lib/dataLayer.tsx, lib/formBuilder.tsx
Quick fix for typescript warning about using type `any`.  Also quick type change for dataLayer formID input from number to string.
=> Small quick changes

components/forms/Dropdown/Dropdown.tsx, components/forms/FormGroup/FormGroup.tsx, components/forms/Forms.js, components/globals/LanguageToggle.js, lib/formBuilder.tsx
This PR fixes the follwoing accessibility issues:
Using Google Dev Tools Lighthouse or Deque Axe plugin scan any form page.
There are still questions surrounding how the accessibility of the Form section headings as well as instructions should be implemented.
=> Accessibility Fixes in Form Generator

.github/workflows/staging-deploy.yml
This repo should not be impacted by the issue that Covid Alert Server
ran into while trying to deploy to ECS using an old Github Action.
However we should still pin to long SHA's for security reasons.
See: https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
=> fix: pin to long form commit SHA for actions.

forms/award.json, forms/baggage.json, forms/callback.json, forms/esdc.json, forms/esdc_accessibility_fund_FOR-DEMO.json, forms/intake.json, forms/lostfishgear.json, forms/securityclearanceform.json, lib/dataLayer.tsx, pages/index.js, pages/sandbox.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
This PR introduces a new page `sandbox` that will display the links to all forms that have their `publishingStatus` set to `false`.  The form titles are no longer using static i18n json but instead the internationalization is using the bilingual forms titles as set on the form json object.
The `welcome` page will only display the forms that have their `publishingStatus` set to `true` and implements the same i18n changes.
It is no longer required to manually add links to either page when a new form is uploaded as both pages are now dynamically driven by all forms under the `forms` folder at the root of the project.
=> Welcome page for Staging

components/globals/Fip.js, components/globals/Footer.js, components/globals/LanguageToggle.js, components/globals/PhaseBanner.js, styles/_base.scss, styles/_forms.scss, styles/_header.scss
> Phasebanner.js
> Fip.js
> LanguageToggle.js
> Footer.js
In doing so, I deleted some of the queries that were breaking due to some of the new classes etc. (I'll fix this when I start working on some of the smaller screen styles)
|  Before |  After  |
|---|---|
|  <img width="1552" alt="Screen Shot 2021-02-04 at 19 03 51" src="https://user-images.githubusercontent.com/30609058/106970989-fceb7780-671b-11eb-8c0f-16678060b7c8.png"> <img width="1552" alt="Screen Shot 2021-02-04 at 19 03 48" src="https://user-images.githubusercontent.com/30609058/106970992-fe1ca480-671b-11eb-9eaa-cf713e280223.png">  |  <img width="1552" alt="Screen Shot 2021-02-04 at 19 04 01" src="https://user-images.githubusercontent.com/30609058/106971024-0f65b100-671c-11eb-9eef-c7012c3d853e.png"> <img width="1552" …
=> Layout Fix

components/globals/Base.js
This PR adds the Google Analytics tracking code to the Base page.  The GA script will only render when NODE_ENV is set to production.  Once we have multiple deployment environments (staging and production) we can revisit this setup.
=> Add GA code

forms/platform_intake.json
First draft of the CDS platform intake form (WITH copy and design changes, see below)
**JSON TO-DOs BEFORE GOING LIVE:**
- add the recipient email address (currently set to `tbd@cds-snc.ca`) ✅
- clear design and copy changes with ... Elodie? Who owns this form @srtalbot ?
- update French copy for the following line: `Veuillez ajouter des courriels séparés par des virgules ci-dessus.` to match the new English copy `Separate each email address with a comma.` cc @mcman12 if you have a moment? This is the only translation change needed
**Design & copy changes:**
- Removed the “Platform CDS” header from the page. Rationale: it sits outside the page hierarchy and isn’t needed when the form title is clear. We also don't have a component that renders such an element right now, nor is it …
=> Upload the CDS platform intake form JSON

lib/logger.tsx
This PR does a small refactor to the logMessage functionality.  It now appends the 'client side log' after JSON stringify has run on the error message object/array
=> Stringify error before appending CSL

forms/forests_early.json, forms/forests_future.json
the forests forms should not be shown on the main page, so setting the publish status to false.
=> set publish status to false

components/forms/FormGroup/FormGroup.tsx
This PR fixes and A11y issue where the Form Group element did not have an ID (only a name) and the label therefore could not be correctly associated to it.
=> Add id back to FormGroup

Dockerfile
This PR fixes an issue with the Docker Image.  The new i18n package requires the config file to also be available after the NextJS package is built.
=> Need to include next-i18next config

forms/TSB-contact.json
- Validate email and text fields via `type` in the TSB form
=> Add validation types to TSB form

pages/index.js
The remaining violations in the a11y scanner have to do with the fact that we don't have a < h1 > on the homepage [(see scan here)](https://a11y-tools-query.herokuapp.com/reports/d1fd1c478b318f3c0683872bcf93f75d45e20e3af6811660948fea48b0749661). I've added a generic "GC Forms" "GC Formulaires" title here.
This is just a placeholder, and happy to adjust the title or styling! I am not sure if I should tag in any of the designers on the team here, or flag on slack?
=> Added a generic h1 to the main page for a11y

.gitignore
I was running Storybook locally and noticed it added close to 50 files under this directory. We probably want to ignore this directory so nothing gets accidentally committed?
=> Update git ignore to exclude storybook static directory

forms/TSB-contact.json
A non email field was set to type: email, causing validation issues
=> Fix TSB email validation bug

components/forms/TextPage/TextPage.tsx, pages/id/[form]/[[...step]].js
Considering that the confirmation page doesn't receive the `pageText` from the URL query anymore, rather via the `formMetadata` property, we don't need to strigify/parse the values.
=> Fix blank confirmation page due to stringify/parse

lib/dataLayer.tsx, lib/formBuilder.tsx, lib/tests/dataLayer.test.js, pages/api/submit.js
This PR has a few small changes:
- Aligns logic around form values and form data to center on the `form.elements` array as the source of truth and leaves `form.layout` only the source of truth for form rendering
- Filters out any `richText` elements from the `formMetaData` passed to the submit API to ensure that any urls in richText do not block the form submission at the  AWS firewall. This is only needed until we can host the form templates in their own DB or API.
- Removes check for element ID's in the `layout` property that do no exist in elements.  This is likely to occur now that we are filtering out the richText elements from the array however their ID still appears in the `layout` property.  The associated test for this check is also removed.
=> Remote File Inclusion - AWS Firewall blocking form submissions

cypress/integration/platform_intake_spec.js, cypress/integration/tsb_contact.spec.js
This PR adds a test for the TSB form and updates the platform intake one:
- Reads the form config file, for formMetadata
- Checks the brand/logo, if applicable
- Checks for text on the confirmation page
Note: I descoped the work, but plan to continue and add fixtures that allow us to dynamically test both EN and FR versions of the forms, all fields, etc
=> Update cypress tests to check for brand/logo and confirmation text

styles/_header.scss
I tried inline-block but that made our default SVG disappear. Block seems to work with both .pngs and .svgs
=> Add block style to logo so that focus state appears when the logo has focus

components/forms/Label/Label.tsx, components/forms/TextArea/TextArea.test.js, components/forms/TextInput/TextInput.test.js, lib/formBuilder.tsx, styles/_forms.scss
As per WCAG, meaningful content should not be inserted using CSS pseudo elements. This PR moves the asterisk indicated a required field into a <span> within the label element. I've also added an aria label to it so that screenreaders will read "required" instead of "star" or "asterisk" when reading it out.
I'm making this as a draft because currently the new asterisk is a separate readout from the label, requiring an extra tab to navigate through, and i'd like to improve that.
UPDATE: upon further research this is how screen readers are expected to work, and so I'm marking this as ready for review.
=> Render and read the asterisk on required fields more accessibly

styles/_forms.scss, tailwind.config.js
Title is pretty self explanatory. Basically just matches the :before style we're using a bit more but transparent so that it doesn't show up. In my local testing, it looks how I would expect it to look. (I compared to Notify and it looks and behaves the same as there from what I can tell).
=> Update checkbox styles to avoid visual bug when using a screenreader

components/forms/Label/Label.tsx, components/globals/LanguageToggle.js, lib/tests/setupTests.ts, public/static/locales/en/common.json, public/static/locales/fr/common.json, styles/_header.scss
Updated the accessibility of the LanguageToggle component, by removing the `<h2>` and replacing with a label.
My biggest outstanding complaint with the language toggle is that when you change the page while using a screenreader, the screenreader does not give any indication that the page or content has changed. Ideally it would read out the new title of the page or somehow otherwise indicate that the content has changed. It looks like this is an area of active work for next.js so we should keep an eye on their updates.
Also iterated on the required field (*) readout - as Screenreader was still reading out the asterisk.
Now it reads out 
`label name ->  "required" -> input description` in successive tabs. Still not perfect but I'm happier with it.
This iteration also required translating …
=> A11y iterations for LanguageToggle and required fields

styles/_forms.scss
The checkbox and radio input element were normally hidden behind the styled label-input except when a label spanned multiple lines.  This PR aligns the input element and the label element so that one is always hidden by the other.
| Before | After |
|:-----:|:------:|
|![Screen Shot 2021-05-03 at 12 12 54 PM](https://user-images.githubusercontent.com/25329319/116903062-eadd8000-ac09-11eb-987d-748bee785f26.png)|![Screen Shot 2021-05-03 at 12 15 49 PM](https://user-images.githubusercontent.com/25329319/116903037-e31ddb80-ac09-11eb-8311-40abf60b63b1.png)|
=> Checkbox input mis-aligned on multi-line label

components/forms/TextInput/TextInput.tsx, documentation/Forms/FormViewer.stories.mdx, lib/formBuilder.tsx
We already supported the "name" type in the json for validation purposes. This PR just extrapolates this and allows input type="name" and autocomplete="name" to be possible now when this type is used.
Enabling these properties when possible is a best practice for accessibility: https://www.w3.org/TR/WCAG21/#input-purposes
=> Enable input type and autocomplete for "name" type 

components/forms/Form/Form.tsx, components/forms/Label/Label.tsx, lib/formBuilder.tsx, lib/validation.tsx
In this PR, there are two fixes for validation accessibility:
1. When errors appear at the top of the form, the focus will shift to that error container
2. When clicking on an error link in this container (error alert box), you’ll be “scrolledIntoView” of the label that sits above the input field and the field will have focus on it (previously it would scroll directly into the input field, so the label text couldn't be seen)
*Note: open to future improvements, if we find a way to not use JS
=> Fix accessibility issues with error messages 

next-i18next.config.js
This PR implements a fix that is caused by the next-i18next package that leverages react-i18next under the hood.  It tries to use `Suspense` however given that some of the pages are rendered server side the `Suspense` function doesn't exist.
Solution posted here on  [NextJS github repo](https://github.com/vercel/next.js/issues/22508)
=> Wait for i18n to initialize

.storybook/main.js, documentation/Forms/AccessibilityReport.stories.mdx, documentation/Forms/FormViewer.stories.mdx
- Similarly to how EN (covid alert) has their "[Accessibility Report]( https://github.com/cds-snc/covid-alert-documentation/blob/main/AccessibilityReport.md)" in their repo, I've added our version by slightly modifying their text
- Also, storybook was broken (components like Label uses translations) as it couldn't resolve i18n but found [a fix to resolve via alias](https://github.com/isaachinman/next-i18next/issues/935#issuecomment-802001105)
Note: I'll update Storybook via `gh-pages` after merging this PR.
=> Add accessibility report docs and fix storybook

documentation/Forms/FormViewer.stories.mdx, forms/TSB-contact.json, lib/dataLayer.tsx, lib/markdown.tsx, lib/tests/markdown.test.js, lib/types.tsx, pages/api/submit.js
- This PR adds a new field in EN/FR to allow customizing the email subject line for the form
- Tests/Docs updated
TODO: update the terraform repos as well ([staging PR](https://github.com/cds-snc/forms-staging-terraform/pull/14) and [prod](https://github.com/cds-snc/forms-production-terraform/blob/main/forms/aws/lambda/reliability/reliability.js#L38))
=> Add emailSubject field to JSON config to allow customizing it per form

pages/admin/upload.js, pages/api/templates.js
Restructuring the api/templates route to actually accept and handle post POST and GET requests, to hopefully unblock @bryan-robitaille 
Also added a quick fix to just return null if the lambda has timed out instead of bringing down the whole app. Will brainstorm methods to reduce lambda timeouts tomorrow!
=> Expose GET method in api/templates, and don't crash the app if the lambda times out

lib/dataLayer.tsx, pages/admin/index.tsx, pages/admin/vault.tsx, pages/api/retrieval.js, pages/api/submit.js, public/static/locales/en/admin-login.json, public/static/locales/en/admin-vault.json
This PR creates a new page `/admin/vault` and a new api endpoint `/api/retrieval` that request through a lambda function submissions that have been stored in the vault for a specific form.  Both the `/admin/vault` page and `/api/retrieval` api are protected through auth.  Designs are obviously to be iterated upon.
| Search for Form 45 | Response 1 | Response 2 |
|:-----:|:----:|:----:|
|![Screen Shot 2021-05-19 at 1 39 39 PM](https://user-images.githubusercontent.com/25329319/118859366-246be780-b8a8-11eb-9961-01a10fe153c4.png)| ![Screen Shot 2021-05-19 at 1 40 14 PM](https://user-images.githubusercontent.com/25329319/118859386-2b92f580-b8a8-11eb-9c42-2642e5fb1cdd.png) | ![Screen Shot 2021-05-19 at 1 40 24 PM](https://user-images.githubusercontent.com/25329319/118859410-3188d680-b8a8-11eb-8 …
=> Get vault submission to nextJS page

styles/_base.scss, styles/_forms.scss, styles/_header.scss
With the way `hover` works on mobile it was triggering the hover state and the active state at the same time. The result was blue text on a dark background (gross!). 
The active styles have been updated to have white text so they will overwrite the hover state as the button is touched.
=> Add white text to active state for mobile

components/globals/Base.js, documentation/Introduction.stories.mdx, pages/id/[form]/[[...step]].js
- If we pass the `?embed=true` parameter to a form url, the header and the footer won't be shown
- Updated docs to indicate how to embed in an iframe
```
<iframe src="https://forms-formulaires.alpha.canada.ca/id/20?embed=true" title="Form description title"></iframe>
```
=> Hide header/footer if embedding a form within an iframe

cypress.json, package.json, pages/admin/vault.tsx, pages/api/retrieval.js, pages/api/submit.tsx, public/static/locales/en/admin-vault.json, public/static/locales/fr/admin-vault.json
This PR adds the functionality to mark a form submission as processed and removes it from the Vault storage.
| Reading form submission | Form submission processed|
|:----:|:----:|
|![Screen Shot 2021-05-26 at 3 45 56 PM](https://user-images.githubusercontent.com/25329319/119721812-93fa4d80-be39-11eb-9c5e-62d55ec4fef4.png)|![Screen Shot 2021-05-26 at 3 46 22 PM](https://user-images.githubusercontent.com/25329319/119721809-92308a00-be39-11eb-884e-73cddcf31c01.png)
It also adds a new env var called `CYPRESS` when started with `yarn start:test` that ensures cypress does not actually submit forms.
Also increased Cypress command timeout to 10s from 4s.
=> Vault response delete

components/containers/DynamicForm/Settings.test.js, components/containers/DynamicForm/Settings.tsx, components/forms/JsonUpload/JsonUpload.tsx, public/static/locales/en/admin-templates.json
This PR adds several small UI updates to help give feedback on user actions.
- When creating a form, the page redirects to the settings page for the newly create form on success.
- When updating the JSON of an existing form on the settings page, a small success message appears beside the upload button once the request is successful
- When deleting a form, the user is first asked to confirm the deletion before it goes through - to make deleting a little less easy to accidentally do
=> Add redirects and confirmations for uploads and deletes

.github/workflows/cypress.yml, .github/workflows/eslint.yml, .github/workflows/jest.yml, .github/workflows/prod-build-push-container.yml, .github/workflows/staging-build-push-container.yml
This PR adds dependencies on the GitHub actions that build and deploy the code to AWS.  This ensures that even on a merge if the automated tests fail for any reason the code will not be deployed.
=> Run tests on push

pages/admin/vault.tsx, public/static/locales/en/admin-vault.json, public/static/locales/fr/admin-vault.json
After a form with at least one entry is looked up in the vault, a "Delete all Responses" button now appears below the form entries. This uses similar logic to the Delete Form button I implemented on the Settings page (in that there's a confirmation and second button before the request goes through).
I also added a small useEffect() hook to allow the "Look up Responses" button to display a different amount of entries if it has changed since the page was loaded. Example - if you have a vault tab open and a tab open and submit a form, the vault tab wouldn't pick up on the new submission without a hard refresh.
Feel free to use form 196 or a new form to test.
I added this function to the vault page instead of as an option when deleting a form on the Settings page to avoid outstanding policy …
=> Added "Delete all responses" per form to the vault

components/containers/Dashboard/DataView.tsx, lib/types.tsx, public/static/locales/en/admin-templates.json, public/static/locales/fr/admin-templates.json, styles/_base.scss
A quick sandbox update to the 'view form templates' admin page.
Since we now have a form settings page, and we have quite a lot of forms, printing out the form JSON on this page was not very useful, and not very readable.
I've streamlined the page to just show the id and internal name of the form, and the full JSON can be viewed on the settings page by clicking the Edit button
=> Make form templates page more readable

.github/workflows/jest.yml, lib/tests/dataLayer.test.js
Remove annotations from GitHub actions so that external collaborators can not have github actions fail on PR's due to lack of write access.
Will improve by implementing pull_request_target in separate action that handles artifacts and writes to the PR in the future.
=> Remove annotations and commenting from GitHub actions for now

next.config.js, package.json, pages/api/version.js
Adds `/api/version` which shows the current app version from the VERSION file, and also the current contents of the changelog file.
Also syncs the version in package.json with the new VERSION file. We'll need to note that we need to keep these values in sync (not that anything bad will happen if we don't, it's just good practice)
=> Add api route to view app version

components/forms/Checkbox/Checkbox.test.js, components/forms/Dropdown/Dropdown.test.js, components/forms/Label/Label.tsx, components/forms/Radio/Radio.test.js, components/forms/TextArea/TextArea.test.js, components/forms/TextInput/TextInput.test.js, lib/tests/validation.test.js
Recently, #220 exposed that our validation was non functional for checkboxes and radios.
In this PR I have written more tests around validation for existing components, to ensure that both a) the asterisk and other associated 'required' elements render on a required field, and b) an error is thrown if the field is empty.
I heavily rewrote validation.test.js to leverage jest.each using test cases. I converted all the existing text validation cases to this format, and then added one for testing whether a required field was filled for each other type of input element we currently have.
=> Round out component validation tests

components/forms/Form/Form.tsx, components/globals/Base.js
Adds google tag manager with a custom data event on form submission.  Included in the event are custom Data Layer variables including the `formID` and `formTitle` for form identification.
No additional user information is sent as part of this form submission event.
closes #237
=> Add google tag manager

pages/id/[form]/[[...step]].js, pages/id/[form]/settings.tsx, pages/sandbox.js, public/static/locales/fr/error.json
This PR enables temporary routing for existing published form Ids.  A grace period of 1 week will be provided to allow for our clients to change their website links to leverage the newly assigned form Ids after which the temporary routing in code will be removed.
This PR also fixes:
- French translation issues on the 404 page.
- Adds context.locale to redirects invoked in the getServerSideProps functions to ensure the user is sent to the proper locale page.
=> Temp routing

lib/dataLayer.tsx
Once you have the local infrastructure setup running, simply add the following line to your .env to enable hitting your local template lambda:
`LOCAL_LAMBDA_ENDPOINT=http://127.0.0.1:3001`
=> Enable local template lambda

CHANGELOG.md, lib/logger.tsx, lib/tests/logger.test.js, pages/admin/vault.tsx, pages/api/submit.tsx, pages/api/templates.js
This PR removes left over debugging `console.logs()`, reduces the production level logger level to `warn` from `info`, and fixes an issue when the Reliability Queue feature is turned off.  
When the 'Send to Reliability Queue' feature is turned off the Submit API was returning an error to the form client when it should have been returning a 200 success.
=> Quick fixes

pages/sandbox.js
Fix for a good ol' copy and paste issue when duplicating functionality across pages.
=> Fix sandbox page showing published instead of unpublished forms

lib/dataLayer.tsx, pages/api/retrieval.js, pages/api/submit.tsx
Instantiate Lambda client at module level instead of within function call.
Will hopefully reduce error rate on high load.
Also setting a retry strategy.
=> Lambda performance enhancements

SECURITY.md, pages/api/submit.tsx
This PR is to update the security readme and to set an upper limit to the amount of data received by the formidable form. If this form requires more than 8 MB please add a review comment and i'll update my PR.
Rejecting requests with significant content length is a good practice to control the network traffic intensity and thus resource consumption in order to prevents Denial of Service attacks. By default the formidable form accepts up to 200 MB of data and is typically never exceeded by the majority of applications by a significant margin.
For most of the features of an application, it is recommended to limit the size of requests to:
- lower or equal to 8mb for file uploads.
- lower or equal to 2mb for other requests.
- Service disruptions due to a malicious user submitting forms of 200 …
=> refactor: minor security improvement

components/forms/FormGroup/FormGroup.tsx, components/forms/Label/Label.tsx, lib/formBuilder.tsx
Fix for #306 .
This PR slightly adjusts the markup in radio and checkbox groups in order to better support Screen readers.
Previously, screen readers would not identify checkbox and radio groups as "groups" for navigation purposes, but would rather just read out the label and inputs separately. This is not the correct behaviour and caused confusion in user testing.
VoiceOver now correctly identifies the fieldset element around these elements as a group. It seems like the key was using a legend instead of a label in these groups, and eliminating extraneous divs.
=> Group radio and checkboxes correctly for screen reader support

components/forms/Checkbox/Checkbox.test.js, components/forms/Dropdown/Dropdown.test.js, components/forms/FormGroup/FormGroup.test.js, components/forms/Radio/Radio.test.js, components/forms/TextArea/TextArea.test.js, components/forms/TextInput/TextInput.test.js
Fix for #291 .
Now using the official replacement for `toHaveDescription` https://github.com/testing-library/jest-dom#tohavedescription
=> Fixed use of deprecated Jest toHaveDescription function

CHANGELOG.md, lib/cache.tsx
Fixes the sandbox page displaying only published forms.
Issue: Redis key was duplicated between both published and unpublished cache.
closes #310
=> Set correct redis key for unpublished forms

lib/formBuilder.tsx
This PR fixes a bug where a form will not render if a dynamic row contains a `richText` form element.
=> bug fix - dynamic row initial value

components/forms/RichText/RichText.tsx, components/forms/TextPage/TextPage.tsx, cypress/integration/cds_intake.spec.js
closes #319 
Special shout out to @craigzour  detective work!
- Used useEffect and tabIndex to make h1 heading be focused on page load for the confirmation page. 
- Added an override to the markdown-to-jsx library to add tabIndex -1 to h1 elements in RichText component
- Added cypress test to test that h1 is focusable when page is loaded 
1. Pull down changes
2. Turn voice over on 
3. Complete form and press submit ( whichever form you please )
4. Observe screen reader reading the h1 element on the confirmation page
N/A
N/A
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code …
=> Make screen reader announce heading on confirmation page

pages/_document.js
In staging the CSP contains repeated versions of the generated script hashes.
Could not replicate locally however added a logic check to not add a hash value if it is already contained in the array.
=> Fix hashes repeated in Content Security Policy

CHANGELOG.md, lib/integration/helpers.ts, lib/tests/helpers.test.js, pages/api/submit.ts
Part 1/2 to close #336 
- Send language of the submission to the Next JS submission API through the `Content-Language` header
- Add a language key/value with this value assuming english as the default to the payload sent to the Submission Lambda
- Fix mixed async/await and promise code styles in `processFormData` and `callLambda` functions 
- Renamed `submit.tsx` to `submit.ts`, this is because there are no TSX components. 
You should be able to confirm it works through the modified unit tests. Otherwise you can console.log the req headers in the submit API handler to confirm the presence of the `Content-Language` header
N/A
=> feat: add language of submission to submission data

.github/ISSUE_TEMPLATE/manual-accessibility-test-routine.md
Made AxeDev tools optional, as only some developers have access and automated tests use them on every PR.
=> Update manual accessibility template

.github/workflows/staging-deploy.yml, .github/workflows/weekly-dynamic-security-scan.yml
This PR adds a call to the Scan websites tool into the CI pipeline. After the client component has been deployed it will make an API call to the static (read-only traffic) tracking tools API that request a spidering of the public facing pages of both the english and french domains.
This also adds a weekly call to the Scan websites tool to run dynamic security testing every Sunday.
=> feat: mirror a11y tracker and run dynamic security scans weekly

CHANGELOG.md, components/globals/Base.js, pages/_document.js
This PR ensures that the Google Tag Manager Iframe only appears in Production.  It appears some of the Google Analytics from Staging and Local are finding their way in.  Hoping this will solve the issue.
In _document.js change the logic to not check for the forms-formulaires.alpha.canada.ca domain.  In the elements in Dev Tools you should see the script appear. 
=> fix: Analytics Iframe only on prod url page

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/dynamic_rows.spec.js, cypress/integration/forms_functionality.spec.js, cypress/integration/platform_intake_spec.js, cypress/integration/tsb_contact.spec.js, cypress/integration/welcome_page.spec.js
The baseUrl, or any explicit reference to http://localhost:3000 in the Cypress test is redundant, since the baseUrl is configured in the cypress.json config file.
Run the cypress tests. The tests should pass, connecting to http://localhost:3000 as defined in the config file.
=> test: remove redundant baseurl

.storybook/main.js
This change fixes a configuration issue with Storyboard. This allows it to find the folders `./lib` and `./components` when referenced as `@lib` and `@components`. The change is limited in scope to only when executed for **Storyboard**, it will have no impact on any other build or tests.
Run Storyboard. It should compile and execute properly. If any of the stories are for components, check to see the import paths in the component itself (not the `*.stories.*` file. The import paths should be able to include `@lib`.
=> fix: path mapping for `@lib` and `@components`

lib/integration/helpers.ts
This PR increases the submit timeout from 5 to 60 seconds.  The increase is due to file uploads taking additional upload time vs just sending json data.
=> Increase axios timeout of submit function to 60 seconds

CHANGELOG.md, pages/api/token/temporary.ts
closes #616
linked to https://github.com/cds-snc/forms-terraform/pull/176
- Log error when we detect that we failed to generate a temporary token. It will get into our ECS Log group in CloudWatch. We can then pattern match it in order to trigger an alarm.
=> feat: log error when we failed to generate temporary token

CHANGELOG.md, components/forms/Form/Form.test.js, components/forms/Form/Form.tsx
closes #160 
The problem stemmed from component refreshes when setting state. `setSubmit` was called in the onSubmit handler for the form element. This resulted in the component refreshing and the useEffect hook being executed. What this meant was when submitting a form after an initial submit was done with errors, the `isValid` prop was still false and when `setSubmit(true)` was executed, the component was refreshed and `setFocusOnErrorMessage` was called. This resulted in scrolling to the top of the page even when no errors were present.
The fix was simply to use the state provided by the HOC `withFormik` isSubmitting as opposed to any internal state for the lower component. This means that validation will be done before any refreshes happen and isValidate will be correctly set. …
=> fix: Use formik state as opposed to child state to fix submission glitch

components/forms/Form/Form.tsx
There is no issue for this fix. I noticed that the submit button had a duplicate `className` value: `className="gc-button gc-button"`. The <Button> component adds the `gc-button` class by default, so it is not required when initializing the component.
The submit button should appear and function exactly as before. Upon inspecting the code, the extra `gc-button` class should no longer be there.
=> fix: Remove extra className value on submit button

components/forms/Form/Form.tsx
No issue number 
The method attribute for the Form components `form` element [was removed in a previous PR](https://github.com/cds-snc/platform-forms-client/commit/a4bf8a418e5edf520487211c40ded257810fc4bf#diff-f751526980cd88e552ac46936f9a21062f6796fdd1ed5d6b3dbe918f9b0121b0L80-L81) as I thought it was redundant. I had not considered that if the javascript failed to load following that this would result in a GET request when the submit button was pressed resulting in data leakage in the URL.
N/A
N/A
=> fix: add method attribute with a value of POST to the form

components/forms/TextInput/TextInput.test.js, components/forms/TextInput/TextInput.tsx, documentation/Forms/FormViewer.stories.mdx, lib/formBuilder.tsx
Closes #626 
- Update a config for a form to include the `autoComplete` attribute. For example:
`      {
"id": 4,
"type": "textField",
"properties": {
"titleEn": "Address",
"titleFr": "Adresse",
"autoComplete": "street-address",
"validation": {
"required": false
},
}
}`
- Load a form, and inspect that the code includes `autocomplete="street-address"` for the modified textField.
- Please note that there is a specific list of allowed values for `autoComplete`: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens
=> feat: autoComplete attribute on textField

CHANGELOG.md, components/forms/Checkbox/Checkbox.test.js, components/forms/Dropdown/Dropdown.test.js, components/forms/Label/Label.tsx, components/forms/Radio/Radio.test.js, components/forms/TextArea/TextArea.test.js, components/forms/TextInput/TextInput.test.js, public/static/locales/en/common.json, public/static/locales/fr/common.json
Closes #625 - Replace the asterisk on required fields with copy:  "(required)" / "(obligatoire)"
| 
| 
|
- Load a form with required form elements.
- The asterisk should not appear, and the copy "(required)" / "(obligatoire)" should appear.
=> feat: Replace 'asterisk' with 'required'.

CHANGELOG.md, components/forms/Form/Form.tsx, lib/tests/validation.test.js, lib/validation.tsx
Closes #521 
This will loop through the list of errors generated by Formik and match them up with the list of elements in the form itself.
The UI changes to this are imperceivable as a screenshot, since it's only the anchor for the link that changed.
- Create a form config where the `layout` ids are not in sequential order. 
- Submit a blank form, generating lots of errors.
- Verify that the links in the error list match and go to the correct form elements.
=> fix: Sort the error summary to match the displayed elements.

CHANGELOG.md, package.json, styles/_forms.scss, yarn.lock
Sets the list position style explicitly to 'inside' so the decimal or bullet markers are inline with the beginning of the text.
|![Screen Shot 2022-03-09 at 3 29 58 PM](https://user-images.githubusercontent.com/25329319/157531401-072e4e91-5506-46d1-9a12-f9dd4a0d9b51.png)|![Screen Shot 2022-03-09 at 3 29 14 PM](https://user-images.githubusercontent.com/25329319/157531350-8776b019-d24b-439f-a37b-248a3c3061a5.png)|
=> Set list position to be inside (inline with text start)

CHANGELOG.md, components/forms/Dropdown/Dropdown.test.js, components/forms/Dropdown/Dropdown.tsx, lib/tests/formBuilder.test.js, public/static/locales/en/common.json, public/static/locales/fr/common.json
closes #623
- Modified default selected value so that it is now displayed with a text instead of being an hidden option (which did not work properly on all browsers)
Following Before/After is based on Safari:
|<img width="1198" alt="68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565346439396532623837383165373739306237653863632f39613565383064622d366166302d346366362d613732632d626139366136336431333164" src="https://user-images.githubusercontent.com/1763961/157903507-29160895-d70e-49ac-86a4-ec61727044a9.png">|<img width="537" alt="Screen Shot 2022-03-11 at 11 04 06 AM" …
=> fix: dropdown default selected value is now displayed with text

components/forms/Label/Label.tsx, pages/api/templates.ts
The removed code is redundant for non-group form elements. If a element is already marked as `required`, then the screen reader will read out: "Full name required required", since it is reading out the visually-hidden copy of `required`, as well as the `required` attribute for the form elements (ie: `input`, `textarea`, etc..).
- load a form with required elements
- tabbing through the form elements should only read out `required` only once per element, regardless if it is a group element or not
=> fix: remove redundant `required` copy.

lib/validation.tsx
Adresses #676 
A checkbox group with **required** as the validation means that at least one checkbox needs to be selected.
With the current deployment, if a checkbox is selected and then deselected, the form validation will treat the "required" requirement of that checkbox group as satisfied, and pass the form validation.
Test against form **308** on staging.
- in all cases, a checkbox group that is required, and has no boxes selected should fail the validation
- upon loading the form, submit without selecting any of the checkboxes. Validation should fail.
- upon loading the form, select and then deselect the same checkbox. Submit the form. Validation should fail.
- select and then deselect any random combination of the checkboxes. End with all of them deselected.  Submit the form. …
=> fix: ensures a required checkbox group has at least one checkbox selected

.github/workflows/prod-build-push-container.yml
Fixing a line in the production build script, that was missing a `\` at the end of a line, which caused the command to be truncated.
=> Added missing line ending.

lib/middleware/schemas/templates.schema.json
There is no PR for this issue.
It was noticed that the definition for `submission` was not included in the schema. Added the definition, with the 2 possible properties: `email` and `vault`.
=> feature: Add the submission object.

lib/integration/crud.ts, lib/types.ts, pages/admin/view-templates.tsx, pages/api/templates.ts
Closes #786 
Created a recursive function to retrieve the form templates in batches. This adds parameters for `limit` and `offset`, to request only some form templates in each call to the lambda function, ensuring that each batch is below the 1MB limit. It will merge all the batches together, and return all templates back to the calling function.
- PR 211 on the `forms-terraform` repo will need to be merged in first in order to test.
- The database will need to have more than 50 forms in the `templates` table in order to test this.
- Visit the `/admin/view-templates` page, and observe that all templates are returned.
- All jest and cypress tests should pass too.
What should the default `limit` be? Currently set at 50, but I suspect it could be quite a bit higher than that, and still be …
=> fix: add `'limit` and `offset` the the crudTemplates call, retrieving the templates in batches

.github/workflows/codeql-analysis.yml
Updates CodeQL scanning action to V2.  Version 1 warning found in logs that V1 will be decommissioned and no longer supported in December 2022.
=> CodeQL version bump to v2

app.json, package.json
This PR removes the Heroku specific configuration that was used for the preview app.
Seeing as we're no longer used the preview app feature this configuration can be safely removed.
=> Remove Heroku Specific Configuration

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/scripts/forms-dev-entrypoint.sh
Currently the devcontainer is using the incorrect user, so the shell is defaulting to the root user. This PR fixes that, as well as introducing a devcontainer helper post create script to setup the basics.
=> fix: update devcontainer to not use root user

.github/workflows/staging-deploy.yml
- Just a little fix for the staging deploy Github action to make it send the existing slack alert to the right channel
=> fix: sending slack alert on form-deploy-activities when something goes wrong in the staging deploy Github action

.github/workflows/staging-build-push-container.yml
Add the missing `ECR_REGISTRY` environment variable that's used
to identify the Docker image that will be used to generate the SBOM.
* #802
=> fix: form viewer Docker SBOM generate

.devcontainer/docker-compose.yml
Update the devcontainer docker-compose to no longer
explicitly link the services.  
This is because `links` are no longer required as all 
services implicitly share the same Docker network.
=> fix: remove service links from devcontainer docker-compose

pages/api/token/temporary.ts
Closes #839.
The problem was solved by escaping the double underscore that is interpreted by Markdown as bold. While other characters used for Markdown syntax could be improperly rendered by a Notify template, only the underscore can be used in a token.
- modify `temporary.ts` to have a hardcoded temporary token that contains a double underscore
- modify `temporary.ts` to send email to `forms-formulaires@cds-snc.ca`.
- use the api to request a temporary token for a valid form / email on your local install
- check the email for `forms-formulaires@cds-snc.ca` to see an email with the hardcoded temporary token that contains a double underscore.
=> fix: escape markdown characters

CHANGELOG.md, components/globals/Base.js, components/globals/Footer.js, cypress/integration/tsb_contact_remove_footer_gc_word.spec.js, lib/middleware/schemas/templates.schema.json, lib/types/form-types.ts, tests/data/tsbDisableFooterGCBranding.json
Make Gc branding in the footer configurable via formConfig object. 
closed #804 
1. create or update an existing form like [TSB Form](https://forms-staging.cdssandbox.xyz/id/25)
2. add the new attribute `disableGCBranding = true`   to `brand`  element like so :  
`    "brand": {
"disableGcBranding": true 
},`
3.  It should remove the GC word from the footer.  
As of today, It is not possible to remove the GC branding in the footer for all forms at once. 
The implementation works for forms that have a custom branding enable meaning the `brand` attribute is configured otherwise GC branding will be displayed.  
=> make footer GC branding configurable

Dockerfile
Fixes that prisma folder was not copied to final image in docker creation file.
=> copy prisma folder to final image

pages/api/auth/[...nextauth].ts
- Token variable is not properly initialized when logging in with Google credential provider.
=> fix: uninitialized variable in token creation

CHANGELOG.md, components/admin/JsonUpload/JsonUpload.test.js, components/admin/JsonUpload/JsonUpload.tsx
Closes #897 
When uploading the JSON config for a new form, the page wasn't updating to the `~/settings` page. The data being returned from the API had changed along the way, and didn't match what was being looked for.
Also updated some Jest tests. `submitStatus` was always visible on the screen, even though it may have been empty.
Refactored some code while I was fixing this bug.
Go to the "Template Upload" page, enter some new JSON to be uploaded. After submitting, it should redirect to the `~/settings` page.
All other functionality should remain the same. If uploading empty or corrupt JSON, it should present an error message.  Updating JSON from the `~/settings` page should present the message that the JSON was properly updated.
I noticed that when uploading some JSON, if there is any …
=> fix: json upload bug

.github/workflows/test-container-build-production.yml
Pinning actions/checkout to v2
=> fix: test-container-build-production workflow checkout action not pinned

__fixtures__/accessibilityTestForm.json, cypress/integration/accessibility.spec.js
This PR modifies the Cypress test that previously fetched all Published templates.  The application no longer leverages the Template Lambda from Staging so no forms are currently being scanned.  A new A11y test form is now leveraged that lists every component in GCforms.
=> Use internal a11y form for Cypress

pages/api/submit.ts
The submit API allowed GET, POST, PUT and DELETE API requests which were not CSRF protected. The submit API should have only allowed the POST method and this method should be protected with a CSRF token. 
N/A
N/A
=> fix: URGENT fix. Only allow POST method in the submit API

__tests__/api/flags.test.ts, __tests__/api/id/form/bearer.test.ts, __tests__/api/id/form/owners.test.ts, __tests__/api/templates.test.ts, __tests__/api/users.test.ts, lib/auth.ts, lib/tests/auth.test.ts, lib/tests/sessionExists.test.js, package.json, pages/admin/login.tsx, pages/admin/unauthorized.tsx, types/next_auth/index.d.ts, yarn.lock
This PR updates NextAuth to v4.10 and renames `getServerSession` to `unstable_getServerSession`.
=> Update Next Auth to 4.10

CHANGELOG.md, cypress/integration/logout.spec.js, pages/auth/logout.tsx, public/static/locales/en/logout.json, public/static/locales/fr/logout.json, styles/_forms.scss
closes #945 
- Fixed session end date being displayed on logout page
- Run code contained in fix/logout-last-session-end-date branch
- Navigate to http://localhost:3000/auth/logout
=> fix: logout session end date

.storybook/main.js, __utils__/setupTests.ts, components/forms/Button/DeleteButton.tsx, components/login/SignInKey.test.js, components/login/TemporaryToken.test.js
Since `next-i18next` is being used, there were some references to `react-i18next` that needed to be removed since they were no longer being used.
- All tests should pass successfully
- The `<DeleteButton>` on the settings page of a form should continue to display the correct message in the selected language
=> fix: remove react-i18next references

__tests__/Settings.test.js, components/admin/FormAccess/FormAccess.test.js, components/auth/AcceptableUse.test.js, lib/tests/helpers.test.js
Just tightening up some of our tests.  Any responses that return a status of 200 should be a resolved response, and conversely, any response that is 3xx, 4xx, or 5xx, should be a rejected response.
- All tests should continue to pass
- I am not convinced that our tests are checking for what we want them to be checking for. That being said, I am certain that we should be changing the `mockedResolvedValue` and `mockedRejectedValue` to match the expected status responses.
=> test: adjust mockResolvedValue and mockRejectedValue based on status code

.env.example, .github/workflows/codeql-analysis.yml, __fixtures__/cdsIntakeTestForm.json, pages/api/verify.ts
The Recaptcha V3 Site Key accidentally was added to the codebase.  Removing and redeploying to staging.
The Site Key is already public and is passed client side so no need to recreate.
Also fixing spelling error in Recaptcha.
`Recaptacha` to `Recaptcha`
=> Accidental Recaptcha ID leak.

components/login/TemporaryToken.tsx, public/static/locales/en/login.json, public/static/locales/fr/login.json
(no ticket assigned)
- Fix broken localized error title on temporary token auth page
=> fix: missing localized error title on temporary token auth page

components/form-builder/panel/ElementPanel.tsx
Small fix: ensure there is a `<label>` wrapper around the Required checkbox and text
=> Add label wrapper to Required checkbox

components/login/SignInKey.tsx, components/login/TemporaryToken.tsx
closes #971 
- Added two `aria-describedby` flags in order to get more context on what is expected when specific input is selected
=> fix: a11y in Login UI

components/form-builder/layout/Layout.tsx, components/form-builder/layout/Output.tsx
There's a way to see the JSON output, but we hid it initially because right now we just want to be showing the form builder. 
However, we _do_ want to be able to see the JSON output for the form, for those in the know. 
This PR removes the "hidden" div and adds a click handler to the bottom separator. It's not intuitive at all, but that's also kind of the point.
We can make this permanent later, or maybe we find another place to put this. For now, this is just for devs and for anyone who wants to see what the generated output is.
=> Add click handler that will show/hide the JSON output in the Forms builder

components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx
Very small PR, fixes two problems that were causing console errors:
1. Passing in the `key` as a property.
React is not chill with this, so adding a question was causing console errors. No longer passing in the key solves this.
2. Using the wrong prop type for one of the properties on `PanelActions`
In this one, we're passing in a function that renders an element, not the actual element itself.  The prop type said to expect a string or an element, but that's now out of date. Fixed it to say to expect an element.
=> Form builder bugfix: Don't pass in the key as props

components/form-builder/store/useTemplateStore.ts
Fixes some console errors we were seeing when removing elements or moving them around.
There was a bug I was seeing when either moving form fields or removing a field, which was that a bunch of the fields in the "form" object were being removed. The way that the new "elements" was being updated was correct, but it was resetting the "form" object such that all the other keys were being deleted.
Updated so that the "elements" key is getting replaced without any side effects.
This is an example of the console error being thrown when removing a field.
=> Don't replace the entire "form", just reset the elements

components/globals/Base.js
Closes #989 
| 
|  
|
- login as a Program Administrator (~/auth/login). Observe that the adminNav menu no longer appears on the "policy" or "retrieval" pages.
- login as an admin (~/admin). Observe that the adminNav menu still appears under the `~/settings` page.
=> fix: change isAdmin logic

components/form-builder/__tests__/useTemplateStore.test.ts, components/form-builder/store/useTemplateStore.ts
Previously, duplicated elements were just pushed to the end of the array of elements. This PR changes that behaviour to insert the duplicated element after the element being duplicated.
| ![Screen Recording 2022-09-16 at 10 53 12 AM](https://user-images.githubusercontent.com/1187115/190668692-901ec36b-a1c4-4679-b8cb-407d60b98441.gif) | ![Screen Recording 2022-09-16 at 10 54 15 AM](https://user-images.githubusercontent.com/1187115/190668854-cba18acd-5da7-4f6d-97ef-a19db523f07d.gif) |
- Add multiple elements
- Duplicate one
- Note where the new item gets inserted
Please complete the following …
=> feat: insert at index when duplicating

components/form-builder/icons/BackArrowIcon.tsx, components/form-builder/icons/index.ts, components/form-builder/layout/Preview.tsx, components/form-builder/preview/Form.tsx
When you submit a previewed form, the confirmation page is displayed. This adds a link to return to the Form preview.
Also adds some instructional text next to the Submit button on the form "To preview your confirmation message, click submit"
| Submit label                                        | Return link                                      |
| <img width="797" alt="image" src="https://user-images.githubusercontent.com/1187115/190684275-aca5deb1-7e7a-453b-bade-090e05063f3f.png"> | <img width="676" alt="image" src="https://user-images.githubusercontent.com/1187115/190684325-d26b341d-0152-4ca1-97d1-15c384382c9a.png"> |
- Create a form with elements
- Preview the form
- Notice the new …
=> feat: Add a Return to form link to the confirmation page preview

CHANGELOG.md, lib/templates.ts, lib/tests/templates.test.ts, pages/id/[form]/[[...step]].tsx
The `getTemplateByID` request being made for the forms page was returning non-public form config data. This change sanitizes the data by calling `onlyIncludePublicProperties()` on the form, returning only the properties that can safely be sent to the browser when being requested by an unauthorized user (ie: someone filling out the form).
- Load any form into the browser, as if you were going to fill it out.
- Observe in the browser Developer Tools / Network tab, that the data being sent from the server does not include non-public properties, such as `submission`, or `internalTitleEN`, among other such properties. 
- It should include default values for `displayAlphaBanner` and `securityAttribute`, even if they are not present in the formConfig saved in the …
=> fix: return only public properties for form

__fixtures__/testData.json, __tests__/api/id/form/retrieval.test.ts, __tests__/api/templates.test.ts, __tests__/api/token/temporary.test.ts, __tests__/id/[form]/settings.test.js, components/admin/BearerRefresh/BearerRefresh.stories.tsx, components/admin/FormAccess/FormAccess.test.js, components/admin/JsonUpload/JsonUpload.stories.tsx, components/form-builder/layout/Preview.tsx, components/forms/DynamicRow/DynamicRow.test.js, cypress/support/commands.js, lib/tests/auth.test.ts, lib/tests/helpers.test.js
I noticed that in many of the tests, the `formID` was a number, instead of a string. I thought that this could cause some tests to act unpredictably, and that they should be updated to reflect the fact that `formID` has been changed from a number to a string.
All tests should continue to pass.
=> fix: change formID to strings of proper length

components/admin/JsonUpload/JsonUpload.tsx
Just a small bit of refactoring, that uses optional chaining to define formID, and makes formID optional for the `uploadJson` function. In the case where `formID === undefined` within the function, then it will `POST` the `jsonConfig` (that was existing functionality).
Just making it a little simpler to read. 
- All tests should continue to pass
- In the `/settings` page, upload a JSON Config for a new form
- In the `/settings` page, modify the JSON Config and update it
=> refactor: make formID an optional parameter

components/form-builder/elements/Select.tsx, components/form-builder/preview/Form.tsx, documentation/Forms/FormViewer.stories.mdx, lib/middleware/schemas/templates.schema.json, lib/types/form-types.ts, prisma/seed.ts
Updates the form builder preview to add the introduction and policy fields 
Example link of existing form 
https://forms-staging.cdssandbox.xyz/en/id/25
Longer example:
https://forms-formulaires.alpha.canada.ca/en/id/167
- Create a new form
- Enter content into the introduction and policy locked content areas
- Preview the form
👉  This doesn't update the forms core preview.  Once the design settles we can handle that part with Core.
**Bonus Unrelated Fix**
Updated the element dropdown so it doesn't push the panel open to fit it's content
=> feat: Update form builder preview

__tests__/api/signup/confirm.test.ts, __tests__/api/signup/register.test.ts, __tests__/api/signup/resendconfirmation.test.ts, pages/api/auth/[...nextauth].ts, pages/api/signup/register.ts, pages/api/signup/resendconfirmation.ts
* added new API route with path /api/signup/resendconfirmation to resend confirmation code
* added api tests
=> feat: resend confirmation api

components/form-builder/layout/Layout.tsx, components/form-builder/layout/Preview.tsx, components/form-builder/layout/Save.tsx, components/form-builder/layout/Start.tsx
We need to get the French/English language toggle out of the top nav but we also want it to be available to us.
The compromise here is using the Headings as the toggle, even though it is not something we want to do long-term.
Still easy to click and very unlikely someone will activate it by accident.
=> feat: Double-click headers to switch language

.github/workflows/build-and-deploy-storybooks.yml, .github/workflows/prod-build-push-container.yml, .github/workflows/staging-build-push-container.yml, .github/workflows/test-container-build-production.yml, .github/workflows/test-container-build-staging.yml, jest.config.js
This PR modifies various Github workflow actions to not run when application files do not change.
Ignored files and paths include paths that begin with '.' as well as paths that begin with '__'.  These files and paths are only used for development and are not part of the core application.
A change to a `.github` workflow or a `.vscode` development setting should not trigger an application build and deployment.
Also this PR modifies the jest test coverage to only focus on application files and ignore all other files, including storybook files embedded in the application directory.
=> Do not run deploy workflow when app doesn't change

components/form-builder/layout/Layout.tsx, components/form-builder/layout/Start.tsx
Adds a blue dashed border around the Preview, and redirect to Preview after opening a form file. Also, when you "open a form" on the start screen, redirect to Preview (previously went to Design).
| <img width="1315" alt="image" src="https://user-images.githubusercontent.com/1187115/194409512-5886e9b2-503e-4881-b971-4054f0579e90.png"> | <img width="1309" alt="image" src="https://user-images.githubusercontent.com/1187115/194409446-2844986a-f574-40c0-b1e0-27ffa99262df.png"> |
=> feat: Preview outline and preview after upload

components/form-builder/elements/Option.tsx, components/form-builder/elements/RichTextLocked.tsx, components/form-builder/elements/ShortAnswer.tsx, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/panel/Button.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/plate-editor/RichTextEditor.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
This PR addresses some of the a11y violations flagged by aXe.
In particular:
- adds aria-labels to the "Remove" buttons. There was an aria-label attribute being added to the buttons but they weren't doing anything with it previously.
- use the "description" as an aria-describedby fields for question titles
- added a missing "id" to question titles
- use heading level 2s in our RichTextLocked fields
- add `aria-label`s to our RichTextLocked fields 
There are still some left over related to the RichText field, so I will explain them in the notes.
| 29 aXe violations, uh oh | just 5 now 👍 |
| …
=> fix: Add accessible labels to our Remove buttons

lib/policyBuilder.ts, lib/tests/policyBuilder.test.ts, package.json, pages/admin/privileges.tsx, pages/api/auth/[...nextauth].ts
- Added permission condition interpolation feature
- Added tests for new interpolation function
=> feat: add permission condition interpolation feature

__tests__/api/acceptable-use.test.ts, components/globals/AdminNav.tsx, lib/templates.ts, pages/admin/flags.tsx, pages/admin/form-builder.tsx, pages/admin/login.tsx, pages/admin/privileges.tsx, pages/admin/unauthorized.tsx, pages/admin/upload.tsx, pages/admin/users.tsx, pages/admin/vault.tsx, pages/api/acceptableuse.ts, pages/api/privileges.ts, pages/api/users.ts, pages/id/[form]/retrieval.tsx, pages/id/[form]/settings.tsx
This PR:
- wraps the various pages that require privileges and ensures the user has the minimum privileges required to be interactive.
- fixes a security issue where on acceptable-use API any valid session had the ability to modify any other user's acceptance flag.  The user id is now pulled from the active session and is not passed in the body of the request.
- disables Vault page and API as the feature is not in use until a future major release
-   small refactors for code style commonality and more interactive state changes.
=> Page access restrictions

components/form-builder/elements/RichText.tsx, components/form-builder/elements/RichTextLocked.tsx, components/form-builder/layout/EditNavigation.tsx, components/form-builder/layout/LeftNavigation.tsx, components/form-builder/layout/PreviewNavigation.tsx, components/form-builder/layout/Start.tsx, components/form-builder/lexical-editor/Editor.tsx, components/form-builder/lexical-editor/RichTextEditor.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/translate/RichText.tsx, components/form-builder/translate/Translate.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
This PR brings us more into alignment with what's in the mockups. 
- Our rich text fields are no longer full-width
- The form title looks like a "title" input now (bottom underline) instead of a regular text input
- Tweaked the "design" icon on the start page because it was too small
Where I made CSS changes, I tried to convert things to tailwind as much as I could. There were still some holdouts, but it moves the needle a little bit.
| <img width="1552" alt="Screen Shot 2022-10-27 at 12 07 37" src="https://user-images.githubusercontent.com/2454380/198344297-95c7432d-997a-41d5-8c27-3529ed454717. …
=> fix: Update design for form title and rich text fields

package.json, yarn.lock
Fixes issue where `ts-node` was only listed as a development dependency.
=> Add ts-node to production dependencies

CHANGELOG.md, __tests__/api/templates.test.ts, lib/templates.ts, lib/tests/templates.test.ts, prisma/migrations/20221031124445_add_ttl_to_template/migration.sql, prisma/schema.prisma, prisma/seeds/fixtures/templates.ts
closes https://github.com/cds-snc/platform-forms-client/issues/1166
linked to https://github.com/cds-snc/forms-terraform/pull/271
- Changed the form template delete API function in order to mark them as archived instead of deleting them
- Delete a form template using the admin UI
- It should disappear from the list of templates in the UI but will stay in the database (`yarn prisma:studio`)
=> feat: mark form template as archived instead of deleting them right away

components/form-builder/layout/Header.tsx, components/form-builder/layout/Layout.tsx, components/form-builder/layout/LeftNavigation.tsx, components/form-builder/layout/Settings.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Add a "settings" page that is close to the one in Figma. It the first 2 fields are non-functional, but the delete button works. 
If you click the delete button, it reinitializes the form and navigates you back to the start page. It's super abrupt, so we can ask Sam what to do about this in future.
A also changed the left nav to remove the "Start" nav link. You can now click the top nav button ("GC Forms") to get you back to the form builder landing page.
|  <img width="784" alt="Screenshot 2022-10-31 at 10 47 27" src="https://user-images.githubusercontent.com/2454380/199039152-f7488918-1a55-474f …
=> Add settings page

components/form-builder/elements/Option.tsx, components/form-builder/lexical-editor/RichTextEditor.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/QuestionInput.tsx
Basically, we want to update the value in the field(s) when the language changes.
Before this PR, we were just getting the value that was passed in the first time and it would only be updated when a user starts typing, not when the language changed across the app.
Just to be clear, _saving_ fields is totally fine. When you switch languages and you update an input field, it updates in the right place (the `en` or `fr` value, as required), but the value displayed to users wasn't changing to reflect that.
If you look at a form previous to this PR and you switch between English and French, you won't see the question titles, the form titles, the options or the rich text descriptions change. On this PR, they all change as you would expect.
=> fix: Add useEffect hooks to debounced fields

components/form-builder/hooks/useAllowPublish.tsx
When checking the translation status of form elements, only check choices if the element type is one of radio, checkbox, dropdown. There are a few circumstances where you can erroneously end up with an empty option in the state object, and it would cause the translation check to fail if it was empty. This ensures we're only checking those choices when they element type requires them.
=> Only check translation status of choices for relevant types

components/form-builder/layout/TestDataDelivery.tsx, components/form-builder/preview/Form.tsx, lib/helpers.ts, public/static/locales/en/form-builder.json
This PR updates the form submission to allow a component to handle submitted / sent confirmation vs the form handling via a redirect. 
- Adds a `redirect` param to the submitAPI (defaults to `true`)
https://github.com/cds-snc/platform-forms-client/pull/1236/files#diff-576e7186db8f40050f59e5bbd8384302a870572e8329fd9915eedf2c03c556d7R263
- Adds an onSuccess prop to allow a component to handle rendering success or fail
- Create a form
- Visit Data Delivery
- Save the form
- Send the form
This should result in a confirmation screen for data delivery 
**Temp Screen**
=> Use callback vs redirect for test data delivery

components/form-builder/layout/Layout.tsx, components/form-builder/shared/Button.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
This PR fixes 2 small-ish bugs:
1. When you are editing the email address for the form to send to, you were previously not able to delete the whole string, as it would repopulate with the original email. 
2. The screen reader announcement for the button messages would previously only happen once. 
Now, empty emails are okay while editing (if it is empty when you leave the tab, your previous email will end up in that field again). 
And button messages are reset after the message fades away, so now we are physically removing the message from the DOM rather than just hiding it with CSS. Tested with VoiceOver and it seems like we are good now. …
=> Fix: announce button messages & allow empty emails when editing

components/forms/Form/Form.tsx
Fixes #1272 
There was a typo in the name of the description property that was preventing the English introduction from displaying.
=> Fix typo preventing english intro from displaying

lib/auth.ts, lib/middleware/jsonValidator.ts
No issue for this 
On the policy page when NextJS would issue a hydration request the NextJS server would return a redirect since the requireAuth that wraps getServerSide auth returns a redirect. The solution was not to return a redirect if the path starts with /_next/data which is what the client uses for hydration requests 
Go to the policy page after logging in. Try to switch to french. It should not fail
N/A
=> fix: solve infinite redirect on policy page

components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx, components/form-builder/shared/Button.tsx, components/form-builder/store/useTemplateStore.tsx
The main change in this PR is adding a "highlight" effect when new questions are added or duplicated. It's similar to the Stackoverflow pattern they use when you link directly to an answer ([example here](https://stackoverflow.com/questions/2281087/center-a-div-in-css/2281107#2281107)).
I've also fixed a small layout bug, which happened when you added more than 10 questions.
| The "10" overlaps the question input   |  The "10" does not overlap the input  |
| <img width="819" alt="Screenshot 2022-11-16 at 12 35 15" src="https://user-images.githubusercontent.com/2454380/202253347-8884ed13-c853-441 …
=> Add "highlight" effect when adding/duplicating questions

components/form-builder/__tests__/useTemplateStore.test.tsx, components/form-builder/store/useTemplateStore.tsx
Removes default "my forms" so the form title label gets announced
- visit the form builder
- should no longer default to "my form"
=> Remove default "my form"

components/form-builder/panel/PanelActions.tsx
Fixes a small bug introduced in the previous PR that caused focus to go to the element actions toolbar after adding a new element. This restores the original behaviour that gives focus to the Question when a new element is added.
=> Bugfix: set focus on Question when new element added

pages/form-builder/preview/[[...params]].tsx, pages/form-builder/preview/test-data-delivery.tsx, pages/form-builder/published.tsx, pages/form-builder/save.tsx, pages/form-builder/share/[[...params]].tsx
In the previous refactor PR, some page titles got overwritten by copy/paste. This restores them.
=> Fix form-builder page titles

renovate.json
Update the Renovate config so that non-major GitHub action and Docker digest update PRs are grouped together.
I've been testing these suggestions since our feedback session last week and they're working well to cut down on the PRs.
- cds-snc/platform-core-services#182
=> feat: group Docker and GitHub Renovate updates

components/forms/Form/Form.tsx
Fixes #1368 - Privacy Policy was not displaying on Preview (or any Form render) due to a typo.
=> Fix typo preventing privacyPolicy from displaying on form

components/form-builder/app/navigation/PreviewNavigation.tsx, pages/form-builder/preview/[[...params]].tsx, pages/form-builder/preview/test-data-delivery.tsx
The menu is only needed when logged in and you have Preview/Test options. When not logged in, there is no Test option, so don't show the menu.
=> Only show Preview menu when logged in

components/form-builder/app/shared/ResumeEditingForm.tsx, components/form-builder/app/shared/index.ts, pages/myforms/[[...path]].tsx, public/static/locales/en/my-forms.json, public/static/locales/fr/my-forms.json
Adds a resume form button under my forms "if a form session exists"
partially fixes #1393
☝️
you can now resume editing
>at the end of the process when trying to publish it you will "lose" your form because the sign-in process will redirect you to the /myforms page.
partially fixes #1320
☝️ 
you can now resume editing
https://user-images.githubusercontent.com/62242/205718889-bb76a784-a983-4c52-ae86-46dbfb55e20c.mp4
- Visit form builder
- Start creating a form
- Visit "my forms" (when logged in)
- Note a resume editing form button should now exist
- Resume editing a form --- should take you back to your previous form
=> Add resume form to "My Form"

components/form-builder/app/edit/Edit.tsx, components/form-builder/app/translate/Translate.tsx, components/form-builder/store/useTemplateStore.tsx
closes https://github.com/cds-snc/platform-forms-client/issues/1319
- Quick fix to set the `emailSubject` properties to `__title__ - Response` in order for the current email response design to continue working properly
=> fix: set emailSubject properties to Title - Response

components/form-builder/app/Publish.tsx
- Hide publish button when user does not have permission on page https://forms-staging.cdssandbox.xyz/form-builder/publish. If think it used to work but was probably broken during some refactoring. Also changed the fact that you could see the "Publishing disables editing " warning message even if the form was not in a publishable state. In Figma we either have the warning message with the publish button or none of them.
=> fix: publish button is hidden when permission is not assigned

components/form-builder/app/Settings.tsx, components/form-builder/app/shared/ResumeEditingForm.tsx, components/form-builder/store/index.ts
Update to ensure a form session has data before showing the resume form option.
I noticed this after working on the delete from dialog yesterday - deleted for session still existed for deleted form but the session was cleared when calling form initialize after the deletion.
**Form without data**
1) From the start screen create a new form.  **Don't enter any information**.  Visit my forms ... resume button should not appear.
<hr>
**Form with data**
1)  From the start screen create a new form.  **Enter a form title**.  Visit my forms ... resume button should be available
<hr>
**Form deletion**
1) Create a form and save it.
2) Visit my forms + delete the form via the delete dialog
3) Visit my my form --- no resume session should exist
Please complete the following items in the checklist …
=> Don't show "resume" form when session is empty

components/form-builder/app/edit/elements/lexical-editor/ToolTip.tsx
Fixes a bug where the RichTextEditor Toolbar buttons required a two clicks to activate. This was caused by some improper child element cloning in the Tooltip component.
=> Fix Tooltip bug

__tests__/api/signup/register.test.ts, pages/api/signup/register.ts
This PR adds email domain validation check to the Register API endpoint.  It was previously possible that any email address could register with Cognito by directly calling the Register endpoint.
A request to the Register API endpoint that includes a non valid gov email address should now return a 400 error.
=> Fix / Missing email domain check on register API

lib/tests/users.test.ts, lib/users.ts, pages/api/auth/[...nextauth].ts
No issue 
It was previously possible to create an account with cognito and gsuite that used the same email. Redirect logic has been added such that user's can only sign in with the original way they registered (The way they signed into GC Forms the first time). I.E if one registered with the cognito method and attempted to sign in with a gsuite account with the same email they would be redirected to sign in with the cognito account and vice versa. 
This removes the possibility of an account takeover and as such we can return to using emails to lookup users. This will allow us to use the csv option to migrate users from one cognito user pool to another and have user's still be able to access their accounts after a password reset
1. Test to make sure the login still works 
N/A
Please …
=> fix: switch getOrCreate user function to use email instead of token sub

components/form-builder/app/navigation/Header.tsx
- `My Forms` link is not displayed in Header after user sign in
Thank you @timarney for discovering that bug
=> fix: My Forms link is not displayed in Header after user sign in

pages/form-builder/preview/[[...params]].tsx
This fixes the preview / test page to ensure you can pass a form id
Currently the preview link with an ID lands on a missing page
- Visit My Forms
- Preview an existing form
=> Fix preview page when passing id

.github/workflows/staging-deploy.yml
According to Github logs we have not been able to deploy to staging for the past few days. It happened right after https://github.com/cds-snc/platform-forms-client/pull/1402 was merged.
The error logs are:
````
Run aws-actions/amazon-ecs-deploy-task-definition@67f6f62a733c5de6ba4ba69fc2a2bb8802945a7f
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/aws-actions/amazon-ecs-deploy-task-definition/67f6f62a733c5de6ba4ba69fc2a2bb8802945a7f/dist/index.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:[1](https://github.com/cds-snc/platform-forms-client/actions/runs/3838434406/jobs/6534886553#step:9:1)5)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at …
```
=> fix: attempt to fix "deploy to staging" Github action

components/myforms/MenuDropdown/MenuDropdown.tsx
Removes unnecessary dependencies from Menu Dropdown useEffect
The useEffect listed `refs` as dependencies but React will never see those updates.
See: https://epicreact.dev/why-you-shouldnt-put-refs-in-a-dependency-array/
> useRef is similar to useState except changing the value doesn't trigger a re-render.
> React can't know that the value changed if a change doesn't trigger a render!
Test the Menu Dropdown under my forms
=> Fix dependancy array for menu dropdown

components/form-builder/app/edit/PanelBodyRoot.tsx, components/form-builder/app/edit/elements/ShortAnswer.tsx, cypress/e2e/form-builder-field-with-description.cy.js, pages/form-builder/index.tsx
Fixes bug for missing default description when toggling `En, Fr` with a date, numeric, phone, email selected
See before and after:
https://www.youtube.com/watch?v=Ch8e1tayjK8
- On `develop` add a form element
- Select a date element
- Note the default description shows
- Change edit mode to `FR` note the description is now empty
---
- Swap to this branch 
- Select a date element
- Note the default description shows
- Change edit mode to `FR` note the default description is now in fr
=> Fix example fr description

components/form-builder/app/shared/SaveButton.tsx, components/form-builder/util.ts
When navigating from my form the date is not being read properly.
1). The date really should be read when navigating from "my forms" but given _**we're making a fetch call and the text is in an aria live region it gets picked up by a screen reader.**_ To fix how the text is read the code us updated to use use `-` vs `/`
When navigating "on purpose" to the last saved the aria label with now gets picked up
-----
**Notes:**
- Moved aria-polite out + adds aria-atomic="true" to ensure full text read when an update happen
See:  #1511
=> Last saved date

components/form-builder/app/shared/SaveButton.tsx, components/form-builder/hooks/useTemplateStatus.tsx, lib/templates.ts, lib/tests/templates.test.ts
A previous PR changed the payload of the get single template api route and needed to be updated to include the updated_at property to support the SaveButton.
Save button should work again.
=> Bugfix: Get updated_at into the getTemplate endpoint

components/form-builder/app/Template.tsx, components/form-builder/app/navigation/Header.tsx, components/form-builder/app/navigation/ShareDropdown.tsx, components/form-builder/icons/BackArrowIcon copy.tsx, components/forms/Form/Form.test.js, flag_initialization/default_flag_settings.json, pages/form-builder/edit/[[...params]].tsx, pages/form-builder/edit/translate.tsx, pages/form-builder/preview/[[...params]].tsx, pages/form-builder/publish.tsx, pages/form-builder/settings/[[...params]].tsx, public/static/locales/en/admin-flags.json, public/static/locales/en/form-builder.json, public/static/locales/fr/admin-flags.json, public/static/locales/fr/form-builder.json
Adds initial share drop down behind a feature flag. 
**Noting this menu doesn't match the Figma designs** 
- This PR just gets the files and feature flag in place.
<hr>
As a followup once this in in place we can look at using https://www.radix-ui.com/docs/primitives/components/dropdown-menu for the menu which will allow us to have sub level items.
<hr>
- Turn on feature flag 
- Ensure share menu is only showing on pages where the form would be available to be emailed
=> Add: initial share dropdown + feature flag

pages/api/share.ts
The URL in the share email was missing the https:// prefix.
=> Add scheme prefix to url in share email

.github/workflows/staging-build-push-container.yml
Generate the SBOM before logging out of the ECR.
The latest version of the Docker generate-sbom action now pulls the newly pushed image from the ECR.  This was done to support multi-architecture Docker image scan, but unfortunately broke workflows that logged out of the ECR before the SBOM was generated.
=> fix: generate Docker SBOM step

pages/api/request/support.ts, pages/form-builder/support/[[...supportType]].tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Quick update for some localization strings. Spreadsheet is here:
https://docs.google.com/spreadsheets/d/1_T94VYdANvxV65nw9L4NbflwkWUlp3RCbGPF8ZGxh4g/edit#gid=2014401594
Also updating the Contactus form to use a checkbox. This required a minor change to the API as well.
Navigate to form-builder/support/contactus and try filling out a form and checking the email. For form sake (hah :) test the related form-builder/support/ form also. 
Whatever the user's language is that fills out the form, the selected options are printed out in that language in both the English and French versions in the email. Future bug fix.
=> Updates Contactus localization and to use a checkbox

components/form-builder/app/navigation/LinksSubMenu.tsx
The Share menu "Copy" option was configured to copy the JSON but should just copy the link to the published form.
=> Bugfix: Share menu should copy URL not JSON

components/form-builder/app/navigation/FileName.tsx
- Fixes issue where you couldn't backspace out the entire file name (it would reset to the "old" fileName)
- Fixes issue where the input width was not getting set when reloading when using a longer fileName and or the form title width
1)
- Type in a fileName
- Backspace to remove the fileName --- this should now allow the field to be empty
2)
- Add a really long file name
- Save the form + reload
- The fileName input should have a width that fits the fileName i.e. not cut off (unless it's too long for the screen)
3) 
- Fill in the form title not the fileName 
- The fileName should get filled + take on the width of the file title
=> Fix fileName input bugs

.github/workflows/build-and-deploy-storybooks.yml, .github/workflows/cypress.yml, .github/workflows/jest.yml
The system Node version appears to now default to Node 18.
Since our application is tied to Node 16 at the moment in Docker this PR ensures that Node 16 is used when running tests etc.
=> Force Node 16 in Github Actions

components/globals/Loader.tsx, cypress/e2e/accessibility.cy.js
This should hopefully fix some of failing E2E tests on github.  The A11y test for the Registration page often failed as the test sometimes started while the spinning loader was still displaying.
This new check for the A11y tests ensures that an H1 is in the DOM before starting the A11y check.
=> Cypress: Check for H1 before starting test

components/form-builder/app/shared/ListBox.tsx
Fixes an issue with React keys for the ListBox
- Enable the add element dialog
- Open the dialog
The key warning should be gone.
=> Fix ListBox key issue

components/form-builder/app/translate/DownloadCSV.tsx
The previous update to CSV download included a bug that caused the CSV to just be appended to every time you click Download. This fixes that so it refreshes the data object before generating.
=> Bugfix: Refresh CSV data before building

cypress/support/e2e.js
In debugging Cypress tests I noticed that the default flags were not being applied to all tests.  In the past we  had left it up to the developers to ensure that flags their tests were using were properly intercepted.  However, as the project grows this  pattern is no longer sustainable.
This quick little code change ensures that default flag values are used to intercept all `checkFlag` requests.  The `cy.useFlag` used directly in a test will override these default settings allowing to create tests for features that may be normally off in Production / Staging.
=> Ensure default flags are applied for Cypress tests

package.json, pages/_app.tsx, pages/api/id/[form]/[submission]/download.tsx, yarn.lock
While testing @falila 's latest work on the form responses archiving feature I noticed a bug where it was not always possible to complete a form submission when files were uploaded through one or multiple file input components.
The bug is located in NextJS and described here https://github.com/vercel/next.js/issues/39262 . It was introduced in our codebase with https://github.com/cds-snc/platform-forms-client/pull/1487 and the use of `return NextResponse.next();` .
NextJS version `12.3.4` is the latest minor version for version 12 and it does include the fix we need (https://github.com/vercel/next.js/pull/41270)
=> Bump NextJS version from 12.2.5 to 12.3.4

form-builder-templates/address.json, form-builder-templates/attestation.json, public/static/locales/en/form-builder.json, public/static/locales/en/my-forms.json, public/static/locales/fr/form-builder.json, public/static/locales/fr/my-forms.json
Added in French equivalents for files including `my-forms.json` and `form-builder.json` where they were missing, as well as a few other files.
=====
Notable tweaks in English:
> - Country ≠ city
> - Date of birth ≠ birth day
> - Create an account ≠ sign up
Notable translations in French:
> - Clipboard = Presse-papiers
> - Spreadsheet = Feuille de calcul
> - Street address = Adresse municipale
> - Middle name = Deuxième prénom
> - Legal attestation = Attestation légale
> - City, town, or community = Ville ou communauté
> - Postal or zip code = Code postal ou zip
=> Fill in missing [FR] translations 

components/form-builder/app/ResponseDelivery.tsx, components/form-builder/app/branding/Branding.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Discovered on  branch #1563 fixes missing alt text for logo preview
Also split the text out for (default)
- Check alt text for branding preview logo
=> Branding preview alt text 

components/form-builder/app/SetResponseDelivery.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds vault option hint text with link to `Responses`
- As a logged in user visit setting + vault option
=> Add hint text for vault option

components/form-builder/app/edit/elements/lexical-editor/RichTextEditor.tsx
Fixes: #1786 
Updates dependancies for 
```
const updateValue = useCallback(
```
Simplifies the debounce call and removes the secondary `useCallback` 
The "parent" callback `path` dependancy wasn't being passed updateValue the path index was getting a stale value
see: https://github.com/cds-snc/platform-forms-client/issues/1786#issue-1642558235
=> Fix 1786 - page text

components/form-builder/app/ShareModalUnauthenticated.tsx
The Download File button in the unauthenticated Share Modal was downloading a file called `form.json` whereas the Download File button in Settings gave the file a name based on the form title and the date. This brings the same download action from Settings to Share Modal.
them such as any environmental setup …
=> Use the same DownloadFile button from Settings on Share Modal

components/form-builder/app/Template.tsx, components/form-builder/app/edit/Edit.tsx, components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/Modal.tsx, components/form-builder/app/edit/MoreModal.tsx, components/form-builder/app/edit/PanelBody.tsx, components/form-builder/app/edit/RefsContext.tsx, components/form-builder/app/edit/elements/question/Question.tsx, components/form-builder/app/edit/elements/question/QuestionInput.tsx
- Adds a provider / context  to handle keeping an array of question input refs
- Adds handle re-focus content after using the "more modal"
- Adds handle re-focus after moving items up / down
The allows us to focus question inputs by ID as needed
See issue details https://github.com/cds-snc/platform-forms-client/issues/1804
Fix - https://www.youtube.com/watch?v=nNC3HkXjx6k
Stand-alone demo https://mhtj61-5173.csb.app
https://github.com/timarney/input-refs-demo
- Add 2 elements
- Open the more modal for one of the elements
- Press save
- Focus should be restored to the element 
- Move to the other element --- only on floating menu should appear.
=> Handle input focus refs

components/form-builder/app/Preview.tsx, components/forms/Label/Label.tsx, lib/formBuilder.tsx
Fixes #1731 
Thought this was going to be more difficult, but it turns out we're already passing a language down through Preview/Form to the formBuilder which is responsible for rendering the Label which includes the (required) text. By adding a lang prop to the Label component, we can then pass that into the `t()` function that renders the (required) text.
For the Submit button, we pass that in for Preview, so that was pretty straightforward, along with the "Sign in to test..." text.
=> Use translationLanguagePriority in Form Preview

components/myforms/HTMLDownload/ResponseSection.tsx
The html file downloads were not showing the table headers in French. The problem was a minor typo sending the language in the wrong case (le sigh...)
Go to the responses page, download a submission and double check the French section table column headers are in French.
This would be fun to refactor entirely but that can be fore another day
=> Missing strings in Response HTML

components/myforms/HTMLDownload/ProtectedWarning.tsx, components/myforms/HTMLDownload/index.tsx, pages/api/id/[form]/[submission]/download.tsx, public/static/locales/en/my-forms.json, public/static/locales/fr/my-forms.json
closes https://github.com/cds-snc/platform-forms-client/issues/1934
- Fixed issue where data classification was not properly set in the HTML response. It was static but now relies on the `SecurityAttribute` retrieved from the database.
=> fix: data classification in HTML response does not match form settings

styles/_forms.scss
closes https://github.com/cds-snc/platform-forms-client/issues/1933
- Removed space in bulleted list for Markdown renderer content
=> fix: removed space in bulleted list for Markdown rendered pages

public/static/content/en/terms-of-use.md, public/static/content/fr/terms-of-use.md
Clients need to confirm receipt within 45 days.
=> Terms of Use - precise number of days

lib/clientHelpers.ts, lib/formBuilder.tsx, lib/logger.ts, lib/tests/logger.test.ts
- Removed `logger` function. It was something we included in our Tech Debt document a while ago.
=> feat: removed logger function

components/form-builder/app/edit/ModalForm.tsx, components/form-builder/app/edit/MoreModal.tsx, components/form-builder/app/shared/TextArea.tsx, components/form-builder/store/useModalStore.tsx, cypress/e2e/form-builder/form-builder-modal-description.cy.js
Fixes: #2017
With the move to use the layout array (https://github.com/cds-snc/platform-forms-client/pull/1956) for element ordering a bug was introduced with the More modal which was based on element indexes.
This PR updates the code to use item.id for the More modal.
- Add a multiple form elements
- Use the `more` modal to add descriptions 
- Move the elements `up` or `down`
- Ensure the item descriptions match the element
=> Update More Modal to use item ids

CHANGELOG.md, pages/form-builder/index.tsx, pages/form-builder/responses/[[...params]].tsx
closes https://github.com/cds-snc/platform-forms-client/issues/2023
- Fixed issue where the responses page was still accessible even if the form was marked as deleted. It led to download of responses failing because of the logic behind that requires a form template to succeed.
- Create a form
- Delete that new form
- Try to access the responses page for that form you just deleted `http://localhost:3000/form-builder/responses/<formId>`. It should redirect you to a 404 page.
=> fix: responses page redirect to 404 page if form does not exist (deleted)

components/globals/LanguageToggle.tsx
Updates the Language toggle to use pathname vs asPath which was causing some serialization issues.
Fixes #2048
Fixes #https://github.com/cds-snc/platform-forms-client/issues/2032
See https://github.com/cds-snc/platform-forms-client/issues/2048
=> Use pathname for language toggle

CHANGELOG.md, __tests__/api/id/form/submission/download.test.ts, package.json, pages/api/id/[form]/[submission]/download.tsx, yarn.lock
closes https://github.com/cds-snc/platform-forms-client/issues/2052
- Fixed issue where the download API would override the `Status` of a response from `Confirmed` to `Downloaded`. Now it can only update it if it is a `New` response.
- Re enable `Renders a HTML file` unit test. It was only missing a mock for the `renderToStaticNodeStream` function
- Added `aws-sdk-client-mock-jest` package for new download API unit tests
- Upgraded `aws-sdk-client-mock` to version 2.1.1
- Get yourself in a state where a new response is available for download
- Download the response (status should be updated to Downloaded)
- Confirm the response (status should be update to Confirmed)
- Download the response once again (status SHOULD NOT be updated to Downloaded)
Please complete the following items in the …
=> fix: download API can only change status for new responses

.github/workflows/cypress.yml
A single workflow was building and saving 2 different caches for yarn installations.
We now tell Cypress action that the caches have already been restored.
=> Update cypress.yml to use same cache as other workflows

.github/workflows/cache-cleanup.yml
Ensures that yarn caches created by different branches are removed once the Pull Request has been merged.
Reference: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
=> Cache cleanup action

CHANGELOG.md, lib/tests/validation.test.js, lib/validation.tsx, pages/auth/resetpassword.tsx, pages/signup/register.tsx
closes https://github.com/cds-snc/platform-forms-client/issues/2095
- Allow more symbols to be used in passwords. (Set of special characters that is now being used can be found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html))
- The added unit test will take care of testing that change. 
- If you really want to test something, just create an account with a password that did not work ([see related issue](https://github.com/cds-snc/platform-forms-client/issues/2095)). Make sure you comment out line 122 in `register.tsx`
=> feat: allow more symbols to be used in passwords

components/form-builder/__tests__/useTemplateStore.test.tsx, components/form-builder/app/edit/Edit.tsx, components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/ElementRequired.tsx, components/form-builder/app/edit/PanelBody.tsx, components/form-builder/app/edit/PanelBodyRoot.tsx, components/form-builder/app/edit/PanelBodySub.tsx, components/form-builder/app/edit/elements/Options.tsx, components/form-builder/app/edit/elements/question/Question.tsx, components/form-builder/app/edit/elements/question/QuestionInput.tsx, components/form-builder/app/edit/elements/sub-elements/SubElement.tsx, components/form-builder/app/edit/elements/tests/Question.test.js, components/form-builder/store/useModalStore.tsx, components/form-builder/store/useTemplateStore.tsx
Per issue #2092 element updates we're happening to the wrong elements after moving elements up / down etc...
This PR makes use of the `propertyPath` helper which takes an `id` to look up the element path vs relying on the index which started breaking when we moved to use the layout array for element ordering.
Fixes: #2092
See "steps to re-create" https://github.com/cds-snc/platform-forms-client/issues/2092
Also:
- Insert at least 3 elements. Be sure 2 of these elements contain "choices" i.e. Radio, Checkboxes, Dropdown
- Enter text into the elements
- Move the items up / down etc...
- Update the text in each --- ensure the text updated is for the correct element
- Test duplicating items
=> Fix - #2092

lib/hooks/auth/useConfirm.ts, lib/hooks/auth/useLogin.ts, lib/hooks/auth/useRegister.ts, lib/hooks/auth/useResetPassword.ts
Follow-up to https://github.com/cds-snc/platform-forms-client/pull/2117 to use re-factor to use hasError
This cuts down on the repeated code to parse Axios error messages
```javascript
const e = err as AxiosError;
const message = e.response?.data?.message;
```
and makes the `includes` lookup easier but adding the ability to pass strings as an array vs multiple str `includes` 
- signup / register flow
=> use hasError

pages/api/auth/2fa/request-new-verification-code.ts
- Added very basic API path to request new 2FA verification code. 
API path = `/api/auth/2fa/request-new-verification-code`
Request method = `POST`
Request body = `email: <user_email>`
Requires CSFR token
=> feat: added new API to request new 2FA verification code

lib/auth/cognito.ts, pages/api/auth/2fa/request-new-verification-code.ts, pages/api/auth/[...nextauth].ts, pages/auth/test_2fa.tsx, prisma/migrations/20230523174152_add_cognito_custom_2fa/migration.sql, prisma/schema.prisma
- Introducing authentication flow token as an extra layer of security to our authentication APIs (especially the one that can request a new 2FA verification token)
=> feat: introducing authentication flow token

components/globals/ErrorPanel.tsx
Updates the error pages (ErrorPannel) home link depending on auth status. 
If the user is authenticated then the home link should be to the form builder, otherwise the link should be to the public forms site.
=> Fixes ErrorPannel home link depending on auth status

lib/auth/2fa.ts, lib/auth/2faLockout.ts, lib/auth/cognito.ts, lib/tests/auth/2fa.test.ts, lib/tests/auth/2faLockout.test.ts, lib/tests/auth/cognito.test.ts
- Reduced number of allowed attempts from 10 to 3 for 2FA validation mechanism
- Added unit tests for new 2FA code
=> Added unit tests for new 2FA code

lib/auth/cognito.ts, lib/tests/auth/cognito.test.ts
- New verification code is being generated and saved when calling `begin2FAAuthentication` even if a code already exists.
=> feat: renew 2FA verification code when beginning 2FA auth session even if one already exists

components/auth/Confirmation/Confirmation.tsx, lib/hooks/auth/useConfirm.ts
Updates use confirm to accept props coming from login vs creating new refs.
Fixes #2196
- To test you'll need an account that `hasn't been confirmed` yet + a local connection to staging for the user pool
- Using an account that hasn't been confirmed try to login 
- Once you receive the email verification code ... enter it 
- You should now be signed in 
=> useConfirm bug issue #2196

components/form-builder/app/shared/DownloadFileButton.tsx, components/forms/Form/Form.tsx
Form titles are used for tracking success in google analytics
There's no other way to easily see this within the application, so putting it back as one of our data points in google analytics
=> Put back formTitle for Google Analytics and GTM

CHANGELOG.md, __tests__/api/notify-callbacks.test.js, pages/api/notify-callback.ts
Our GC Notify callback API cannot differentiate between all the types of emails we are sending (form submission, account confirmation, share a form, etc...) with our GC Notify account.
The form submission email does have a reference (submission ID we are manually passing when sending a form submission) that can be sent back to us through the callback while the other emails do not have any (`null`) because it would be irrelevant.
=> fix: GC Notify callback API should only handle form submission type of email

CHANGELOG.md, components/form-builder/app/Preview.tsx, components/forms/Form/Form.tsx
- ReCaptcha will not load in form builder preview mode. 
@anikbrazeau found that the submit button of the form builder preview tab was not working anymore. We broke it when we enabled (recently) Google ReCaptcha in Staging (it is not enabled in Production). This is due to the preview feature not passing the ReCaptcha secret key (the frond end does not have access to that information) to the form component. I decided to take advantage of the `isPreview` parameter to decide whether we should load ReCaptcha or not.
- Make sure you have enabled ReCaptcha in the Feature flags
- Create a form and try to submit a response through the Preview tab
=> fix: do not load recaptcha in form builder preview mode

.github/workflows/pr-review-sync-env-vars.yml
Now that the PR review sync has been tested, the manual `workflow_dispatch` trigger is no longer needed.
- cds-snc/platform-core-services#385
=> chore: remove workflow trigger

.github/workflows/pr-review-client-delete-unused.yml, .github/workflows/pr-review-client-deploy.yml, .github/workflows/pr-review-client-remove.yml, Dockerfile.pr
Update the PR review env workflow to remove all AWS cli output.
Also updates the `Dockerfile.pr` to pull the AWS web adapter Docker image from the CDS public ECR to avoid rate limiting issues.
- Closes cds-snc/platform-core-services#387
=> fix: remove AWS cli output for PR review envs

components/auth/LoginMenu.tsx, pages/api/auth/[...nextauth].ts
To save ourselves from having to add all PR Review environment URLs to Cognito as allowed Callback URLs dynamically, we just use the Staging URL for the NEXTAUTH_URL in the Review environments. 
For the most part, this doesn't affect anything visibly until you try to Logout, when NextAuth will redirect you using the NEXTAUTH_URL from the environment as the baseUrl, which would be the Staging URL.
This PR modifies the NextAuth `redirects` callback to return a relative path without baseUrl, so it will work in any environment.
=> fix: manually handle logout redirect for PR Review environments

.github/workflows/release_generator.yml
Updates the token used on the Release Generator action to personal token so that CI tests and other actions downstream can run.  
See https://github.com/google-github-actions/release-please-action#github-credentials for details
=> ci: Update token on release generator

prisma/seeds/seed.ts, utils/cognitoMigration/convertEmailAddressToLowercase.ts
- Prisma/Cognito migration code will not handle failures gracefully
For Prisma:
```
Running 'lowercaseEmailAddress' migration
Failed to migrate user email address Clement.janin@cds-snc.ca because of following error:
Invalid `.update()` invocation in
/Users/clementjanin/github/platform-forms-client/prisma/seeds/seed.ts:197:10
194 .filter((user) => /[A-Z]/.test(user.email))
195 .map((user) => {
196   return prisma.user
→ 197     .update(
Unique constraint failed on the fields: (`email`)
Converted email address clement.janin+tesT1@cds-snc.ca to clement.janin+test1@cds-snc.ca.
2 users required migration to lowercase email address but some may have failed (see logs above)
```
For Cognito:
```
Users requiring email address update:
[
{
username: '0f9845d2-4541-463e-bb9e-58eea964533b',
email: …
```
=> refactor: improve Prisma/Cognito user email migration code to handle failures gracefully

.github/workflows/prod-build-push-container.yml
Add back the GitHub SHA variable that is used in the docker image arg.
Future check to possibly remove the argument from docker files.
=> ci: add back github sha for docker image arg

components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/DownloadTableReducer.ts, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json, styles/_forms.scss
This work adds the Client side logic to restrict a download. A submission download is restricted if the user account is in a "escalated" state and the submission marked as new.
IMPORTANT: because a placeholder value is use for "escalated" and set to true, the Download table will always show a warning and block any new downloads.
At this point I think the only thing that can be tested is whether non-new submissions are not blocked in the Client.
The warning text may need to be updated and eventually the French translation added.
This work relies on a placeholder value for the account "escalated" state. This will need to be done.
The download API should also use the account "escalated" state to block a submission download at the API level. This can be down once the variable is created (or …
=> Adds initial work for restricting downloads

.eslint-tailwindcss.js, components/form-builder/icons/ManageAccountsIcon.tsx, components/form-builder/icons/SettingsApplicationsIcon.tsx, components/form-builder/icons/index.ts, components/globals/layouts/AdminNavLayout.tsx, pages/admin/index.tsx, public/static/locales/en/admin-home.json, public/static/locales/fr/admin-home.json
Adds an Admin landing screen per https://github.com/cds-snc/platform-forms-client/issues/2343
Previously, was directing to Accounts.
This introduces a landing screen with grouped links to admin sections
Login as administrator, see new landing screen
=> [deactivate] Admin home screen

components/form-builder/app/navigation/FileName.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds a hidden label for the form name on the Settings screen. 
Go to the settings screen. Start VoiceOver and tab to the Form name input. The content in the input should be announced along with the label "Form name".
=> Fixes minor a11y issue with a missing label

components/globals/Buttons/LinkButton.tsx, components/globals/StyledLink/StyledLink.tsx, lib/localStorage.ts, lib/sessionStorage.ts, pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/[id]/manage-permissions.tsx, pages/admin/accounts/index.tsx
Fixes : https://github.com/cds-snc/platform-forms-client/issues/2379
Before and After video:
https://www.youtube.com/watch?v=H8mv5cRa8j4
Updates account page to pull a user id if stored in local storage to auto-scroll back to that card.
- when navigating from accounts to manage forms (back to accounts)
- when navigating from accounts to permissions (back to accounts)
- When deactivating 
- When locking / unlocking publishing 
Per above actions navigate / take actions to ensure scroll is working as expected.
=> Account screen - scroll to user

.vscode/launch.json, README.md, package.json
Updates VSCode launch.json with new debug configurations that function with the latest version of NextJS.
Do not start the application in a separate terminal.  The debug configuration will launch all processes required.
- Launches the application with yarn dev.  Can debug both pages and app router backends
- Launches the application with yarn dev:test.  Can debug server side code in APP_ENV=test mode.
- Launches chrome browser for client side debugging
- Launches both server-side (yarn dev) and client-side debugging.
=> chore: update debug config

components/form-builder/app/Template.tsx, components/globals/layouts/AdminNavLayout.tsx, cypress/cypress.d.ts, cypress/e2e/accounts_page.cy.ts, cypress/e2e/form-builder/admin-menu.cy.ts, cypress/e2e/form-builder/ownership.cy.ts, cypress/support/commands/commands.ts, cypress/support/e2e.ts, lib/auditLogs.ts, lib/auth/2fa.ts, lib/auth/auth.ts, lib/cache/userActiveStatus.ts, lib/hooks/useAccessControl.tsx, lib/integration/prismaConnector.ts, lib/middleware/sessionExists.ts, lib/tests/auth.test.ts, lib/tests/sessionExists.test.js, lib/users.ts, next-env.d.ts, pages/api/auth/[...nextauth].ts, prisma/seeds/fixtures/users.ts, prisma/seeds/seed.ts, tsconfig.json, types/next_auth/index.d.ts
Implements immediate deactivation of a user by logging them out and redirecting them to the account deactivated page.
Closes #2347 
- Modifies the Next Auth JWT token and Session processing to add a 'deactivated' property to the Token and Session objects.
- Cache implemented to store the active status of a user to reduce calls to the database.
- `useAccessControl()` hook modified to check for user active status and if the user is deactivated to automatically sign the user out and redirect to `account-deactivated` page.
- `useSession` middleware that protects API endpoints updated to refuse access to deactivated accounts.
- `requireAuthentication` Page wrapper updated to redirect users to `account-deactivated` page when called Server Side
- Page layouts `Template.tsx` and …
=> feat:  Immediate deactivation / logout

__tests__/api/id/form/submission/download.test.ts, lib/auditLogs.ts, lib/vault.ts, pages/api/id/[form]/[submission]/download.tsx, pages/api/id/[form]/submission/confirm.ts, pages/api/id/[form]/submission/report.ts
Some audit logs were being generated that had identical keys which were causing errors.
For general Response logs (for example get all responses for a form) the logs have been changed to instead reference the form ID.  Response subject and ID's are instead reserved for when dealing with a single response.
Difficult to test...
=> fix: update audit logs to be more unique

lib/templates.ts, lib/tests/vault.test.ts, lib/types/retrieval-types.ts, lib/utils.ts, lib/vault.ts, pages/form-builder/settings/[formId]/form.tsx
Tweaks to enhance performance and fix a few issues
- Simplify the call to get the entries related to the form ID in the vault.
- Ensure that if DynamoDB needs to paginate due to a large number of responses the code can handle the use case
- Build a promise array of the batched delete request and allow them to begin while continuing to generate the promise array.
- Fix privileges and ability in tests where the privileges were modified instead of the user ID.
- Modify util `chunkArray` to use a generic type so that it is easier for other functions to leverage it.
- Create a draft form
- Send multiple form responses
- Check responses page that responses are available
- Publish form
- Check responses page that responses are gone
Please complete the following items in the checklist before you …
=> chore: refactor delete responses on publish

lib/auth/auth.ts, lib/cache/securityQuestionsStatus.ts, next-env.d.ts, pages/api/auth/[...nextauth].ts, pages/auth/setup-security-questions.tsx, pages/form-builder/index.tsx, pages/form-builder/responses/[[...params]].tsx, pages/form-builder/settings/branding-request.tsx, pages/form-builder/settings/branding.tsx, types/next_auth/index.d.ts
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2428
- Adds check to see if user has security questions setup and if not re-direct them to the setup page (temp page)
Will add tests in future PR just getting code in place to help unblock other PRs
Noting - check defaults to `true` as we need to do a real check still.
Update hardcoded value to equal `false` in [...nextauth].ts
which should in turn setup the redirect
```javascript
// @todo add real check here once security questions are implemented
const hasSecurityQuestions = true;
```
=> Add security questions check

components/admin/Profile/EditSecurityQuestionModal.tsx, pages/auth/setup-security-questions.tsx, public/static/locales/en/profile.json, public/static/locales/fr/profile.json
Adds an "unknown error" to the profile dialog. 
Also adds the start of a "loader" for the create security questions page. I was noticing a small delay, even locally, when submitting the form. Currently this just disables the submit button as an indicator when submitting.
Consider a "submitting" (previously called "loading") pattern for all/most of our forms.
=> Adds unknown error to profile dialog plus loader

lib/auth/passwordReset.ts, lib/auth/securityQuestions.ts, lib/hooks/auth/useResetPassword.ts, pages/api/auth/[...nextauth].ts, pages/auth/reset-failed.tsx, pages/auth/resetpassword.tsx, public/static/locales/en/reset-password.json, public/static/locales/fr/reset-password.json
Fixes #2502
Adds redirect to reset failed for 2 scenarios
1) via a reset magic link (this should never happen as the link shouldn't be generated) 
2) resetting with no security questions (added a check before sending the link)
- Test reset password without setting up security questions first
=> Add redirect if missing security questions

flag_initialization/default_flag_settings.json, pages/auth/login.tsx, pages/auth/resetpassword.tsx, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
Fixes https://github.com/cds-snc/platform-forms-client/issues/2508
Removes the feature flag to enable password reset form / link to show
- Visit sign-in
- Reset link should be available by default now
- Visit + test reset password link
<hr>
- Visit admin + ensure the flag doesn't show
=> chore: Remove password reset feature flag

prisma/migrations/20230811140652_make_security_questions_unique/migration.sql, prisma/schema.prisma
- Adds uniqueness to security questions in Prisma schema to avoid duplication when starting the application.
- Delete all existing security questions (`SecurityQuestion`) and security answers (`SecurityAnswer`) from your database
- Run multiple `yarn prisma:deploy`
- Check the `SecurityQuestion` database table. There should not be any duplicate.
=> fix: make security questions unique in database schema

pages/auth/resetpassword.tsx, pages/auth/setup-security-questions.tsx, public/static/locales/en/reset-password.json, public/static/locales/en/setup-security-questions.json, public/static/locales/fr/reset-password.json, public/static/locales/fr/setup-security-questions.json
fixes: #2515
Updates support link + text on security questions page
- Test support "Get support" link form security questions password reset flow
=> chore: Add Get Support link to Answer Security Questions

components/form-builder/app/LoggedOutTab.tsx
Prior to this PR the settings page flashes the logged out screen prior to showing the correct page state.
This PR makes an update check the status of use session before showing content.
https://github.com/cds-snc/platform-forms-client/assets/62242/f6b7b241-055e-42ea-bca7-e2bfe2dba064
☝️ 
Current - we see a flash of the logged out screen
- Throttle your network connection
- Note when logged in you should no longer see the logged out screen content.
=> chore: check session loading state on settings page

components/form-builder/getPath.test.ts, components/form-builder/getPath.ts
The Root ID parsing code in the path helper breaks on forms with more than 99 elements. We currently do not support sub elements, so this parsing code is not needed at the moment, but is causing problems for large forms. Removing for now, to be revisited when we introduce sub element support.
this issue that could be addressed in the future? If so please …
=> bugfix: Remove sub element parsing as it causes problems with long forms

components/myforms/Card/Card.tsx
Stops long emails in a myforms card from breaking the design.
| ![Screenshot 2023-09-13 at 9 01 02 AM](https://github.com/cds-snc/platform-forms-client/assets/107579368/a74be756-4fc3-4b20-a260-3b2a6b668bca) | ![Screenshot 2023-09-13 at 9 00 12 AM](https://github.com/cds-snc/platform-forms-client/assets/107579368/82d3a174-3638-4a13-aa36-dbb096e36513) |
Create a form and configure to have a long email and set the publishing option to email. Go back to the myforms screen and find the related card. The email line should be truncated
=> Fixes myforms card email overflow problem

.github/workflows/prod-deploy.yml, .github/workflows/staging-deploy.yml
Add a GitHub workflow to automatically update the production ECS task when a new release is published.  This workflow will wait for the production Docker image build/push before starting.
Additionally, this reports the Staging and Production deployments to Sentinel to help with the capture of [DORA metrics](https://www.leanix.net/en/wiki/vsm/dora-metrics). 
1. Merge a non-release PR and confirm that the ECS task deployment still works as expected.
1. Merge a release PR.
2. Once the Production Docker image build and push workflow finishes, the Production deploy workflow should start.
3. Validate the rendered appsec and task definitions templates in the `forms-production-vault-file-storage` S3 buckets.
Once we've confirmed that the templates are correct, a subsequent PR will enable the …
=> chore: Add automated production ECS task deploy

.github/workflows/delete-ecs-task-defs.yml, bin/delete-ecs-task-defs.sh
Add a workflow that deletes old ECS task definitions from Staging.  The workflow is configured to delete all but the 5 most recent task definitions.
Once the workflow has been tested, it will be configured to run on a nightly schedule and Production task definitions steps will be added.
This workflow uses an OIDC role to retrieve temporary credentials rather than using a hard-coded AWS access key/secret.
1. Once merged, manually run the workflow.
2. Expect that it will delete all ECS tasks in Staging except for the 5 most recent.
- https://github.com/cds-snc/platform-core-services/issues/441
=> chore: add ECS task definition delete workflow

.github/workflows/delete-ecs-task-defs.yml, .github/workflows/prod-deploy.yml
Update the ECS task definition to run once a week on Sunday.  Also include the Production ECS task deletion in the workflow and reverts to using AWS access keys.
Additionally, this fixes the Production deployment script to use the correct access keys.
- https://github.com/cds-snc/platform-core-services/issues/441
=> chore: enable ECS task definition delete

.github/workflows/delete-ecs-task-defs.yml
Update the ECS task definition delete workflow to use OIDC roles now that the claim policy has been updated with the correct default branch.
Manually run the workflow and expect that it deletes the old ECS task definitions successfully in the Staging and Production accounts.
- https://github.com/cds-snc/platform-core-services/issues/441
- https://github.com/cds-snc/aft-global-customizations/pull/42
- https://github.com/cds-snc/aft-account-request/pull/134
=> chore: use OIDC roles for ECS task def delete

components/form-builder/hooks/useElementOptions.tsx
Adds missing translation key for Address in the form-builder.
Try setting the language to French. Then in the form-builder menu dialog, the Address block label should be in French (Addresse)
=> Fixes missing translation key

.github/workflows/release_generator.yml
Update the Release Generator workflow to use an SRE read/write GitHub app temporary token for authentication.
Merge this PR and expect that Release Generator workflow runs without error.
- cds-snc/platform-core-services#441
- https://github.com/cds-snc/forms-terraform/pull/491
- https://github.com/cds-snc/forms-terraform/pull/495
=> chore: use SRE app token for Release Generator

.github/workflows/prod-deploy.yml, .github/workflows/staging-deploy.yml
Update the Production deploy workflow to perform the ECS task update and deploy.
Update the Staging deploy workflow to use OIDC roles for AWS authentication so it is consistent with the Production deploy workflow.
The ECS task definition and app spec template generated from [yesterday's `v3.4.5` release](https://github.com/cds-snc/platform-forms-client/actions/runs/6240260581) was compared to the ECS task definition and app spec template used to deploy in the AWS console.
The only major difference was that the v3.4.5 release template used the expected Docker image tag.  The `diff` of the files is shown below.
```diff
❯ diff form-viewer-task-def-github.json form-viewer-task-def-aws.json
6c6
<       "image": "957818836222.dkr.ecr.ca-central-1.amazonaws.com/form_viewer_production:v3.4.5", …
```
=> chore: enable automated Production ECS deploy

.github/workflows/delete-ecs-task-defs.yml, bin/delete-ecs-task-defs.sh
Update the ECS task definition delete workflow to set `ACTIVE` tasks to `INACTIVE` and then to keep the 100 most recent `INACTIVE` task definitions.
This is being done because of how Terraform plan operations will fail if the Terraform state references an ECS task definition that no longer exists.  With this approach, the Terraform plan no longer fails.
Additionally, the Production ECS task delete is being temporarily removed until testing in Staging is complete.
Once the PR merges, manually invoke the workflow and expect it to:
- Keep the 5 most recent `ACTIVE` ECS task definitions.
- Set the remaining ECS tasks to `INACTIVE`.
- cds-snc/platform-core-services#441
- https://github.com/cds-snc/platform-core-services/issues/464
=> fix: update ECS task def delete to set inactive

.github/workflows/delete-ecs-task-defs.yml, bin/delete-ecs-task-defs.sh
Update the ECS task delete workflow to include production. Also fixes a minor spacing issue in the script output.
Manually invoke the workflow once the PR merges and expect it to run against both Production and Staging accounts.
- Closes cds-snc/platform-core-services#464
=> chore: Enable Prod ECS task delete

.github/CODEOWNERS
Add a CODEOWNERS file that will be used with branch protection rules to ensure release PRs are only approved by one of the listed users.
Once this has merged and the `develop` branch protection rules are updated, confirm that only one of the listed users is allowed to approve a release PR.
- https://github.com/cds-snc/platform-core-services/issues/466
=> chore: Add release manifest code owners

styles/_form-builder.scss
Fixes: #2685
The `solid` prop for border was removed accidentally here https://github.com/cds-snc/platform-forms-client/pull/2654/files#diff-c66e3b7d15ceac3c4686d473ec1eb9c5174ee1ffc8a86d00ddf81975c38df32fR84
This PR brings it back.
| <img width="689" alt="Screenshot 2023-09-22 at 9 50 27 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/ed290cf5-9c0c-491d-9dcf-0e7164809a53"> | <img width="778" alt="Screenshot 2023-09-25 at 9 17 02 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/92fceb4f-a082-4cd1-a9c8-de9222fcdf93"> |
Radio options on the Settings …
=> fix: radio button on settings page

public/static/locales/fr/form-builder.json
Word "le" shows up twice on FR Support form
=> chore: Fix support form duplicate word

components/form-builder/app/navigation/SubNavLink.tsx, components/myforms/FilterNav/FilterNavigation.tsx, pages/forms/[[...path]].tsx
Updates "forms" subnav to default highlight "all" as the selected sub nav item
**Before** 
The "all" sub nav highlighting happens "late" 
We know all will be highlighted so we can safely default to that item. 
- Visit `/forms` note the sub nav highlights properly 
- Also visit the form builder as the Sub nav is also used there --- no updates but ensure it's working as current
Noting -- for accounts with Manage All Forms / a large amount of cards we're still seeing a small "blip" but this PR updates will cover most use cases.
=> refactor: default forms to "all" 

pages/_document.tsx
part of the work related to https://github.com/cds-snc/platform-forms-client/issues/2741
- Added an HTML instruction for search engines not to index our website when not running in production (aka make Staging disappear from search results)
=> feat: add noindex, nofollow instructions for search engine robots

pages/_document.tsx
- Attempting to fix `noindex` meta tag not being included on root index page
=> fix: add noindex meta tag in Staging on all pages including root index

styles/_forms.scss, styles/_typography.scss
H4 had some odd default styling.
This PR removes that and adds a bit of padding to it for better H4s.
=> chore: Remove section-header default styling on h4 and add margin

pages/_document.tsx, public/BingSiteAuth.xml, public/googlef34bd8c094c26cb0.html
- Replaced `google-site-verification` meta tag with a public file used to identify our https://forms-staging.cdssandbox.xyz/ URL in Google Inspection Tool. A file is unique and tied to a specific URL address.
- Also added a file for Bing as they both use the same verification method
PS: I was able to test the verification process with the PR environment URL and it worked fine. Bing was also able to see the meta tag but Google could not so after multiple tests I decided to go with the file method.
=> chore: add verification files instead of meta tags for Google and Bing search engines inspection tools

pages/_document.tsx, public/BingSiteAuth.xml
- The BingSiteAuth.xml file is blocked by our AWS firewall because it contains uppercase letters which cannot pass the AllowOnlyAppUrls rule unless we remove the instruction to lowercase the inspected URI. Since the meta tag works with Bing I decided to use that method to verify ownership of our staging website.
=> chore: added Bing ownership verification meta tag for staging env

components/form-builder/__tests__/useAllowPublish.test.tsx, components/form-builder/app/edit/MoreModal.tsx, components/form-builder/app/shared/SaveButton.tsx, components/form-builder/hooks/useAllowPublish.tsx, cypress/e2e/form-builder/autocomplete.cy.ts
This update removes `isSaveable` check from save button.
Based on feedback there has been confusion around the save button not showing.
This PR removes the check for a title and question.  
- As a logged in user 
- Edit a form 
- Save button should be available right away.
=> chore: Remove isSaveable check

prisma/seeds/fixtures/settings.ts
Adds a setting to configure the responseDownloadLimit.
This affects the Responses screen and limits the number of responses you can download at once.
Adding this setting to be merged to develop so that we can experiment with it on #2831 
(currently PR review environments can't make db changes)
=> Add a configurable responseDownloadLimit Setting

components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/icons/CheckAllIcon.tsx, components/form-builder/icons/CheckIndeterminateIcon.tsx, components/form-builder/icons/index.ts, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Adds an icon to the header of DownloadTable to enable selecting all visible records.
Icon toggles between 3 states:
- All selected
- None selected
- Indeterminate (some selected)
=> Add "Select all" header icon to DownloadTable

components/form-builder/app/responses/DownloadButton.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx, pages/form-builder/responses/[[...params]].tsx
Refactors the Download button and handler on the Responses page to its own component. There is no functional change here, just the button and handler have been moved out.
This is in preparation for future development where the download button will launch a Modal to handle the multiple download formats.
=> Refactor Responses Download button to component

components/form-builder/app/responses/CheckAll.tsx, components/form-builder/app/shared/Tooltip.tsx
Adds a Tooltip to the CheckAll component.
Simplifies a type on the CheckAll component by using an existing one.
Adds "side" prop to Tooltip component
=> CheckAll Tooltip and small refactor

pages/form-builder/support/[[...supportType]].tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
closes: #2735 
It removes the option to request a demo from the contact us page.
| ![Screenshot 2023-11-16 at 11 13 32 AM](https://github.com/cds-snc/platform-forms-client/assets/25329319/28086fcd-cf54-4982-aea8-9fd465649092) | ![Screenshot 2023-11-16 at 11 20 02 AM](https://github.com/cds-snc/platform-forms-client/assets/25329319/619af085-78ac-44c3-a3f8-5e988edf187d) |
Visit the contact us page at `{host}/form-builder/support/contactus`
The request a demo option should no longer be visible.
=> chore: Remove demo request from contact us form

components/form-builder/app/responses/ActionsPanel.tsx, components/form-builder/app/responses/BottomActionsPanel.tsx, components/form-builder/app/responses/DownloadButton.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/DownloadTableReducer.ts, pages/form-builder/responses/[[...params]].tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Adds the Download/Confirm panel to the bottom of the Responses screen and adds a RESET action to the Reducer to handle when switching Status filter.
This PR just adds the panel and uses the existing Download/Delete buttons and actions.
=> Add Download/Confirm panel to Responses

components/form-builder/app/responses/Dialogs/ConfirmDialog.tsx, components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/tests/DownloadTable.cy.tsx, pages/form-builder/responses/[[...params]].tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Restores the Confirm dialog and button to the Downloaded Responses page and updates the content of the dialog. Also uses responseDownloadLimit for the maximum number of codes to input. This may need its own setting eventually.
=> Add confirm button and dialog to the Downloaded Responses page

components/form-builder/app/responses/MoreMenu.tsx, components/form-builder/app/responses/tests/DownloadTable.cy.tsx
Hides the inline Delete option on the More menu on the Confirmed Responses screen.
| <img width="1359" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/ae41475a-91b8-4e23-b57c-e0cdef3e9192"> | <img width="1388" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/9ab3261c-64ff-4980-9510-563ee62ac02d"> |
=> Hide delete on confirmed

components/form-builder/app/responses/ActionsPanel.tsx, components/form-builder/app/responses/DeleteButton.tsx, components/form-builder/app/responses/Dialogs/ConfirmDeleteNewDialog.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Adds the Confirm delete new responses dialog.
Does not delete responses, only placeholder.
=> Confirm delete new responses dialog

pages/api/id/[form]/submission/download.ts
- Responses should only be marked Downloaded when downloading "official records" (html, html-aggregated, html-zipped).
- All downloads should be logged with format indicated
=> Only mark downloaded for official records

lib/tests/vault.test.ts, lib/vault.ts, pages/form-builder/responses/[[...params]].tsx
The responseDownloadLimit setting was added to limit the number of concurrent HTML file downloads. 
This PR applies that same limit to listAllSubmissions (the max number of submissions that can be displayed)
=> Use responseDownloadLimit setting for listAllSubmissions query

components/form-builder/app/responses/DownloadTable.tsx, pages/form-builder/responses/[[...params]].tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Responses screen updates:
- Move title below nav
- New titles (hidden on zero results)
- New Confirm delete (Sign off) message and button
=> Add "sign off" message, new titles, and confirm dialog button

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, components/form-builder/app/responses/DownloadTable.tsx, lib/responseDownloadFormats/html-zipped/index.ts, pages/form-builder/responses/[[...params]].tsx
Adds a prefix to downloaded file names.
`[form-name-slug]-[yyyy-mm-dd]-responses-reponses.zip`
`[form-name-slug]-[yyyy-mm-dd]-responses-reponses.csv`
`[form-name-slug]-[yyyy-mm-dd]-responses-reponses.json`
`[form-name-slug]-[yyyy-mm-dd]-receipt-recu.html`
Note only the downloaded files get the prefix. Files inside .zip files are named:
`receipt-recu.html`
`responses-reponses.json`
`responses-reponses.csv`
=> Prefix downloaded file names

components/form-builder/app/responses/DownloadTable.tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
When displaying responses in the DownloadTable, an Alert has been added to the bottom to indicate there are more responses available. This just adds the current number of responses shown to that message.
Note, this messaging should be reviewed by Content/Design.
=> Add number shown to "more responses" alert

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Replaces the MoreMenu with a direct Download link, since there is currently only one item in the MoreMenu.
Note, instead of removing all the MoreMenu code, just blocked it out behind a false boolean and rendered the Download button from the MoreMenu component itself. We can cleanup or re-use in future as necessary.
=> Download link instead of MoreMenu

public/static/content/en/terms-and-conditions.md, public/static/content/en/terms-of-use.md, public/static/content/fr/terms-and-conditions.md, public/static/content/fr/terms-of-use.md
Fixes #2890 
`https://digital.canada.ca/legal/terms/` ----->  https://digital.canada.ca/terms/
`https://digital.canada.ca/legal/security-notice/` -----> https://digital.canada.ca/security-notice/
=> chore: Update link URLs with CDS website update

lib/clientHelpers.ts
In some environments the test for the formatDate helper method started to fail. This is because Node 19 included a change to the `toLocaleDateString("en-CA"...` date format, so dates started coming out as `mm/dd/yyyy` instead of `yyyy-mm-dd`. See: https://github.com/nodejs/node/issues/45945
This PR updates the helper to just use the ISO8601 date, splitting off the time part.
=> Bugfix: Fix date format helper

components/form-builder/app/responses/DownloadSingleButton.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx, public/static/locales/en/form-builder-responses.json
Split out the "Download single file" button from the MoreMenu
Save the MoreMenu component for future
Add some table row / download button semantics for a11y
Following the example here: https://stackoverflow.com/questions/72231079/accessibility-how-to-handle-buttons-in-a-table
- Added a row header using the response id column for this purpose
- Added aria-labelledBy to the download button referencing the header
- Added some visually-hidden text to the row header and the button itself as well
=> DownloadTable table row + button semantics

lib/responseDownloadFormats/csv/index.ts
Taking a two-prong approach to preventing user-provided text from being interpreted as formula when importing to spreadsheets:
- Double-quote all columns
- If a string starts with any of `=,+,-,@` then add a single quote `'` character to the beginning
The second approach is required because for example in Google Sheets on Import, you can instruct Sheets to interpret strings as formatted text or formula, which bypasses the quoting in the first approach.
=> Escape all csv columns

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, lib/responseDownloadFormats/html-zipped/index.ts, pages/api/id/[form]/submission/download.ts
Moves the .zipping of individual HTML files + receipt to the client side.
=> fix: Move zipping of individual HTML files to client side

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, lib/responseDownloadFormats/csv/index.ts, public/static/locales/en/form-builder-responses.json, public/static/locales/en/my-forms.json, public/static/locales/fr/form-builder-responses.json, public/static/locales/fr/my-forms.json
- Fixes #2929 
- Fixes #2964 
- Fixes #2968
- Fixes #2956 
- Fixes #2957 
- Fixes #2965
- Fixes #2947 
- Fixes #2970
=> Content updates to clarify "New download formats" feature

components/form-builder/app/responses/Dialogs/ReportDialog.tsx, components/form-builder/app/responses/Dialogs/line-item-entries/LineItem.tsx, components/form-builder/app/responses/Dialogs/line-item-entries/LineItemEntries.tsx, components/form-builder/app/responses/Dialogs/line-item-entries/LineItems.tsx, components/form-builder/app/responses/DownloadTable.tsx, lib/clientHelpers.ts, pages/form-builder/responses/[[...params]].tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Adds a link to view Responses in Problem status. The link appears below the table next to the "Report a problem link."
In future, the intention is to have a Problem filter at the top like the other statuses, but have it hidden unless there are problems.
=> (feat) Add problem response section

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx
Fixes #2922 
When there is an error while downloading, an error is bubbled up to the DownloadTable and rendered there, but the Dialog remains open covering the error message.
This PR closes the dialog on error after setting the error state.
=> (fix) Close DownloadDialog on error

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx
Fixes #2933 
When downloading the Individual HTML Files with receipt, add a `_` prefix to the receipt filename so it appears at the top of the downloaded files.
When downloading CSV or JSON formats, ensure the receipt is delivered first, in case the multiple-file-download fails.
=> fix: Download receipt first

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx
Adds a GA logging event when downloading to log the selected format, form id, number of records, and a timestamp.
=> feat: Log GA event when downloading to record selected format

lib/responseDownloadFormats/html/components/ResponseHtml.tsx, lib/responseDownloadFormats/html/components/ResponseSection.tsx
See #2958 
There was some placeholder text on the individual HTML file rendering leftover from the initial refactor.
=> Replace placholder text (dd) with the Form Title

lib/responseDownloadFormats/types.ts, pages/api/id/[form]/submission/download.ts
Sorts questions/answers according to the form.layout array before downloading.
- Create a form with multiple inputs and use the Move up/down functions to re-order the questions.
- Create one or more responses
- Download responses in any format
- See that the questions/answers are sorted according to the sort order you set
Previously, doing these same steps, the questions/answers would be sorted by the order they were added, regardless of the layout array.
=> fix: Download ensure questions/answers are sorted according to form.layout

components/form-builder/app/navigation/TabNavLink.tsx, pages/form-builder/responses/[[...params]].tsx
Updates the styling of the navigation on the Responses page to appear more like tabs.
=> feat: Render Responses page navigation as tabs

lib/clientHelpers.ts, pages/api/share.ts
Prevents file save fails by slugifying the json filename of a share.
Go to a form and edit the form to have a title with special characters etc. like
`Test-TEST &^%$# hi there 2 `
Try Sharing the form (top share menu) and email it to yourself. The result should be an email with a json attachment with a file name that is slugified. 
e.g. the above should become `test-test-hi-there.json`
=> Updates share api to slugify the filename

components/form-builder/__tests__/util.test.js, components/form-builder/util.ts, components/form-builder/utils/itemHelper.test.ts, cypress/e2e/form-builder/autocomplete.cy.ts, cypress/e2e/form-builder/form-templates.cy.ts, form-builder-templates/contact.json, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
A minor update that changes autocomplete fields to use `tel` instead of `phone`
See #3046 for test instructions
=> Fix for form input autocomplete tel type

components/form-builder/app/responses/Dialogs/ConfirmDialog.tsx, components/form-builder/app/responses/Dialogs/line-item-entries/LineItemEntries.tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Error code missing in confirmation modal 
The user copied and pasted submission IDs into the confirmation modal and got a message that it was sending. They didn't get an error that it was the wrong format.
https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/3027 
| ![image](https://github.com/cds-snc/platform-forms-client/assets/70960477/944800bb-baf4-47c9-8d5f-6901e58d2f35) | …
=> fix: Confirm Dialog allows badly formatter code to be submitted

components/form-builder/hooks/useTemplateContext.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/3112
Update to monitor changes to description fields and force provider to re-render to make the save button available.
=> fix: update template subscribe

form-builder-templates/address.json, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Updates form-builder address content to fit semantically with a 1-line input vs. the old multi-line content. See #3046 form more info.
Content Update
```
EN: Include your street name and number. For example: 123 Main St. Apt 10
FR: Indiquez le nom de rue et le numéro d'unité. Par exemple : 123 Rue Principale Apt 10
```
=> Updates form-builder address content

pages/api/templates/[formID].ts, pages/api/templates/index.ts
- Add more information to null operation response log message (in Template API).
Before:
`Null operation response`
After:
`Template API response was null. Request: method = GET ; query = {"formID":"clrgrjwny000cmgxc9e838q7f"} ; body = ""`
=> chore: add more information to null operation log message

components/form-builder/store/useTemplateStore.tsx
Fixes #3130 
When duplicating fields, the duplicate function in useTemplateStore appends the word `copy` to the title of the element. 
Problem is, in richText elements, the title is not normally used and by appending text to it causes the word `copy` to render to the screen on the rendered form. Since the richText field doesn't have a Title field, it is then not fixable by the user.
This addresses the issue by ignoring the title field when duplicating richText elements.
=> fix: Don't append "copy" to title on duplicate richText elements

components/form-builder/app/shared/conditionals/ConditionalSelector.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3135
=> fix: 3135 Fix choice language

.github/workflows/prod-build-push-container.yml
Revert to using the AWS access keys for the Prod ECR push workflow as the OIDC roles will not exist
until the Prod infrastructure release.
Once the infrastructure release has gone through, this can be switched back to using OIDC roles.
- https://github.com/cds-snc/platform-core-services/issues/512
- https://github.com/cds-snc/platform-forms-client/pull/3116
=> revert: use AWS access keys instead of OIDC role

components/form-builder/hooks/useTemplateContext.tsx
Update to ensure changes to filename flag a template update.
Note: Input needs to be blurred after updated to fire the state update.
=> chore: fix filename save draft

components/form-builder/app/settings-modal/SettingsDialog.tsx
Support ticket  (#16510)
Fixes issue where delivery option was not saving when using the Settings dialog modal.
> ...  If you try to change your Response delivery option from download responses from GC Forms to receive responses by email and click save at the bottom, it doesn’t change the response delivery option. It stays Download responses from GC Forms in both the Form set up and the Settings page.
=> fix: settings modal save

components/form-builder/store/useTemplateStore.tsx
Support ticket https://cds-snc.freshdesk.com/a/tickets/16520
Issue when an element is removed that has conditional rules attached the get choice look up was failing.
=> fix: get choice lookup when question is removed

components/auth/ReVerify.tsx, lib/auth/cognito.ts, pages/api/auth/2fa/request-new-verification-code.ts
- Fixed issue with 2FA when requesting new code while there is no active (2FA) session. 
Context: 
It happens if a user has two instances of the GC Forms application opened (2 tabs in a browser) and requests a new 2FA code in of them after he completed the sign-in flow on the other one. 
This is based on the review of some logs due to an alarm being triggered in production. This is something we can reproduce every time when we test locally.
- Open the GC Forms application in two different tabs on your browser
- Reach the 2FA verification code page on both instances
- Enter a valid code on one of them and complete the sign-in process
- Try to request a new code on the tab that is still expecting a verification code
- You should be redirected to the `http://localhost:3000/auth/login` which …
=> fix: request new 2FA code does not work if there is no active 2FA session

components/clientComponents/auth/ReVerify.tsx
Updates re-verify to be consistent with how other POST requests add data the http body. This was originally not working because the data was added to the http message body as url encoded and trying to be read as json.
Try signing on and at the Verify step, try clicking the link/button to send a new code. If you get a code it works.
=> Fix for re-verify not sending a code

lib/validation.tsx
Fixes an issue where when using conditional rules ... elements with empty rules arrays we're bypassing validation checks.
=> fix: validation when conditional rules array is empty

components/clientComponents/form-builder/app/shared/ClosedBanner.tsx
Fixes responses settings link.
1. Go to a form with responses
2. Go into settings and set the status to closed
3. Go back to the form responses and a link should be displayed above the table to go to settings
4. Click the settings link
5. You should be sent to the settings page
=> Fix for broken settings link on responses page

middleware.ts
Closes #3162 
Fixes pagination on Responses page by ensuring searchParams are appended to a URL when redirecting in the language middleware.
=> Append query params when redirecting in language middleware

components/form-builder/app/shared/conditionals/ConditionalIndicator.tsx
[(#16582)](https://cds-snc.freshdesk.com/a/tickets/16582)
Fixes issue where conditional indicator was showing a parent id and not a question #
Before
After
=> fix: conditional indicator question number output

app/(gcforms)/[locale]/(form administration)/form-builder/preview/[[...slug]]/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/settings/[[...slug]]/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/settings/[formID]/form/clientSide.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/settings/branding/clientSide.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/settings/branding/page.tsx, next-env.d.ts
closes https://github.com/cds-snc/platform-forms-client/issues/3169
- Fixed hydration issue in settings (base settings, branding and form management) and preview pages.
As discussed with @timarney and @bryan-robitaille, we will continue using this `useRehydrate` hook until we implement a global layout where we will initialize the `TemplateStoreProvider` once instead of having it done on all new rendered pages (something that appears to be creating a new empty context every time).
=> fix: hydration bug in settings pages

utils/archivableAuditLogsMigration/.env_example, utils/archivableAuditLogsMigration/add_archivable_status_field_to_audit_logs.ts, utils/archivableAuditLogsMigration/package.json, utils/archivableAuditLogsMigration/tsconfig.json, yarn.lock
- Added new migration script to be executed in both Staging and Production to make existing audit logs archivable.
- This script can be tested locally. Just make sure you create audit logs without that new `Status` field first.
The AWS DynamoDB console gives us an idea about the number of audit logs that we currently have in our table and that we will most likely have to migrate:
- Staging: 437,030
- Production: 357,090
=> chore: added new migration script to make existing audit logs archivable

.env.example, .github/workflows/cypress.yml, README.md, lib/auth/passwordReset.ts, lib/deactivate.ts, lib/integration/freshdesk.ts, lib/ownership.ts, lib/responseDownloadFormats/html-aggregated/components/CopyCodes.tsx
Renames the NEXTAUTH_URL parameter to HOST_URL as it is used in other parts of the application.
Future versions of Next-Auth (v5) have an issue when the NEXTAUTH_URL is present.  Our current version (V4) does not explicitly require the NEXTAUTH_URL and can operate without it.
Infrastructure Dependency: https://github.com/cds-snc/forms-terraform/pull/606
- Rename the NEXTAUTH_URL in you .env file to HOST_ENV
- Run the app with yarn dev  or yarn build && yarn start
=> chore: Rename NEXTAUTH_URL as it is no longer required for Next-Auth

app/(gcforms)/[locale]/(support)/contact/actions.ts, app/(gcforms)/[locale]/(support)/contact/components/client/ContactForm.tsx, app/(gcforms)/[locale]/(support)/contact/page.tsx, app/(gcforms)/[locale]/(support)/support/actions.ts, app/(gcforms)/[locale]/(support)/support/components/client/SupportForm.tsx, app/(gcforms)/[locale]/(support)/support/page.tsx, app/(gcforms)/[locale]/(support)/unlock-publishing/actions.ts, app/(gcforms)/[locale]/(support)/unlock-publishing/components/client/UnlockPublishingForm.tsx, app/(gcforms)/[locale]/(support)/unlock-publishing/page.tsx
Fixes server actions not throwing a "Malformed request" error. 
Also moves the forms intro content back into the forms components. This keeps the original design of showing just an error card (not the page title etc.) when an error is thrown from the server.
=> Fixes support actions error handling

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/ClassificationSelect.tsx
Ensure protected B isn't available to be chosen in the settings panel dropdown if the delivery option is set to email.
=> Fix settings panel protected B

app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SaveButton.tsx, lib/hooks/form-builder/useTemplateContext.tsx
Previously, the SaveButton imported the `createOrUpdateTemplate` server action directly. The problem when autosaving on page exit seems to be that the serverAction becomes de/re-registered when navigating and does not fire.
This PR moves the actions import to useTemplateContext which does not unmount on navigation, and SaveButton can just access it through there.
=> Fix: autoSave on navigation

components/clientComponents/globals/layouts/UserNavLayout.tsx
Forms link was displaying on certain pages when logged out. Added a conditional wrapper around the link in UserNavLayout.tsx
| Logged out                                          | Login                                        |
| ![image](https://github.com/cds-snc/platform-forms-client/assets/1187115/90c236c8-a326-4607-89ad-351ca625376a) | ![image](https://github.com/cds-snc/platform-forms-client/assets/1187115/b60f8eb0-d461-4da8-a0e2-12aec6c74572) |
=> Fix - Hide Forms link when logged out

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/page.tsx
Visiting Responses when logged out was throwing an error, but should have been rendering the LoggedOutTab component.
This happened when we moved some server actions up to the layout.tsx component, but the LoggedOutTab component was being rendered in the page.tsx component, which was too late.
=> Fix - Logged out responses page should render LoggedOutTab

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Responses.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/page.tsx
Had a bunch of extra checking for unauthed users and unsaved templates in the Layout, Page, and Responses components. But since we catch everything in the Layout, no need for alternate states further down.
=> Cleanup: Responses unauthed + unsaved states

app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/[id]/manage-forms/components/server/FormCard.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/DeliveryOptionEmail.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/ClosedBanner.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/ConfirmFormDeleteDialog.tsx, app/(gcforms)/[locale]/(form administration)/forms/[[...path]]/components/client/Menu.tsx, components/clientComponents/myforms/Card/Card.tsx, lib/ownership.ts, lib/responseDownloadFormats/html-aggregated/components/CopyCodes.tsx, next.config.mjs
Fixes a bunch of stray URLs with the FormID in the wrong spot.
Also adds a redirect from `/form-builder/[id]/responses` to `/form-builder/[id]/responses/new`
...and simplifies two existing redirects.
=> Fix urls with formId in wrong position

__utils__/mocks/server-actions/submitForm.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/branding/components/BrandingRequestForm.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/clientSide.tsx, components/clientComponents/forms/DynamicRow/DynamicRow.test.js, components/clientComponents/forms/Form/Form.test.js, components/clientComponents/forms/Form/Form.tsx, components/clientComponents/forms/index.ts, jest.config.ts, lib/hooks/useGCFormContext.tsx, lib/tests/clientHelpers.test.js, lib/tests/formBuilder.test.js
Fixes all the failing tests introduced in [the PR to change Submit API to server action](https://github.com/cds-snc/platform-forms-client/pull/3354).
Creates a global mock for `submitForm` to fix most tests.
Creates a local mock for the Form.test.js file so it can test that the action has been called.
=> submitForm server action mocks

app/layout.tsx
Adds flag check prior to loading script
Before:
After
=> Check flag recaptcha flag

components/clientComponents/globals/Header/Header.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Updates the form-builder header to be "Forms" consistently across pages.
=> Update form-builder header title to be consistent

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/page.tsx
Fixes #3391
Before a form is saved, its id in the url is 0000. 
We can use this to disable form submission.
=> Disable submit on unsaved form preview

app/(gcforms)/[locale]/(form administration)/forms/components/ResumeEditingForm.tsx
Fixes issue where skeleton loader was showing when no session would ever exist.
=> Fix resume loading

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/TitleAndDescription.tsx, lib/store/useTemplateStore.tsx
Set isPublished to true in templateStore on publish.
Addresses a bug where the left nav didn't update after publish and Edit was still available, and you could also get to the Edit screen in some cases.
=> Set is published

app/(gcforms)/[locale]/(support)/contact/actions.ts, app/(gcforms)/[locale]/(support)/support/actions.ts, app/(gcforms)/[locale]/(support)/unlock-publishing/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/login/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/login/components/client/LoginForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/components/client/MFAForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/register/action.ts, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/action.ts, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/InitiateResetForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/PasswordResetForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/QuestionChallengeForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/setup-security-questions/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/setup-security-questions/components/client/SecurityQuestionsForm.tsx, app/(gcforms)/[locale]/(user authentication)/profile/action.ts
fixes: #3430 
- Modified Valibot to abort validation pipeline early so only 1 validation error is generated per field.
- Ensured validation errors from form state were being passed down to input components.
Fixes pages: 
- Support
- Unlock Publishing
- Login
- MFA
- Register
- Reset Password
- Security Question Setup
- Profile
| ![image](https://github.com/cds-snc/platform-forms-client/assets/25329319/cef119e1-fb0e-43eb-b0f2-a9754bd3fc64) | ![image](https://github.com/cds-snc/platform-forms-client/assets/25329319/7205e881-a033-44d5-ba2f-6ebd64b19f86) |
=> fix: Validations passing multiple issues per field and Error highlighting on input fields

__utils__/mocks/file-type/index.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Dialogs/ConfirmDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Dialogs/ReportDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/ResponseEmail.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/buildFormDataObject.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/parseRequestData.ts, app/(gcforms)/[locale]/(support)/unlock-publishing/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/policy/components/client/AcceptButton.tsx, app/(gcforms)/[locale]/(user authentication)/auth/register/action.ts, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/action.ts, app/api/id/[form]/apiusers/apiusers.ts, components/clientComponents/admin/FormAccess/FormAccess.tsx, components/clientComponents/forms/FileInput/FileInput.tsx, components/clientComponents/forms/Form/Form.tsx, jest.config.ts, lib/formBuilder.tsx, lib/tests/validation/fileValidationClientSide.test.ts, lib/tests/validation/fileValidationServerSide.test.ts, lib/tests/validation/validation.test.js, lib/tsUtils.ts, lib/types/form-response-types.ts, lib/validation/fileValidationClientSide.tsx, lib/validation/fileValidationServerSide.tsx, lib/validation/validation.tsx, next-env.d.ts
part of the work related to https://github.com/cds-snc/platform-forms-client/issues/3293
- Reworked file validation for the file input component. Two types of validation are applied at different stages (client and server)
- Create a form with a file input component
- Try to upload a file with a size larger than 8 MB
- Try to upload a file with an extension that is not allowed (e.g. .zip)
- Try to upload a file with a modified extension (e.g. rename a .zip to .csv)
You can also call the submit API directly to try to bypass the client side validation. Here is an example where I tried to upload a file larger than 8 MB by passing a fake size value:
```
POST
http://localhost:3000/api/submit
HEADERS
X-CSRF-Token: <insert_valid_token>
DATA:
{
"formID": …
```
=> chore: rework file validation

app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/[id]/manage-forms/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/server/UserCard.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/server/UsersList.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/page.tsx
closes: #3422 
- Ensures the data is refreshed when a form is deleted or modified on the manage forms page
- Fixes permissions on the account page.
-  fixed user view permission so it checks if a user has view all users
- updated permission to manage all forms to pass to card list.
=> fix: Manage Forms page refresh after delete

i18n/translations/fr/profile.json
fixes: #3456
| ![Screenshot 2024-04-22 at 14-35-32 Profil](https://github.com/cds-snc/platform-forms-client/assets/25329319/56615eed-e5b3-4340-9405-2e13d131e7c9) | ![Screenshot 2024-04-22 at 14-34-02 Profil](https://github.com/cds-snc/platform-forms-client/assets/25329319/9d80b9a3-0c42-4c28-a132-db6e82b41697) |
Login to an account without publishing permissions and navigate to Profile page.
=> fix: Profile translation for locked publishing

utils/reliabilityQueueTableTTLDataTypeMigration/.env_example, utils/reliabilityQueueTableTTLDataTypeMigration/change_ttl_data_type_from_string_to_number.ts, utils/reliabilityQueueTableTTLDataTypeMigration/package.json, utils/reliabilityQueueTableTTLDataTypeMigration/tsconfig.json, yarn.lock
Follow up for https://github.com/cds-snc/forms-terraform/pull/637
- Adds script to convert TTL data type from String to Number in the ReliabilityQueue DynamoDB table.
This script should be executed in both environments once https://github.com/cds-snc/forms-terraform/pull/637 has been deployed. We can already do it in Staging.
=> chore: add script to convert TTL data type from String to Number in the ReliabilityQueue DynamoDB table

app/(gcforms)/[locale]/(support)/unlock-publishing/components/server/Success.tsx
Fixes issue with missing localization string in a button on the Unlock Publishing success screen.
Before
After
=> Fixes unlock publishing page localization string

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/useGroupStore.tsx
Renames getGroups in the useGroupStore to getTreeData for clarity since it returns a treeData object
=> Rename getGroups to getTreeData for clarity

app/(gcforms)/[locale]/(form administration)/forms/components/server/Card.tsx, app/(gcforms)/[locale]/(form administration)/forms/page.tsx, i18n/translations/en/my-forms.json, i18n/translations/fr/my-forms.json
Fixes card title localization string by adding it to the my-forms locale file.  The localization key was copy+paste from the form-builder file. The key is used in form-builder also so there is a chance that the key might be updated and then a bug created in my-forms.
Also, the locale from the Page params is used to be more consistent (vs. using 18n locale one place and page params locale another place)
**Before**
**After**
Go to the Forms (my-forms) page. Select French for the language. Any card without a name should have the French string printed out.
=> Fixes Card Title Localization

components/clientComponents/globals/Header/Header.tsx
Adds filename input for auth'd and non auth'd views
For details see: https://github.com/cds-snc/platform-forms-client/issues/3514
=> Fix filename input

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Responses.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/layout.tsx
Fixes #3502
I think what was observed in this issue has to do with NextJS server rendering and caching behaviour. Difficult to recreate/test as once the page has been server rendered, there is no longer a problem.
To address, I've moved the TitleAndDescription component out of the Layout file (server rendered) and down into the Responses component which is where it was originally, and is client rendered.
Should be able to test on the review environment for this PR since the page cache will have been cleared.
=> Bufix Responses TitleAndDescription

.github/workflows/vitest.yml, jest.config.ts, lib/vitests/logger.test.ts, package.json, vitest.config.mts, yarn.lock
[Vitest](https://vitest.dev/) is a testing library that is API-compatible with Jest. The main advantages over [Jest](https://jestjs.io/) are:
- Vitest is compatible out-of-the-box with [TypeScript](https://www.typescriptlang.org/) and ESM
For this PR, the idea is too keep all Jest test in their folders, and move slowly the tests in a new tests-vitest/ folder
=> chore: Vitest setup

components/form-builder/app/edit/elements/lexical-editor/tests/RichTextEditor.cy.tsx, pages/api/submit.ts
linked to https://github.com/cds-snc/forms-terraform/pull/626
- Adds a hack to handle Submission lambda function name which is going to be changed in an upcoming infra update.
This should be deployed to Staging and Production "as soon as possible" so that the Lambda containerization update on the infra side can also be released.
=> feat: implement temporary hack to handle Submission lambda name change

package.json, prisma/seeds/seed.ts
Modifies the Prisma seed script to behave more like 'find or create' so that it does not duplicate the creation of templates and users on every `yarn dev` cycle.
Makes `next --turbo` the default for development mode.
=> fix: Selective Prisma seeding for development

lib/auth/2fa.ts, lib/auth/passwordReset.ts, lib/deactivate.ts, lib/integration/notifyConnector.ts, lib/ownership.ts
Centralizes the `sendEmail` function calls and error handling into the `@lib/integrations`.
- The error handling includes extracting the exact detailed error message from Notify to include it in the logs.
- Adds a check to ensure the env var `TEMPLATE_ID` is set before calling the `sendEmail` function.
Should provide more context for issue: #3530
=> fix: Notify Error Handling Centralization

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .github/workflows/cypress.yml, Dockerfile, Dockerfile.pr, docker-compose.yml
This reverts commit 7fe16413d8c6184c9fe55d3dda9fd34f491bc300.
Breaking change introduced in Node 18.19
=> fix: Revert "chore(deps): pin dependencies (#3230)"

.github/workflows/backstage-catalog-helper.yml, .github/workflows/cache-cleanup.yml, .github/workflows/codeql.yml, .github/workflows/cypress-component.yml, .github/workflows/cypress.yml, .github/workflows/delete-ecs-task-defs.yml, .github/workflows/eslint.yml, .github/workflows/export_github_data.yml, .github/workflows/jest.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/pr-review-client-deploy.yml, .github/workflows/pr-review-sync-env-vars.yml, .github/workflows/prod-build-push-container.yml, .github/workflows/prod-deploy.yml, .github/workflows/s3-backup.yml, .github/workflows/staging-build-push-container.yml, .github/workflows/staging-deploy.yml, .github/workflows/test-container-build-production.yml, .github/workflows/test-container-build-staging.yml, .github/workflows/vitest.yml
Updates github actions to run latest versions as Node 16 is now depreciated.
=> chore: update github action plugins to latest

app/api/share/route.ts, lib/auth/2fa.ts, lib/integration/notifyConnector.ts, lib/tests/auth/passwordReset.test.ts, package.json, types/notifications-node-client/index.d.ts, yarn.lock
Removes `notifications-node-client` and implements a custom instance that creates a custom axios config.
Testing now shows that the detailed error is included in the logs.
=> fix: Replace Notify Client with custom instance

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx
Removes extra group "End" option that was being pushed in before we added it to group initialize.
=> Remove duplicate end group

.eslintignore
Ignore old API tests for ESLint
=> ESLint - ignore old API tests folder

next.config.mjs
The app router branch edit route now always uses an ID in the path.
This PR adds a redirect to the correct new path for edit.
Testing
- Visit /form-builder/edit
- You should be automatically redirected to  `/en/form-builder/0000/edit`
=> Add Edit page redirect

app/api/id/[form]/submission/confirm/route.ts, app/api/id/[form]/submission/report/route.ts, app/api/notify-callback/route.ts, lib/integration/dynamodbConnector.ts, lib/vault.ts
- Trying to fix the `CredentialsProviderError: Could not load credentials from any providers` error by initializing the `DynamoDBDocumentClient` only once.
=> fix: create only one instance of DynamoDBDocumentClient

lib/integration/notifyConnector.ts
- Removed `request` information from Axios error log
=> chore: remove request information in Axios error log

lib/auth/nextAuth.ts, middleware.ts, package.json, yarn.lock
fixes: #3574 
The NextAuth middleware was using the default value of 30 days for session length even though the main NextAuth configuration in the app was set to 2 hours.  This was creating a condition where the middleware would overwrite the JWT token expiry and the effectively remove the 2 hour limitaiton.
Fix:
- Explicitly set the session length for the JWT in the middleware configuration
- Verify next auth session cookie in Staging will have expiry set for 30 days after logging in.
- Ensure PR Review environment has same cookie set for 2 hours after logging in.
- Dig deeper into the code base of Auth JS to see if there is a way to reduce the possible duplication of setting cookies between the middleware running on Edge and the Node application.
=> Fix: Session expiry set to 2 hours

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx
Small update to ensure text wraps and gets truncated for logic view
=> Fix node text wrapping

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/types.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/useGroupStore.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/groupsToTreeData.ts
Adds tree items for into, policy, confirmation
Removes "review" group from displaying in the TreeView
=> Add "ghost items" to tree view

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx
Re-adds the language toggle when editing with groups on.
=> Add language toggle for group edit

components/clientComponents/globals/Header/Header.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3643
Adds missing product name to "Start page" and "Forms"
=> Missing product name in header

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, lib/types/form-builder-types.ts
Updates / add error handling for settings modal 
- Updates some variable names and notes to try to make it more clear for local state, vs template store vs DB calls
- Don't update the template store until after DB call is successful
- Add toast message for server action errors
- Move delivery option check inside the `try` server action so it doesn't throw outside
https://github.com/cds-snc/platform-forms-client/assets/62242/644da4e7-8026-4052-8a69-9e093105b0d6
=> Settings modal - update error handling

app/(gcforms)/[locale]/(form administration)/form-builder/components/ShareModal.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/tag-input/TagInput.tsx, app/api/share/route.ts
Fixes 2 issues with error handling while testing the share functionality
1) An empty array of emails could be sent in the payload
2) If an empty array was sent to the server it was getting past the validation as the value exists but was empty.
With fixes
=> Share modal update error handling

.env.example, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, lib/auth/cognito.ts, lib/auth/nextAuth.ts, lib/nagware.ts
Fixes #3657 (The new version of NextAuth throws an error for any bad login attempt. This affects the MFA section)
This PR fine-tunes the AuthJs logger customization.  
It also fixes a flaky test.
=> fix: auth error handling noise

app/(gcforms)/[locale]/(support)/contact/components/client/ContactForm.tsx
Part of https://github.com/cds-snc/platform-forms-client/issues/3655
Adds a missing alert for the client side if a server side error occurs.
=> * Add missing contact forms error alert on client side.

app/(gcforms)/[locale]/(support)/support/components/client/SupportForm.tsx
Part of #3655 
Adds a missing alert for the client side if a server side error occurs.
=> * Add missing error handler on client side for support form.

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx
Update to allow tree item title to handle double click to rename.
=> Treview - handle double click to rename

app/(gcforms)/[locale]/(support)/unlock-publishing/components/client/UnlockPublishingForm.tsx
Part of #3655 
Adds an alert that the request failed if clicking unlock publish throws an error.
=> * Add missing error message should unlock publish request fail.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Responses.tsx
Fixes #3588 
We were using css to hide the TitleAndDescription when there is a success message on screen, this assumes that users always confirm all downloaded responses, which does not always apply.
=> Don't hide titleAndDescription with success message

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SaveButton.tsx
Fixes save button CSS so link CSS issue so the text doesn't appear as white -> white when active
Tested fail throwing an error from the sever action using a know string value i.e. 
```javascript
export const createOrUpdateTemplate = async ({
id,
formConfig,
name,
deliveryOption,
securityAttribute,
}: CreateOrUpdateTemplateType): Promise<{
formRecord: FormRecord | null;
error?: string;
}> => {
try {
revalidatePath("/[locale]/forms", "page");
if (formConfig.titleEn === "fail") {
throw new Error("Error saving template!!");
}
```
=> Update save button fail CSS

lib/responseDownloadFormats/html/components/RowTable.tsx
Fixes html download page double scroll bar in Edge.
Example download page in Edge
=> Fixes html download page double scroll bar in Edge

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts
Tested with LocalStack off so it's unable to call the Lambda
Error:
=> Fix error return for process form

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Dialogs/DownloadDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/DownloadSingleButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/DownloadTable.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/RetrievalError.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/error.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/exceptions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/page.tsx, i18n/translations/en/form-builder-responses.json, i18n/translations/fr/form-builder-responses.json, lib/responseDownloadFormats/types.ts, lib/types/form-builder-types.ts
Adds a generic error handler for Responses section.
- Will be displayed if any rendered component throws an uncaught exception
Adds a specific error component for when there is an issue fetching responses server side.
- Will be displayed if there was an error retrieving responses in the server action
Previously, both of these cases would throw the generic app level error:
=> Responses section error handling

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/page.tsx
Translate Navigation should only be displayed when Groups are turned off.
=> Fix: Only show Translate Navigation when groups off

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleCanDropAt.ts
Prevent a section from being dropped before Start.
=> Prevent drag/dropping section before Start

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx
Adds background "dots" to logic view.
=> Add background to logic view

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleCanDropAt.ts, styles/_form-builder.scss
- Render item container as Div so that the Delete icon can be a button
- Bugfix: Prevent drop after Review when there are open groups
- Truncate long Item titles
- Render custom dragBetweenLine (target)
- Allow dropping items on folders (prop + canDropAt handler)
- Allow dropping items and folders below open folders (prop)
- Eliminate dragBetweenLine "drift"
=> Fix: Treeview Drag/Drop fixes

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleOnDrop.ts
When dragging items across groups, the group name was being set to titleEn instead of name
=> Fix disappearing group name

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleCanDropAt.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleOnDrop.ts
Handle dropping on empty Groups.
Adds highlight around Groups when dragging over.
If you drop an item on a group that has items it defaults to dropping it at index 0 (top)
=> Handle drop on empty folder

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/groupsToTreeData.ts, lib/store/useTemplateStore.tsx, next-env.d.ts
Fixes issue where a direct link to `/en/form-builder/0000/edit`
Was not initializing the group sections.
=> Update init form to allow direct link to page for groups

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/branding/components/Branding.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/layout.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Requested changes are marked in #3750.
* Purple help text is currently under "Data Classification" heading, when it should be under the "Settings" heading
* Help text in incorrect it should read "These settings can only be changed before publishing." "Ces paramètres ne peuvent être modifiés qu’avant la publication."
* Spacing is inconsistent and too cramped between each section: Data classification, Response delivery option, Purpose and use. * * Ensure there is a class of "mb-10" between each section.
* text correction: Response delivery option should be "Delivery option" "Option de livraison"
* text correction: "Retrieve responses within 45 days." should be "GC Forms holds data temporarily for 30 days." "Formulaires GC conserve les données temporairement pour 30 hours."
* Bold the line …
=> Minor UI Fixes for Settings Page

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, components/clientComponents/forms/NextButton/NextButton.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
- Adds missing string for Next button
- Fixes wrong key for empty page text
- Fixes height issue for add section button
=> Add fr string for Next button

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SectionName.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx
- Updates styling for Logic view nav under the tab buttons
- Updates React flow to remove default keyboard a11y --- we'll just tab to each button.
- Fixes bug where when the active ID was set to "end" - end would be selected when you visit the logic tab which shouldn't be possible. 
https://github.com/cds-snc/platform-forms-client/assets/62242/7b51b12e-df60-4cbc-aa3a-ac95e5733b2a
=> Update logic view nav and remove React flow default a11y

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/FormPurposeHelpButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/index.ts, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Closes #3753 &  
Closes #3754 
--
Closes #3750
* Italics "Administrative purposes," "Non-administrative purposes,"
*  Help text for choosing a delivery option is missing
*  Help text for Administrative purposes reflects information for choosing a delivery option (the current info here should be for the missing help text in the point above^^)
=> * Update and add learn more administrative purposes box.

app/(gcforms)/[locale]/(form administration)/form-builder/components/ClassificationSelect.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
- Minor follow-up fixes from #3219 
- Fix minor FR typos 
- Remove redundant duplicate text
- Remove "default" dropdown
- Missing strings for conditional logic
- Translate "Next" button
- Missing translation strings for keyboard shortcuts
=> Translations and copy

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ConfirmationTitle.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx
Fixes #3755
**Groups off**
**Groups on**
=> Hide section title when grouping is off

lib/auth/nextAuth.ts, middleware.ts
Ensure that NEXTAUTH_URL is also used for the trusted host setting of Auth.js until infrastructure is updated to ensure AUTH_URL is available.
=> fix: Ensure trusted host also uses nextauth_url

.github/workflows/release_generator.yml, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx
Updates group node outlines for better a11y
Before
=> fix: logic view group node outline styling

lib/auth/nextAuth.ts, middleware.ts
Temporarily trust the  x-forwarded-for header for Auth.js to stop issue with setting headers after the response is already sent to the client.
=> chore: Temporarily trust host for Auth.js

lib/auth/nextAuth.ts, lib/origin.ts, middleware.ts
Removes any remaining reference to NEXTAUTH_URL in the codebase as we can implicitly trust that the Elastic Load Balancer safely sets the Host header and ignores any header provided in the original request.
Confirmed here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#host-header-preservation
It would also appear that Auth.js guidance is now that the `trusted_host` should always be set to true: https://authjs.dev/reference/core#trusthost
=> fix: trusted host check and NEXTAUTH_URL

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/processFormData.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/resend/components/client/ReVerify.tsx, lib/auth/cognito.ts
Updates the handling of 2fa "resend code" path errors. 
- Adds a log entry that identifies the email address trying to request a new token `{"level":"warn","time":1718129549075,"msg":"Failed to send new verification code. Reason: Missing 2FA session for user bryan.robitaille@cds-snc.ca."}`
- Fixes the error path to ensure the server redirects the user to `/auth/login` if a session does not exist instead of relying on the browser.  In NODE_ENV Production the error was being sanitized and wasn't being properly handled client side.
Also modifies the "form submission" event log to identify that it is a form submission and not just listing the form ID.
=> chore: Update error handling for 2fa

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/processFormData.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/resend/components/client/ReVerify.tsx, lib/auth/cognito.ts
take 2 of #3801 
Updates the handling of 2fa "resend code" path errors.
Adds a log entry that identifies the email address trying to request a new token {"level":"warn","time":1718129549075,"msg":"Failed to send new verification code. Reason: Missing 2FA session for user bryan.robitaille@cds-snc.ca."}
Fixes the error path to ensure the server redirects the user to /auth/login if a session does not exist instead of relying on the browser. In NODE_ENV Production the error was being sanitized and wasn't being properly handled client side.
Also modifies the "form submission" event log to identify that it is a form submission and not just listing the form ID.
=> Fix: mfa resend when no session

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx
- Render custom DragBetweenLine with arrow indicator
- Customize DragImage for form elements
| <img width="460" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/a3fadc68-bdec-4972-88ff-0ce74826d0d0"> | <img width="456" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/6ce2ce26-aea9-43d9-b472-e3e6cd7b1520"> |
| <img width="437" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/c41533c0-48ef-48e1-bafa-bba0dcb7a93b"> | <img width="451" alt="image" …
=> fix: Improved Drag target indicator and DragImage

lib/formBuilder.tsx
Fixes #3803 
Added a key prop to the Combobox to force a refresh when toggling LanguagePriority on Preview.
To test:
- Create a form
- Add a Departments dropdown
- Go to Preview
- Check that the contents of the dropdown match the language of "Previewing in"
- Toggle the "Previewing in" language
- Check that the contents of the dropdown match the language of "Previewing in"
=> fix: Departments dropdown language toggle on Preview

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/page.tsx
Fixes issue where a user could land on the responses page with a form that has never been saved (doesn't have form responses).
Adds early return to avoid API lookup which throws
```
Forms
- Template 0000 must have associated owners to access responses
```
=> fix: Add early return for responses page when a form hasn't been saved yet 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/page.tsx
Reverts #3824 in favour of a better fix - catches at the actions layer, and checks for UUID as well.
=> fix: Fix for unsaved form Responses error

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/3791
Fixes issue where the selected state was always using the "saved" next action.
**Bug**
https://github.com/cds-snc/platform-forms-client/assets/62242/a65511b0-6c7e-41b3-9a00-87ca969fefdc
**Fixed**
https://github.com/cds-snc/platform-forms-client/assets/62242/a8040523-096f-4394-b43f-7a4bbbf387e6
=> fix: selected state for single action selectors

.devcontainer/docker-compose.yml
Add the `db` and `redis` services back to the devcontainer's docker-compose file to support localhost environments without a LocalStack license.
1. Remove all running docker containers.
2. Build the devcontainer.
3. Setup your local `.env` to connect to the `db` and `redis` services.
```env
DATABASE_URL=postgres://postgres:chummy@db:5432/forms
REDIS_URL=redis
```
4. Run `yarn dev` and expect the app to load at `http://localhost:3000`.
None.
=> fix: add back devcontainer db and redis services

app/(gcforms)/[locale]/(user authentication)/auth/login/components/client/LoginForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/components/client/MFAForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/policy/components/client/AcceptButton.tsx, components/clientComponents/globals/Buttons/ButtonSubmit.tsx, components/clientComponents/globals/Buttons/SubmitButton.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
The original issue was the Agree button would toggle between disabled and back to enabled when the Agree form was submitted.
This fix adds:
-  a new button focussed on submitting with related accessible loading status etc.
- a new button that wraps the above button but for use with server actions (convenience)
Pages updated to use these buttons:
- login
- mfa
- policy (agree page)
Demo of impacted pages
https://github.com/cds-snc/platform-forms-client/assets/107579368/fc0c7491-90f1-4119-954d-4f7ccd530614
Todo:
Add to remain auth related pages?
=> chore: add loading state to submit button

.eslint-tailwindcss.js, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/page.tsx, styles/_form-builder.scss
- use css rule vs inline style to set container height
=> fix: use css rule vs inline style to set container height

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx
Updates Right Panel tabs to use ID from template store if it's different than the possibly stale ID coming in from props.
=> Fix: Ensure the correct id is being used in RightPanel

.gitignore, package.json
Adds yarn command for `dev:secure` 
This runs next the `experimental-https` flag allowing us to use https for our localhost
=> chore: add https support for local development

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/Legend.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/page.tsx, components/serverComponents/icons/LogicOptionArrowIcon.tsx, components/serverComponents/icons/LogicSectionArrowIcon.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3789
Adds some icons with descriptions for the meanings to the logic view.
=> chore: Add legend to logic view

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementRequired.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalForm.tsx, cypress/e2e/form-builder/form-builder.cy.ts
Fixes #3787 
This had been affecting forms with groups turned on. The component would not rerender when the checkbox state was changed.
Modified the component to use local state for the checkbox, rerenders fine now.
=> Fix: Required checkbox not updating

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementRequired.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalForm.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/MoreModal.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBodyRoot.tsx, cypress/e2e/form-builder/form-builder.cy.ts
Fixes #3867 
Learning : 
> Fully uncontrolled — in this case your custom <Input> would take defaultChecked as a prop, and pass it to DOM <input>. The state would be inside the <Input> component itself. The prop value would only ever be used once, when the component is first rendered, and then ignored. The parent would have no way to "force" that state to become something else. If you ever need to reset the input, you'd have to mount it with a different key.
TL;DR : If you want a checkbox to change across components, change it's "key" value (eg: key="{the things id}+{checked or not}"
---
To test: 
1. Create a form.
2. Add a Question
3. Edit the Title, and the Required checkbox.
4. Note the values, and then click the "More" modal. The values should be the same. Edit them in the Modal.
5. …
=> Fix the "More" Modal Pushing Data up and Down

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/EndMarker.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3872
Fixes issue where "hidden" svg marker was covering the logo and part of the form filename input on the logic page
https://github.com/cds-snc/platform-forms-client/assets/62242/747434b2-5a86-4803-90e7-144969ea603f
=> fix: move marker off screen for logic view

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/conditionals/AddOther.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3793
Fixes issue for Other field when form is "grouped".
When using "groups" groupID was not passed so the field was not being added to the group.
=> fix: "Other" question field isn't showing up, so clicking the link "Other" takes you no where 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx
Resolves #3891 
To test, go to settings page of a form, and set delivery option to email. You should now be able to change form purpose and as long as it's a new value the save button enables.
=> * Form Purpose w/ Delivery Option Email - Fix : Save Disabled

app/api/templates/route.ts
Fixes small issues with a nested !response found while reviewing some other code.
Prior to PR:
```javascript
if (!response)
if (!response)
```
=> fix: nested check for response 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Edit.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, components/clientComponents/globals/ClientContexts.tsx
Moves refs provider outside of edit so we can make use of it from elements such as the TreeView.
=> chore: Move refs provider

package.json
- Increases maximum allowed memory space for our Next server. Following recommendation from [Node documentation](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) I set it to 3.5 GB because our ECS is configured with 4 GB of memory.
After investigating on a recent Out of Memory issue in production I could not find any root cause that would explain it. Since it was the first time it happened I decided to just go with a simple change that was recommended on different online websites.
For reference, here is the Fatal error we got in production:
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
=> chore: increase next server maximum memory

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx
Fixes issue where the next action selector was ending up using a previously selected value from stale state.
=> fix: Add key for next action

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/upload/page.tsx, app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/page.tsx
Ensures that only users with "manage all forms" privilege can view the "upload" and "view-templates" pages.  Previously the page would start to load and then throw an Access Control Error.  These changes now short circuit the page load.
=> fix: Permissions on Admin pages

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/DeliveryOptionEmail.tsx
Fixes error when trying to access Responses page when delivery option is set to Email
1. Go to unpublished form
2. Change delivery settings to email
3. Go to Responses page
4. The responses page should show that you have email delivery enabled.
=> fix: Email Delivery Component was mistakenly async

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/provider/TreeRefProvider.tsx
fixes: https://github.com/cds-snc/platform-forms-client/issues/3918
Fixes issue where the right panel should open when clicking to add a rule from a group node.
https://github.com/cds-snc/platform-forms-client/assets/62242/247827da-2468-4794-bc9f-08c74c2a8130
=> fix: add toggle right panel from logic view nodes

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx
Update to use name vs section title
=> chore: use section name for logic view

lib/hooks/form-builder/useHandleAdd.tsx, lib/hooks/form-builder/useIsWithin.tsx
Fixes issue where element panel menus overlap when using add element button
=> fix: overlapping element menus

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelActions.tsx
Small adjustment to move add element button down on non laptop views
=> chore: update spacing for add buttons on smaller screens

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/confirm/ConfirmDeleteSectionDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/confirm/ConfirmMoveSectionDialog.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3996
Adds translation strings for 
1) Deleting a page from the Tree View
2) Confirm moving a page when custom rules are set
For this go to logic page --- add some custom rules to a page
Go to Tree View and attempt to move that page
=> chore: add translations for dialogs

lib/store/useTemplateStore.tsx
See: https://github.com/cds-snc/platform-forms-client/issues/4007
Adjusts initialization code for groups when a form is imported without a groups layout property. 
Import the attached form which has no groups or group layout with the grouping feature on.
[my-form.json](https://github.com/user-attachments/files/16264914/my-form.json)
Note that the elements should end up under the Start page.
=> fix: Import with groups

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, lib/store/useTemplateStore.tsx
File for testing - has no groups property
[v2-accessibility-feedback-template-gc-forms-2023-07-21-1 (1).json](https://github.com/user-attachments/files/16268218/v2-accessibility-feedback-template-gc-forms-2023-07-21-1.1.json)
=> fix: remove initial initializeGroups on default form

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, components/clientComponents/globals/Header/Header.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Adds a toggable banner for campaigns/alerts that can be easily customized.
Closes #3849 
To test:
-> Open app!~ Hooray.
To edit:
-> i18n/translations/en/common.json // i18n/translations/fr/common.json -> "campaignBanner".
To enable/disable.
^ as above, just swap the enabled setting.
Alert tweaks the position of the "Form Setup" right panel to accomdate.
=> feat: Campaign Banner

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx
Fixes issue where start page wasn't receiving the updated translation name.
See: https://github.com/cds-snc/platform-forms-client/issues/4018
Noting the start group is unique as it's name gets setup when the template is created given we need a place for store existing form elements.
In this case we can replace the name when we're creating nodes for the logic view.
=> fix: update start page name for logic view

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx
This fixes and issue where the ` onFocusItem` event does not trigger.
This adds an additional check under `onExpandItem` to ensure the correct active group is set. 
Fix: https://github.com/cds-snc/platform-forms-client/issues/4027
=> fix: adds additional check / set for active group 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SectionTitle.tsx
The issue was when both the page language and the form language match, the language would default to English. So a user with a French page language and a French form would receive English as the language and the app would set the English field even though the French field was active.
To solve this I set the default (if page language equals form language) to the form language.
Follow the steps in #4040
=> fix: Updates sectionTitle to use form lang as default vs English

__fixtures__/sections-out-of-order.json, i18n/translations/en/form-builder.json, i18n/translations/fr/common.json, i18n/translations/fr/form-builder.json
Small content tweaks to clean up the conditional logic feature to match guidance:
- In French, switching `Page de révision` to `Page récapitulative`.
- In English and French, clarifying the action of turning a page into an `Exit page`.
=> Clearer terminology around exit pages and review page

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Edit.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalFormRules.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalRules.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBodyRoot.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBodySub.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SelectedElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/Options.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Closes #3976 
Passes the formId across the application to be able to route to the logic view - so just a quick test to make sure options don't return "undefined" in the URL at the top.
To test:
-> Open or Create a form.
-> Add a question that can have options.
-> Click an option to show "add rules"
-> Click the "add rules", and then click the "Have a complex form? Try branching instead +"
Double check the form has all the stuff you had, and the URL matches. eg: "en/form-builder/0000/edit" vs "en/form-builder/undefined/edit"
=> feat: Add Link to Logic View in Options Modal

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx
Closes #4067
To test simply open a publishable form and resize the window. It should no longer push the left hand bar off weirdly, instead only doing so when it hits mobile widths and then pushes it down as per previously.
=> fix: Add a max width to the warning alert for logic publish

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, components/clientComponents/globals/SkipLinkReusable.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
- Carrying through change in terminology of "pages" throughout the app
- Having "questions" as a logical subset of "pages" instead of the reverse, to clarify the structure of objects
- Not introducing "questions" as a concept unnecessarily --> form element
- Ensuring tab menu is plural for pages, translations, branching // pages, traductions, embranchements
- Update the "rules" modal title to be more concise for dynamic fields
- Distinguish between question "rules" or "parameters" for questions in the "More" modal to avoid confusion
- Decipher "display rules" (hide/show based on X) and branching rules (go to page Y based on Z)
- Differentiate left edit zone from right panel configuration for non-sighted users and help non-sighted users navigate
- Change "autoflow" in French to …
=> Update product strings to clarify conditional logic features and align with guidance

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx
Closes #4028
To test:
-> Open Form, Go to Translations!~
"Start" Page Title should no longer appear, as it is not editable in the first place.
=> fix: Remove the uneditable group section.

i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Elise found a few product copy issues while translating the Guidance articles.
https://docs.google.com/spreadsheets/d/1bhcNoEFnvHL7k-UUAjAndIMsLqNXcQnZySlvxb1Z8T0/edit?gid=1844769255#gid=1844769255
- Clarifying legacy concepts
- Fixing typos
- Ensuring consistency in what is active/passive
- Making autoflow clear/concise where possible
=> chore: Improve French content, fix typos and improve clarity of concepts

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx
Updates the next action selector to use the current language for the review page label.
=> fix: Use language property for review page label 

package.json
Just makes "dev" default not turbo, and gives a turbo option as well.
Turbo seems to cause issues with the auth module sometimes.
=> chore: * Disable turbo for default dev, add turbo command for those that want.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx
Routes to the privacy policy and "start" group when clicking the Privacy Policy Link on the Publish page. Also does the same for Form Title. Routes to the "end" group and confirmation message for that.
Closes #4026
=> fix : Route to the start group on moving from publish page via "Privacy" Link

__fixtures__/testDataWithGroups.json, __fixtures__/testDataWithGroupsLayout.json, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, components/clientComponents/forms/Form/Form.tsx, components/clientComponents/forms/NextButton/NextButton.tsx, lib/utils/form-builder/showReviewPage.ts, lib/vitests/formHasGroups.test.ts, lib/vitests/showReviewPage.test.ts
This feature/fix updates the Preview and Forms-Forms to only show a Review page if a form has multiple pages (groups).
I tested by checking there was *no* Review page on a single-page form in Preview and published in a Forms-form.
Then also checking there was a Review page on a multi-page form in Preview and published in a Forms-form.
For example:
https://github.com/user-attachments/assets/db09531a-8a24-4ee1-94a1-44a55b03c482
=> fix: shows Review page and related for multi-group forms

components/clientComponents/forms/Form/Form.tsx, lib/formContext.ts
Adds conditional input history to the forms-forms. 
This adda the logic from group history and show-hide to only include the data that follows a user's branching path.
**_High Risk PR as this touches forms-forms (how a user submits data)_**
The main things to test are that nothing obvious is broken around form submissions. Also test that the correct data is submitted. See the below video for an example.
Also test that old forms work as they previously did. So a review page should not be displayed when submitting and submissions continue working as previously.
https://github.com/user-attachments/assets/9a994947-7d0f-4f20-8781-0e836c93bc0d
=> feat: Conditional Input History - Forms-form

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/useUpdateGroupLayout.ts
Update `groupsLayout` when deleting a group (page).
Previously, when you deleted a page, the `groupsLayout` would not update.
You would also end up in a strange view where no page was selected, so the editor view was a blank/empty page.
We have an `updateGroupsLayout()` hook that is helpful in this regard, but it relies on the layout of the Tree itself. So we have to force the Tree to update before calling it. We can do this by setting a selected/expanded item in the tree.
To achieve this, we need to:
- find the previous page (default to Start)
- `setSelected(previousPage)`
- `setExpanded(previousPage)` - actually triggers the Tree refresh
- `setId(previousPage)` - so we don't have a blank/empty page in the editor
- `updateGroupsLayout()`
=> (fix): Update groupsLayout when deleting a group

lib/integration/freshdesk.ts
- Added 5 seconds timeout to the Freshdesk API call. While investigating on the recent fuzzy attack we discovered that the API call to Freshdesk was missing a simple timeout. It will prevent server actions from being blocked because of an unresponsive API server.
=> chore: add timeout to Freshdesk API call

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts
Closes #4146
Test JSON file:
[testing-the-high-risk-pr-2024-08-06.json](https://github.com/user-attachments/files/16512709/testing-the-high-risk-pr-2024-08-06.json)
To test:
-> Import
-> Click Test Form
-> Fill it Out to an End that can Submit
-> Submit
-> Check responses tab.
-> Validate order matches.
=> Fix: Add Group Ordering to response download.

.github/workflows/delete-ecs-task-defs.yml
Update the task definition cleanup workflow so that it only deletes `form-viewer` task definitions.
- https://github.com/cds-snc/platform-forms-client/issues/4128
=> fix: only delete form viewer task definitions

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts
Adds a check for if a form is legacy and has no groups to resort to the old layout for downloading responses.
=> fix: * Add a check for legacy forms to use layout object instead.

lib/validation/fileValidationClientSide.tsx
If there are multiple inputs in a repeating set, and not all of them are fileInputs, loop over the answers and pull only the fileInputs.
=> fix: Handle repeatingSets that include more than just fileInputs

i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Small section where we refer to rules instead of branches, text doesn't make a lot of sense:
When clicking on the page flow icon in branching, already have branches applied to the page, get this message,
"This page has branching applied to options
Remove the branches to create a simple page to page connection"
=> fix: content - clarify limitations with reordering pages if branching is applied

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/parseRequestData.ts, lib/tests/validation/fileValidationServerSide.test.ts, lib/validation/fileValidationServerSide.tsx
Related to https://gcdigital.slack.com/archives/C05G766KW49/p1724164024537339?thread_ts=1724163474.356029&cid=C05G766KW49
- Reworked file validation error types to be able to know whether the given file extension or the one that results from the detected MIME type is invalid
=> refactor: rework file validation error types

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/BackButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, components/clientComponents/forms/BackButtonGroup/BackButtonGroup.tsx, components/clientComponents/forms/Form/Form.tsx, components/clientComponents/forms/NextButton/NextButton.tsx, components/clientComponents/forms/Review/Review.tsx, lib/client/clientHelpers.ts
Adds focus header behavior for forms with lengthy pages. Focussing the group header (H2) navigates the page to the top and also announces the change (heading title) for AT users.
Create a form with a few pages that have a lot of form elements. I found adding a few address component sets helpful for this. Then try navigating back and forth through the form. For each page navigation, the focus should start at the top of the form.
=> fix: Adds focus heading behavior for forms with pages (groups)

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateCustomizeSet.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Adds inputs to translate screen for dynamic row properties.
=> chore: Translate dynamic row props

prisma/migrations/20240912193038_create_invitations_table/migration.sql, prisma/schema.prisma
In preparation for PR #4231 
Adds an Invitations prisma model and migration
=> chore: Add Invitation model and migration

app/(gcforms)/[locale]/layout.tsx, components/clientComponents/globals/ClientContexts.tsx, lib/cache/flags.ts, lib/cache/types.ts, lib/hooks/useFeatureFlags.tsx
Moves flags to standalone file to avoid issue with Server functions / components
=> chore: Move types for flags

app/api/notify-callback/route.ts
closes https://github.com/cds-snc/platform-forms-client/issues/2214 (see comments for more information)
- Adds `technical-failure` status (from GCNotify callback) to the list of statuses we should not try to reprocess submission for
=> feat: treat technical-failure as permanent when receiving callback from GCNotify

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, lib/hooks/form-builder/useHandleAdd.tsx, lib/store/types.ts, lib/store/useTemplateStore.tsx, lib/utils/form-builder/getPath.ts
Updates to fix issues caused by using `indexes` vs `ids`.
- Fixes issue with moving up / down after the parent has been re-indexed.
- Fixes focus issues 
- Re-focuses sub element when an item is moved up / down
- Focus sub-element when adding an item
**Before**
When moving a parent up or down the sub-elements would try to use the wrong parent index and in turn the button action wouldn't do anything.
Example:
https://github.com/user-attachments/assets/b8a02ecf-682e-4cf5-a243-6dd68d64f2b2
=> fix: Repeating set sub element panel actions

.github/workflows/staging-build-push-container.yml
Update the Staging ECR push workflow to allow the generate SBOM step to fail.  This step is intermittently failing because the public Trivy Docker image that contains the vulnerability database is being rate limited.
SRE is working on setting up a dedicated ECR for CDS projects to fix this rate limiting in the future.
Expect the generate SBOM step to no longer fail the Staging Docker image build/push workflow.
n/a
=> fix: allow generate SBOM step to fail

app/(gcforms)/[locale]/(support)/contact/components/client/ContactForm.tsx, app/(gcforms)/[locale]/(support)/support/components/client/SupportForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/account-created/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/account-deactivated/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/login/components/client/LoginForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/components/client/MFAForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/register/components/client/RegistrationForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/InitiateResetForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/PasswordResetForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/client/QuestionChallengeForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/setup-security-questions/components/client/SecurityQuestionsForm.tsx, app/(gcforms)/[locale]/(user authentication)/layout.tsx, app/(gcforms)/[locale]/(user authentication)/profile/components/client/EditSecurityQuestionModal.tsx, app/(language selection)/page.tsx
Updates support forms , auth (login etc...) to use GCDS styles.
=> chore: update various form components with updated GCDS styles

components/clientComponents/forms/Form/Form.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Partial fix for #4362 
Adds an improved error message for server-side file validation errors.
The problem with this solution is that it just throws a generic error at the top of the form with no link/association to the input that caused the problem, as a normal validation error would do.
A future PR should attempt to address this shortfall.
=> Improved error message for server-side file validation errors

components/clientComponents/globals/Header/FileName.tsx
Fixes minor issue with Filename input styling.
| <img width="682" alt="Screenshot 2024-10-09 at 2 56 03 PM" src="https://github.com/user-attachments/assets/a5674123-8e4d-47a9-9c43-50ade39bda53"> | <img width="611" alt="fixed" src="https://github.com/user-attachments/assets/c55607c1-a7b8-4b2d-a8c7-a192c7bea097">
|
=> chore: fix margin for filename input

lib/hooks/useCustomEvent.tsx
Adds a customEvent hook for use as a pub/sub implementation across the app.
Intent is to provide an easy way of communicating across components, ie a Button and a Dialog component.
See the MoreDialog as an example of a problem in this regard.
The Dialog and Button are wrapped together and must be inserted into the app code together. This becomes problematic when you have many dialogs on the screen - you end up with many duplicate components, and you get potential for css/style bleed as the dialog becomes wrapped in whatever context the button needs to be visible.
This pub/sub hook will enable splitting the button and dialog components.
The button can appear many times on the screen.
A single dialog can be inserted at a higher/common level and listens for a custom event to toggle open.
The …
=> chore: Add customEvent hook for pub/sub pattern

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/Option.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOption.tsx, components/clientComponents/globals/Buttons/themes.ts
Just a bit of cleanup to make it easier to work with Button icon theme
=> chore: Remove gray bg from Button icon theme and only apply selectively

.github/workflows/docker-vulnerability-scan.yml, .github/workflows/staging-build-push-container.yml
Update the Docker scan actions to use a self-hosted Trivy vulnerability database. This is being done to address the rate limiting of the publicly hosted database.
After merge, expect the generate SBOM and docker scan actions to no longer intermittently fail with rate limiting errors.
n/a
- https://github.com/cds-snc/platform-core-services/issues/597
=> fix: use CDS Trivy vulnerability database

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/Address.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/Attestation.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/Contact.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/DropDown.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/FirstMiddleLastName.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/Name.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/Number.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/TextArea.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/TextField.tsx
Follow-up fix related to gcds-styles - updated example components in the ElementDialog
=> fix: ElementDialog example component styles

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/ClosedMessage.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, next-env.d.ts
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4411
Add validation to closed message.
=> chore:  validate closed message

components/clientComponents/forms/AddressComplete/utils.ts
Fixes part of #4430 , it can be closed and #4417 used for the other part.
Essentially this fix makes it so if a country only provides a single language for it's addresses it doesn't try to force it to grab ENG/FRE entries, instead taking the only option available.
=> Fix: countries with single language only for international addresses.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, components/clientComponents/forms/ClosingNotice/ClosingNotice.tsx, lib/utils/date/utcToEst.vitest.ts, package.json, vitest.config.mts
- Adds closing notice to preview
- Adds tests
- Renames from Notice to ClosingNotice
<hr>
- 👉  Updates vitest config to allow test files to be co-located with the Component
=> chore: Update closing notice

components/clientComponents/forms/AddressComplete/ManagedCombobox.tsx
Closes #4313
Dropdown will now close when new address is set instead of staying open because a new addresscomplete lookup occured.
=> fix: Unstuck AddressComplete Dropdown

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/ApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/Dialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/api/components/ApiKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/api/components/DeleteKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/api/page.tsx
Update API key generation step to happen when the user presses download after agreeing.
=> chore: Move key generation to inside modal / download 

components/clientComponents/forms/AddressComplete/utils.ts
Closes #4452
Issue was the RegEx was not returning correctly for certain addresses causing it to perform a normal search instead of a search by ID.
=> fix: Update Regex for Nested Addresses to Match More Addressess

package.json
Removes the yup package. We dropped it in favor of Valibot some time ago.
=> chore: Removes the yup package

components/clientComponents/forms/Form/Form.tsx
Fixes #4478 
A previous fix (#4374) caused all errors from the serverAction to be caught as FileValidation errors.
This will specifically catch those and render appropriately, and let everything else fall through to a generic Server error.
=> chore: FileValidation error vs Server error

components/clientComponents/forms/AddressComplete/ManagedCombobox.tsx
If the ManagedCombobox component is not active filtering elements, don't force the combobox open on selecting an element. (Basically, the combobox needs to be forced open if it's actively being filtered by the AddressComplete API, but if it's not, it uses the old behavior and shouldn't be forced open.)
Closes #4455
=> fix : AddressComplete Country Select Stuck

components/clientComponents/forms/Review/Review.tsx
Updates review page start title to use the correct language. Previously a check was done on whether the group was undefined, that was the "flag" for whether it was a start group or not. The check was updated to look at the group Id instead.
Load up a group form. Switch the language to French. The Review page Start group should now be in French (the remaining group titles should be unchanged).
EXPECTED
=> fix: Updates the review page start title 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx
Fixes an issue where in certain circumstances the Save changes action on Form management will fail silently and not save the form.
=> fix: Save closed message on Form management

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, components/clientComponents/forms/AddressComplete/AddressComplete.tsx, components/clientComponents/forms/AddressComplete/types.ts, components/clientComponents/forms/Review/Review.tsx, i18n/translations/en/form-builder.json, i18n/translations/en/review.json, i18n/translations/fr/form-builder.json, i18n/translations/fr/review.json
Closes #4507
Toggles between labels if the Address is international or not.
=> fix: Add Canada vs International Labels for Address Complete

lib/templates.ts
Add an ability check before the prisma call to ensure the user is an owner of the form.
=> fix: Ensure user is owner on form when setting closing form date and message

components/clientComponents/forms/AddressComplete/ManagedCombobox.tsx
Closes #4504 
Downshift has a 'bug'/'designflaw'/'intended'? way of behaving that causes a double render when you handle the input value of the component yourself. There's a small and simple work around in simply calling the onChange yourself through the event handler instead of letting Downshift do it all.
=> fix: Users Cursor stuck in AddressComplete Input

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx
Fixes a bug where the save date function was not first converting the date to an ISO date which caused a date miss-match in prisma etc
Here is the related [production thread chat](https://app.slack.com/client/T2G2S06PM/C05G766KW49?selected_team_id=T2G2S06PM).
Closes #4559
=> fix: Updates save date with correct date conversion

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts
=> fix: Grab the right language for AddressComplete SubLabels (Responses)

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/page.tsx, lib/serviceAccount.ts
Don't throw on unsaved forms.
Should quiet this noise
=> chore: Check for unsaved forms when checking for API key

bin/pr-review-entrypoint.sh
The current `cut` command in the pr-review-entrypoint.sh was using `=` as a delimiter.  As more and more of our secrets become complex or handle base64 encoding this delimiter can appear naturally and wreck havoc on the secret parsing.
To fix the `cut` command has been replaced with the same scripting parsing command that is used in pr-review-sync-vars.sh that leverages the first instance of `=` instead of parsing the whole string into multiple sections.
Blind faith
=> fix: PR Review Environment not handling complex secrets

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/ClientContainer.tsx, components/clientComponents/globals/Alert/Alert.cy.tsx, components/clientComponents/globals/Alert/Alert.tsx, components/clientComponents/globals/HealthCheckBox/HealthCheckBox.tsx, i18n/translations/en/form-builder-responses.json, i18n/translations/fr/form-builder-responses.json
Adds a component to create system check status boxes
Example usage:
```jsx
<HealthCheckBox.Success titleKey="systemHealth.contactSupport.title">
<HealthCheckBox.Text i18nKey="systemHealth.contactSupport.description" />
</HealthCheckBox.Success>
```
=> chore: System health component

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts
Adds a form ID to logs to help track errors downloading submissions.
=> chore: add form id to log for form not found

utils/createdAtVaultConfItemsMigration/.env_example, utils/createdAtVaultConfItemsMigration/main.ts, utils/createdAtVaultConfItemsMigration/package.json, utils/createdAtVaultConfItemsMigration/tsconfig.json, yarn.lock
Part 2 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Create migration script to add `CreatedAt` property to existing Vault `CONF#` items. The value assigned to that property is taken from the original associated `NAME#` item.
=> chore: add migration script to add CreatedAt property to Vault CONF# items

lib/integration/notifyConnector.ts
Adjusts Axios timeout to 5 secs for Notify call this now matches the current Reliability queue setting.
=> chore: update Notify timeout setting

utils/statusCreatedAtMigration/.env_example, utils/statusCreatedAtMigration/main.ts, utils/statusCreatedAtMigration/package.json, utils/statusCreatedAtMigration/tsconfig.json, yarn.lock
Part 4 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Adds or updates `Status#CreatedAt` property (using the existing Status and CreatedAt properties from the same item) in NAME# items.
=> chore: add migration script to add StatusCreatedAt property to Vault NAME# items

components/clientComponents/forms/Form/Form.tsx
This update fixes an error where the Jaws screen reader would re-announce a form label on every input change. The ticket mentioned a text input but the same error was on a textarea, search dropdown,.. This error did not happen on the Support form so I suspect it is Form-Forms only. Also this behaviour only happens in Windows+Jaws and not in MacOS+VoiceOver or Windows+NVDA.
The fix removes a top level live-region on the main form element. I suspect this was placed there as a temporary fix and later noted that it should be removed. The tricky part with this is it is difficult to say whether any dynamic updates on a form still depend on this live-region.  My intuition would be none but this should be tested.
_Note: A deeper problem is why a text input change is causing a DOM update on every …
=> fix: update to stop Jaws screen reader re-announcing the form label on every input change

components/clientComponents/forms/FormGroup/FormGroup.tsx
A radio/checkbox group does not need a tabindex on a container, this can cause unpredictable behavior in assistive technologies.
=> fix: for Radio button / group unexpected behaviour

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/ApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ApiKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/FormOwnership.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/ManageApiKey.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/ManageForm.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/ThrottlingRate.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/page.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Adds admin screen to allow generating an Api key for a live form.
Noting this will show for user with Manage all forms + a published form.
=> chore: Add ability for gc forms admin to switch to api mode for live form

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/ManageForm.tsx, package.json
Previously the Throttle UI was showing up whether a form had an API key or not, only a check was done for ownership managing. This adds a check for an API key before showing the Throttle UI.
Create a new form and go to the settings screen and click on the "Form Management" screen. The Throttle UI should not be displayed.
Next click on the "Response Delivery" tab and click "Receive responses via API" and then click "Generate API Key". Now go to the "Form Management" screen. The Throttle UI should be shown.
=> chore: Adds a check that an api key exists before showing throttle ui

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ApiDocNotes.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/DeleteKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/DeleteKeyToChangeOptionsNote.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/dialogs/ResponseDeliveryHelpDialogApiWithApi.tsx
Updates Response delivery view to show note about deleting key before changing an option.
=> chore: Hide other delivery options when API key generated

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOptions.tsx
In certain circumstances (ie when form elements have been re-ordered), the elIndex can get out of sync and becomes a bad way of finding specific elements. This is part of an ongoing Tech Debt exercise to replace indexes by ID lookups.
=> fix: Switch SubOption to retrieve element by id

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/DeleteApiKeyDialog/DeleteApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, lib/hooks/useCustomEvent.tsx
Fixes #4731
Fixes #4724
https://github.com/user-attachments/assets/a5aaec7e-4e16-4a5f-a36b-0951aa9cd82c
👉  Note -- 20 was too much using 10
Fixes [#4737](https://github.com/cds-snc/platform-forms-client/issues/4737)
=> chore: update setting page styling for API 

components/clientComponents/forms/Form/Form.tsx, lib/formBuilder.tsx
This is a followup PR to the previous fix #4704. The form live-region is added back and to stop the "noisy" form labels, a live=off is added around them.
TL/DR: Should work fine.
This appears to work well with screen readers. It is generally a best practice to have any attributes like live-regions rendered as close as possible to the original rendered HTML. This is because if the DOM becomes complex, there is a good chance an AT will ignore any dynamic changes in the DOM unless told about them. But in this case, a live-region is added on the form element that is in the original-ish HTML. So the AT is paying attention to this element. A few children below are the dynamically added show-hide elements with labels that have an overriding live=off.  AT should pick these up and AT are getting …
=> fix: followup to screen reader re-announcing the form label on every input change

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOption.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOptions.tsx, lib/store/types.ts, lib/store/useTemplateStore.tsx
Updates Sub options to use id vs index for adding / removing sub elements
Seeing an issue on staging ---doesn't seem to happen on local dev but was really slow.
=> chore: update add / remove sub choices for repeating sets

components/clientComponents/globals/card/Card.tsx, components/serverComponents/globals/card/Card.tsx
Adds a background colour <img width="22" alt="Screenshot 2024-12-04 at 2 10 01 PM" src="https://github.com/user-attachments/assets/aaff3148-d2ec-403f-a57c-b4c082697cd6"> for the Card components
=> chore: Update card background colour

components/clientComponents/globals/HealthCheckBox/HealthCheckBox.tsx
Centers "paragraph" text for status boxes.
=> chore: update alignment for text in Status Boxes

app/(gcforms)/[locale]/(support)/support/components/client/SupportForm.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Adds API option to support form behind a feature flag.
Version 1 update of the support form #4375 
It works 
Ensure you test with the flag on /off
=> chore: Add api option to support form

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/ApiKeyDialog.tsx
Update to ensure the template store is sync'd properly when creating an API key (save to vault).
Fixes https://github.com/cds-snc/platform-forms-client/issues/4793
- Start with email delivery
- Change to API - generate a key
- Delete the API key (should be vault at this point)
- View responses page 
- Responses should show as "the vault"
https://github.com/user-attachments/assets/3a4a1cca-c817-4df5-b521-fb6da042fb85
=> chore: Reset delivery option when creating API key

lib/store/initStore.ts, lib/store/useTemplateStore.tsx
Moves init store out to a standalone function to start to cut down the size of `useTemplateStore`.
=> chore: move store setup to standalone function

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/MoreDialog/MoreDialog.tsx, lib/store/types.ts, lib/store/useTemplateStore.tsx
Updates template store to include path helper.
The template store already has access to the `elements` -- with this update we can let the template store do the work and avoid pulling the elements into place where we just use them for a lookup.
=> chore: add path helper to template store

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Fixes small issue currently on staging server where the Delivery option was trying to be updated when saving a form purpose.
This PR splits the saves 1 for the Delivery option and 1 for the form purpose.
=> chore: break out save for purpose option

lib/templates.ts
Fixes a  🐔 before 🥚 bug.
Was previously trying to delete draft responses after the published status had been changed on the template.
Now deletes draft responses before updating the status on the template.
=> fix: On form publish delete draft responses before switching to Published status

lib/integration/notifyConnector.ts
- Rewords misleading error message in `notifyConnector.ts`.
=> chore: reword misleading error message in notifyConnector.ts

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/DownloadTable.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/Pagination.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/Responses.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/tests/DownloadTable.test.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/SystemStatus/ProblemsReported.tsx, lib/types/index.ts, lib/types/retrieval-types.ts, lib/vault.ts
- Fixes pagination feature so that it uses the right `lastEvaluatedKey` for the DynamoDB query when listing submissions 
- Use a form that has enough responses so that the pagination feature is available (2 pages is good enough)
- While on page 1 navigate to page 2
- See if it works (on Staging it just returns an error message)
=> fix: pagination feature is broken due to integration of new StatusCreatedAt Global Secondary Index

app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, app/api/templates/[formID]/route.ts, lib/templates.ts, lib/tests/templates.test.ts
removeDeliveryOption was attempting to use a prisma.update to remove the deliveryOption record when changing to API mode. This was not working as expected, and was throwing an incorrect TemplateAlreadyPublishedError.
Modified to:
- Initial `isPublished` check and throw exception as published templates cannot be changed
- Delete any DeliveryOptions for template
=> chore: Replace update with simple delete for removeDeliveryOption

.devcontainer/Dockerfile, Dockerfile, Dockerfile.pr
Pinning to Node Alpine 3.20 until Prisma 6.1.0 is released and implemented.
Fixes SSL location issue between Prisma and  Node Alpine > 3.20
=> Fix: Pin to Node Alpine 3.20

components/clientComponents/forms/Form/Form.tsx
When a Server Action is not found due to newer deployment, the server action returns `undefined`
=> chore: Catch failed to find server action result

i18n/translations/en/admin-settings.json, i18n/translations/fr/admin-settings.json
Based on feedback:
https://gcdigital.slack.com/archives/C074DJX9ETX/p1734542232241549
https://github.com/cds-snc/forms-api/blob/ca13d7545d64bfc471ce9d3f079b4efdd32912e4/src/config.ts#L45
- Low rate limit = 500 requests / minute (default)
- High rate limit = 1000 requests / minute (increased by admin)
- Specified end = could be up to 12 weeks
- Indefinitely
- EN: https://cds-snc.github.io/forms-api/monitoring/
- FR: https://cds-snc.github.io/forms-api/surveiller/
=> chore: Clarify what the API rate limit increase means in admin

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx
If a user creates a new form then navigates to Settings before saving, this `checkKeyExists` call will throw an exception at the privilege check.
No need to retrieve, as the form is new.
=> chore: Don't try to retrieve the API key on new forms

components/clientComponents/forms/MultipleChoiceGroup/MultipleChoiceGroup.tsx, lib/formBuilder.tsx
Originally for any checkbox or radio, a description was repeated for each one. This fix removes the repeated description. This works because the description is linked from the container fieldset to the description using an aria-describedby. The original code did not break WCAG but was bad UX for screen reader users.
Note:
**This doesn't solve the other problem of very verbose page/group loads**. We need to think of a strategy how to announce adding dynamic groups of stuff to a form. I suspect we could update the page title and use the live region announce component or similar. But then we'd want to remove the main live=polite on the main form element and that would require a lot of testing and thinking about edge cases e.g. show-hide rules.
Look at the source code for a checkbox or radio …
=> fix: Updates how a description is added to a checkbox or radio

.github/workflows/cypress.yml
Updates workflow file to cache `.next/cache` dir
https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
=> chore: update cypress workflow to cache next

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/[id]/manage-forms/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/[id]/manage-permissions/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/flags/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/settings/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/settings/components/server/ManageSettingForm.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ManageFormAccessDialog/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, app/(gcforms)/[locale]/(form administration)/forms/actions.ts, app/(gcforms)/[locale]/(form administration)/forms/components/Invitations/actions.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts, app/(gcforms)/[locale]/(support)/contact/actions.ts, app/(gcforms)/[locale]/(support)/support/actions.ts, app/(gcforms)/[locale]/(support)/unlock-publishing/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/login/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/register/action.ts, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/action.ts, app/(gcforms)/[locale]/(user authentication)/auth/setup-security-questions/actions.ts, app/(gcforms)/[locale]/(user authentication)/components/action.ts, app/(gcforms)/[locale]/(user authentication)/profile/action.ts, i18n/index.ts, lib/actions/checkIfClosed.ts, lib/cache/throttlingCache.ts
Part of https://github.com/cds-snc/platform-forms-client/issues/4774
- Adds a delimitation in server actions files to have a clear boundary between public facing functions and internal ones
- Deletes unused server actions
- Removes duplication of privilege checks for some server actions
- Fixes issue with error message due to missing `serverTranslation` call
=> chore: review server actions

components/clientComponents/forms/AddressComplete/AddressComplete.tsx
Previously the default country (Canada) was not being set for both "Canada only" and not "Canada only" addresses. For "Canada only" addresses, the country was never set. For not "Canada only" countries, the country would be null until the user interacted with the country drop down.
The fix sets the default to Canada for both cases.
Create a form with pages and on a page add an address that is "Canada only" and another address that is not "Canada only" (default).
Try filling in the form by not setting any values and go to the Review page. The country should be set to Canada for both cases.
Try filling the form again and for the not "Canada only" country dropdown, select a country other than Canada. This country should show on the Review page.
=> fix: Fixes default country for an address

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/AddressComplete.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/lexical-editor/plugins/FloatingLinkEditorPlugin/index.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/Description.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/Title.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/Translate.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/loading.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/CheckAll.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/Dialogs/DownloadDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/Pagination.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/loading.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/loading.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/tag-input/Tags.tsx, app/(gcforms)/[locale]/(support)/contact/components/client/ContactForm.tsx, app/(gcforms)/[locale]/(support)/unlock-publishing/components/client/UnlockPublishingForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/components/client/MFAForm.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/resend/components/client/ReVerify.tsx, app/(gcforms)/[locale]/(user authentication)/profile/components/server/Icon.tsx, components/clientComponents/admin/LeftNav/NavLink.tsx, components/clientComponents/forms/AddressComplete/AddressComplete.tsx, components/clientComponents/globals/Alert/Alert.cy.tsx, components/clientComponents/globals/Alert/Alert.tsx, components/clientComponents/globals/Buttons/LeftNav.tsx, components/clientComponents/globals/Buttons/SubmitButton.tsx, components/clientComponents/globals/Header/Header.tsx, eslint.config.mjs
Turns `tailwindcss/enforces-shorthand` "on"
Updates existing files to use shorthand.
i.e. 
use
```
size-14 ✅ 
```
not
```
h-14 w-14 ❌ 
```
=> chore: Turn on lint rule for tailwind enforces-shorthand

app/api/id/[form]/submission/unprocessed/route.ts
Given we're now using Next 15... found an issue where we didn't await the `props.params?.form` in the  unprocessed api route.
Was throwing 
```
Error: Route "/api/id/[form]/submission/unprocessed" used `params.form`. `params` should be awaited before using its properties. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```
=> fix: await for param for unprocessed api route

lib/formContext.ts
Update to ensure when emptying out values the emptied value remains the same type i.e. array or string of the incoming value.
- Create 2 checkbox lists 
- Make the second one a show hide based on one of the values in the first.
- Toggle the second list to show and set a value
- Toggle the second list to hide ... in this case the value should be "empty" when sending the payload as it's hidden,
- Ensure the value sent is an array for the checkbox type
=> bug: ensure array is sent for checkbox elements when they are in a hidden state

lib/invitations/inviteUserByEmail.ts, lib/invitations/tests/invitations.test.ts
inviteUserByEmail was using getOrigin() to retrieve the base path for links. This function is (recently became?) async and needs to be awaited.
=> fix: Fix invitation email links

components/clientComponents/forms/FormattedDate/FormattedDate.tsx, components/clientComponents/forms/FormattedDate/utils.ts
Fixes #4958 
1900 was chosen as the minimum year for date validation purposes, fairly arbitrarily. This lowers it to 1000.
=> fix: Date component- set lower threshold for year validation

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx
Somewhere between Edit -> EditWithGroups transition, a bit of code that handles preventing access to Edit on published forms was lost.
=> fix: Prevent access to Edit on Published forms

lib/store/helpers/add/duplicateElement.ts
When duplicating a dynamicRow element, the subElements were not being renumbered to match the parentId, so we'd end up with duplicate IDs in the subElements array. This sometimes caused forms to blow up while editing due to the way we look up form elements by their id.
=> fix: Renumber subElements on duplicate

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/PreviewNavigation.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SaveButton.tsx
When uploading a form file, the user is directed to the Preview page.
This page does not autosave, so if the user then went straight to Settings and tried to make a change, it would throw an error.
This PR just adds the SaveButton to the Preview page so that an autosave is triggered when navigating away.
=> fix: Save on preview to prevent error on uploaded form file

components/clientComponents/forms/Combobox/Combobox.tsx
The searchable list (Combobox) component has a bit of strange behaviour. We do not validate the input value against values in the list. The only validation that is run is if it is set as a Required input. But when that is the case, this odd bit of behaviour can be observed:
- Create a form with searchable drop-down (add some values the list)
- Set the input as required
- Go to Preview and test:
- if you type something not in the list and just hit submit -> validation (required) error
- if you start typing and click a matching item then hit submit -> success
- if you start typing and click a matching item then modify or add more and hit submit -> success
- if you start typing, click a matching item, then delete the text and enter something different -> success
This PR makes a change so …
=> fix: Allow free text in searchable list input

components/clientComponents/forms/ErrorListItem/ErrorListMessage.tsx
| <img width="653" alt="image" src="https://github.com/user-attachments/assets/fc981e63-4523-42f7-8fb8-fc58e486b702" /> | <img width="657" alt="image" src="https://github.com/user-attachments/assets/b07edda1-0a93-4822-9467-1506539e1ed4" /> |
=> fix: Unescape question in validation message

components/clientComponents/globals/Header/LanguageToggle.tsx, components/serverComponents/globals/LanguageToggle.tsx
The locale prop is not supported for the app router - this PR removes it.
```
The `locale` prop is not supported in `next/link` while using the `app` router. Read more about app router internalization: https://nextjs.org/docs/app/building-your-application/routing/internationalization
```
Console warning:
=> chore: remove locale prop for Language toggle

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ManageFormAccessDialog/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/NavigationTabs.tsx, i18n/translations/en/manage-form-access.json, i18n/translations/fr/manage-form-access.json
Removes the Manage access button on Draft forms
Also catches at the Server Action layer and prevents submission.
=> fix: Prevent invitations to draft forms

lib/integration/prismaConnector.ts
Changes the logMessage level of handled Prisma errors so that they do not appear in Slack. The Prisma error is still captured in CloudWatch logs to be referred against for troubleshooting if required.
Current:
Proposed:
=> chore: Silence handled Prisma errors

lib/responseDownloadFormats/csv/index.ts
This is a variant to the fix proposed in https://github.com/cds-snc/platform-forms-client/pull/5054
- Reverts a temporary patch applied to CSV output for form responses
- Removes unnecessary use of `sortByGroups` (because it is already sorted before) when ordering elements for CSV generation
- Filters out `richText` elements before generating CSVs
=> fix: sort layout and filter out richtext when generating CSVs

prisma/migrations/20250130165334_create_template_user_view/migration.sql
A required addition to handle an issue caused by AWS Services not allowing uppercase column names, and Prisma using uppercase column names for Many-To-Many relation tables.
=> chore: Add the migration to produce a perm template to user view object.

lib/templates.ts
- Dumps JSON config in log when detected as invalid
=> chore: dump form JSON config in log when detected as invalid

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/layout.tsx
Add `0000` checks for settings and publish when a user is logged in and has an unsaved form.
Folks shouldn't be able to visit these pages direct or in an unsaved state.
=> chore: use not found page for 0000

components/clientComponents/forms/Review/FormElements/AddressComplete/AddressComplete.tsx, lib/i18nHelpers.ts
Modify AddressComplete review component to use formItem.values like other component types.
Modify AddressComplete to use customTranslate
Modify customTranslate to support review translations.
=> chore: AddressComplete use form values and customTranslate

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/actions.ts
When downloading responses, we map repeatingSet answers onto questions by using the index of the answer in the answer array to find the question. The problem arises when there is a richText element in the repeatingSet question array, there is no corresponding element in the answer array, so indexes are out of sync.
The fix is to filter out richText elements from the repeatingSet question array before using the answer index to find the question.
Also added a bit of checking/logging in case the indexes get out of sync for some other reason.
=> fix: Filter out richText elements from repeatingSet arrays when mapping responses/questions

app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts
Adds a feature flag for hCaptcha. Also adds a feature flag for the form timer so we can disable/enable it depending on whether hCaptcha is on.
=> feat: adds feature flags for hCaptcha

components/clientComponents/forms/FormattedDate/FormattedDate.tsx
Fixes #5123 
If a user enters a date into a non-required date input, then clears the input - the validation was failing because the stored date wasn't being cleared.
=> fix: Don't run date validation if entry has been cleared

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/lexical-editor/Editor.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/lexical-editor/plugins/TabControlPlugin.tsx
Enables using Tab/Shift-Tab to Indent/Outdent lists in the RichText editor.
Seems this was [fixed once before](https://github.com/cds-snc/platform-forms-client/pull/1235) but broke somewhere along the way.
Had to add a custom plugin to capture the Tab key and use it to fire an indent/outdent command
=> fix: enable using Tab key to indent/outdent lists in RichText editor

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx
Fixes #4530 
Improvements to the branching flowchart:
- Stops re-drawing every time a node is selected
- Saves viewport changes a user makes while using (zoom, pan)
- Restores viewport after a branching change is made
This should help keep users oriented while using the flow view. Note that there are a few situations that can cause either a blank screen or user disorientation:
- If zoomed all the way in on a node towards the top or bottom of a complex tree, clicking on "Reset to linear flow", the user could end up on a blank screen as the nodes are regrouped off screen
- Similarly if zoomed in on a specific node and making a change that moves that node offscreen
To help in these situations, the "fit view" button has been enabled (below the zoom +/- buttons)
=> fix: Restore user-set viewport on init

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/RichText.tsx
=> chore: remove invalid "hint text" from richtext fields in translate page.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/lexical-editor/ToolTip.tsx, styles/_form-builder.scss
=> chore: Push the z-Index for tooltips up to the top, so they aren't cut off.

app/api/notify-callback/route.ts
- Adds `status_description` information from GC Notify to our callback warning log (https://documentation.notification.canada.ca/en/callbacks.html#message-delivery-receipts)
=> feat: add status description to GC Notify callback warning log

components/clientComponents/globals/Header/ShareDropdown.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/2783
Fixes share menu issue for `fr` when a form doesn't have a name.
=> fix: fix wrapping for share menu when no name

components/clientComponents/forms/Form/Form.tsx, components/clientComponents/forms/Form/PrimaryFormButtons.tsx
Adds focusable to form error block
Missed one instance in previous pr for isFormClosed helper
=> chore: Add focusable to form error block

Dockerfile
- Removes extra space in Dockerfile CMD instruction
=> fix: extra space in Dockerfile CMD instruction

Dockerfile.rainbow
- Copies all /src directories and files for rainbow container since the base container already has standalone build output in its /src directory
=> fix: copy all /src directories and files for rainbow container since the base container already has standalone build output in its /src directory

.github/workflows/rainbow-deployment/action.yml, .github/workflows/staging-deploy.yml
- Re-enables Rainbow deployment
- Fixes issue with `--logging-config` command option that was misplaced
- Modifies the way we build we detect the latest release for which we need a Rainbow lambda
=> chore: re enable Rainbow deployment

.github/workflows/rainbow-deployment/action.yml
- Fixes Rainbow deployment script to select ECR image identifier that comes just before the latest one
=> fix: rainbow deployment script should select ECR image identifier that comes just before the latest one

.github/workflows/staging-rainbow-cleanup.yml
- Fixes detection of Rainbow deployments on scheduled cleanup
=> fix: detection of rainbow deployments with a priority greater than 2

.github/workflows/staging-deploy.yml
- Uses new Github secrets for Rainbow deployments
=> chore: use new Github secrets for Rainbow deployments

lib/types/form-builder-types.ts
Adds a comment with a link to the client error codes doc. More info is in the [google doc](https://docs.google.com/document/d/1Za03rcuC9YUDtNXuNyHAwUi7wtp-vgVFxBx0Oy2JZz8/edit?tab=t.0).
If this approach becomes difficult to maintain in the future, instead of a google doc a script could also generate a README or similar. But since the main end user of the error code info will be support, a Google doc may be more accessible than a github link to a README.
=> chore: Adds a comment with a link to the client error codes doc

components/clientComponents/globals/FormCaptcha/CaptchaFail.tsx
Updates captcha fail page secondary title to H2
Previous
Updated
Probably the easiest way would be to programmatically force the fail page to show in Forms.tsx
=> fix: Updates captcha fail page secondary title to H2

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/FormOwnership.tsx, i18n/translations/en/admin-forms.json, i18n/translations/fr/manage-form-access.json
Fixes #5363 
EN: "Manage ownership"
FR: "Gérer les propriétaires"
https://gcdigital.slack.com/archives/C01GFD150MC/p1744030538019659
=> fix: missing translation in admin settings

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/conditionals/ConditionalIndicator.tsx
Currently for a conditional element, the question id displayed in the form-builder ui is a little confusing. It stems back to when forms had questions listed by order, and that order index could be used to reference it. To help find the related element id (to reference the related element shown/hidden), a hidden debug data var was added.
Here is the related ticket:
https://cds-snc.freshdesk.com/a/tickets/22017
For example:
=> chore: adds debug info for the element id

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/ManageForm.tsx
Save and Resume component was left out of the early return block for non-admin users.
=> chore: Add SaveAndResume to non admin

instrumentation.ts, lib/cache/privilegeCache.ts, lib/flags/initialization.ts
- (tentative) Fixes production `Connection is closed` errors
- Removes the "disconnect from Redis" function call
Not yet sure why we have not seen it before in Staging (probably because the traffic was not high enough) but since it happens in both the ECS task and Rainbow lambdas it must have something to do with the NextJS server being built in standalone mode + what we changed to be able to achieve this (aka flag initialization).
I was able to confirm that the error we keep getting in Production is thrown by the `ioredis` library that we use to interact with Redis.
Here is the specific code that produces those errors:
```
export declare const CONNECTION_CLOSED_ERROR_MSG = "Connection is closed.";
===
function close() {
self.setStatus("end");
self.flushQueue(new …
```
=> fix: remove Redis disconnect function call (tentative fix)

components/clientComponents/forms/Form/PrimaryFormButtons.tsx, components/clientComponents/forms/Form/SubmitButton.tsx
Currently when on a single page form with a required question, the loader would spin indefinitely. The form could still be submitted and this only impacted single page forms.
The fix adds check for validation errors to submit button spinner.
1. Open a single page form with at least one required field. 
2. Fill in no fields and submit the form. The submit button should be in the original state (not spinning).
3. Fill in the required fields and submit the form. The submit button should show a spinner while loading. (using dev tools network throttling helps with this step)
Example single page form:
https://5qrq7fxzeuwjq55z2co2lfu4bq0qedxt.lambda-url.ca-central-1.on.aws/en/id/cm9cvyajz0000l40c9138xgn8
https://github.com/user-attachments/assets/77feccc4-c37a-4ad7-82be-5c4846442fcd
Example …
=> fix: adds check for validation errors to submit button loader

components/clientComponents/globals/Footer.tsx, components/serverComponents/globals/Footer.tsx, components/serverComponents/globals/Version.tsx
- Removes `async` from version --- not needed.
- Updates style when version is on a front facing form
For front facing -- single line
=> chore: version # updates

package.json, yarn.lock
Package update for markdown to jsx
https://github.com/quantizor/markdown-to-jsx/releases
=> chore: update markdown to jsx

packages/editor/CHANGELOG.md, packages/editor/package.json, packages/editor/src/Editor.tsx, packages/editor/src/plugins/MaxLengthPlugin/index.tsx, packages/editor/src/plugins/MaxLengthPlugin/styles.css, packages/editor/src/styles.css
Only show the contentLength/maxLength indicator when contentLength reaches 80% of maxLength
=> chore: Set contentLength/maxLength indicator threshold for display

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/RichTextEditor.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/RichTextLocked.tsx
The new Editor component has a prop called maxLength. This just adds it to the RichTextEditor wrapping component so it can be set and passed through.
=> chore: Add prop to RichTextEditor to enable maxLength

app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts
- Fixes broken GC Forms website link in Share form email content
=> fix: GC Forms website link is broken in share form email content

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/RichTextLocked.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx
Adds code to toggle details / summary open when clicked from the Tree View
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4121
https://github.com/user-attachments/assets/e4e402c9-8bcf-4c71-91b8-bed1bc64d8e2
=> fix: toggle into, policy and cofirmation open from TreeView

package.json, yarn.lock
Package bump
https://github.com/vercel/next.js/releases/tag/v15.3.2
Note using `npx @next/codemod@canary upgrade latest` for these bumps
=> chore: Update to Next 15.3.2

app/(gcforms)/[locale]/(form filler)/id/[...props]/clientSide.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, components/clientComponents/globals/DateModified.tsx
Adds CSS to hide date modified on confirmation screen
=> chore: hide date modified on confirmation page

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/FormOwnerSettings.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/notifications/Notifications.tsx
Fixes an issue with permissions and notifications toggling. Previously a user with less permissions would not see the notifications UI. Now they should.
Also when going from email to vault delivery and back again will reflect the correct notifications toggle state. Previously when going email to vault delivery the toggle notifications toggle would not update to on.
=> fix: fixes issue with permissions and notifications toggling

lib/tests/validation/validation.test.js, lib/validation/validation.tsx
Adds invcanada.ca as a valid gov email to the signup flow. [Support Slack Thread](https://gcdigital.slack.com/archives/C03T4FAE9FV/p1747412034849619)
Adding a test account with invcanada.ca should pass the signup validation.
=> chore: adds invcanada as a valid gov email

lib/hooks/form-builder/useHandleAdd.tsx
Weird bug. Try this on the main branch:
- Start a new form
- Add a Number input
- Add a Short Answer
The Short Answer inherits the validation rule of the Number input, and now every time you add a Short Answer you end up with a Number input instead.
- Reload your browser
- Add a Short Answer
The Short Answer gets added fine now.
This PR fixes that weird bug.
=> fix: Addding textField sometimes adds Number field

components/clientComponents/forms/ResumeForm/ErrorLoading.tsx, components/clientComponents/forms/ResumeForm/Upload.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Adds a more specific error message for mis-matched files.
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5479
Covers 
```
FR-01
FR-02
FR-03
FR-04
```
```
FR-07
```
=> chore: handle file mis-match issues for save progress 

components/clientComponents/forms/FileInput/FileInput.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5649
Moves cancel button out of hidden span tag.
=> fix: Cancelling a file upload shows a dev tools a11y warning

packages/connectors/package.json, packages/connectors/src/gc-notify-connector.ts
- Adds a way to differentiate between timeouts and other type of errors when no Axios response is available once we have sent a request to GC Notify. This is a change included in the GC Notify connector package.
Note: even though we followed some documentation from Axios (https://axios-http.com/docs/handling_errors). There is only one true way of making sure we have a proper timeout (in the sense of the API not responding within the expected interval).
=> chore: differentiate between timeouts and other type of errors when no Axios response is available in our GC Notify connector

app/(gcforms)/[locale]/(support)/contact/components/client/ContactForm.tsx
Fixes issue where a negative margin was causing the paragraph text to bump up against the Contact us heading 
Issue:
=> chore: fix heading spacing for contact us

app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/client/FilterButton.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/client/UserSearch.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/server/NavigationFrame.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/server/UsersList.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/page.tsx, i18n/translations/en/admin-users.json, i18n/translations/fr/admin-users.json, package.json, yarn.lock
Adds search to accounts page
Note: This also handles extended search i.e. or queries see https://www.fusejs.io/examples.html#extended-search
Also fixed up the filter nav styling
**Before:**
=> chore: Add search to accounts page

package.json, yarn.lock
https://github.com/downshift-js/downshift/releases/tag/v9.0.9
=> chore: update downshift to 9.0.9

app/(gcforms)/[locale]/(user authentication)/components/client/forms/Alert.tsx, components/clientComponents/forms/Alert/Alert.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5662
Remove top margin for alerts
=> fix:  alert heading margin

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/ExitUrl.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, lib/types/form-builder-types.ts
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5030
Adds missing exit page url to the translate page
=> chore: Add exit page url to translate page

package.json, styles/_dropdown.scss, yarn.lock
Updates select css to remove deprecated token for select font
https://github.com/cds-snc/gcds-tokens/pull/449
Ref for CSS:
https://github.com/cds-snc/gcds-components/blob/main/packages/web/src/components/gcds-select/gcds-select.css
=> chore: update GCDS package

lib/fileInput/fileGroupsToFileTypes.ts, lib/hooks/form-builder/useHandleAdd.tsx
Update to add default file types that will be accepted when a file input is inserted via the builder.
This update ensures the "more" modal has default file types to start which allows the UI to display all types as checked by default.
https://github.com/user-attachments/assets/e1157708-d914-40c1-a913-1b609cc898b8
In the previous code undefined or an empty array would default to  "all" but would not be reflected as "checked" in the builder.
=> chore: Add default file types to json for file inputs 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/MoreDialog/Description.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/MoreDialog/Question.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/utils.ts, components/clientComponents/forms/FileInput/FileInput.tsx, components/clientComponents/forms/FileInput/ResetButton.tsx, lib/formBuilder.tsx
Partial fixes for https://github.com/cds-snc/platform-forms-client/issues/5760
- 1 Forms > Settings > Response Delivery > Add API Key
Once the key is created the page updates with the key Id. Is it announced? The attached video shows what I hear. The previous attempt though I thought I heard the key number announced? Either way once the key number is announced, it may help to prefix it with “key” or something similar so it’s clear what it is.
- 2 Forms > Edit Page > Add form Element > File Upload
In the preview window, the Chose File button has a few undefined labels. See image.
- 4  Forms > Edit Page > Add form Element > More
File input and label id does not match. See image.
- 5 Forms > Edit Page > Add form Element > More
Hint text input and label missing relationship. See image.
- 6 …
=> fix: a11y updates for file input

packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/form-types.ts
Updates form types to add strict value  in support of extracted from https://github.com/cds-snc/platform-forms-client/pull/5572
=> chore: add strict value to form types

components/clientComponents/forms/SaveAndResume/MobileDrawer.tsx, components/clientComponents/forms/SaveAndResume/SaveAndResume.tsx
Fixes issue where confirm dialog / mobile drawer were unnecessarily performing renders and data look ups (i.e. when in an invisible state)
Updates Save and resume dialog + mobile navigation to prevent unnecessary renders 
Fixes ticket: 23654
=> fix: save progress minimize renders for non-visible-components

components/clientComponents/forms/CurrentGroupSelector/Menu.tsx
Update to handle overflow scrolling --- when there's lots of groups
=> chore: fix styling when lots of items

lib/validation/validation.tsx
Add gg.ca to the valid email domains so users from the OSGG can register.
=> chore: add gg to the valid email domain list

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/BackButton.tsx, components/clientComponents/forms/BackButtonGroup/BackButtonGroup.tsx, lib/hooks/useGCFormContext.tsx
Subsequent to #5779 
Refactors the BackButton and BackButtonGroup to use the new visibleGroups algorithm to find the last group vs groupHistory.
=> chore: Refactor BackButton to use new visible pages function

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/MoreDialog/DynamicRowOptions.tsx, constants.ts, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, lib/hooks/form-builder/useHandleAdd.tsx
Closes: https://github.com/cds-snc/platform-forms-client/issues/5964
- Updates the form builder to ensure a max row count is set when adding a repeating set.
- Defaults max row count for repeating sets to 25
Notes: 
In a future PR we might want to update front facing form to ensure a max rows property is set regardless of the template value.  This would handle cases where the property isn't set and also legacy templates.
This PR doesn't alter existing templates i.e. if a form already has created a repeating set.
https://github.com/user-attachments/assets/12ab84df-8af1-4697-a68d-984b452ea75f
=> chore: add max row count for repeating sets

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/actions.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/normalizeFormResponses.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/tests/fixtures/date.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/tests/fixtures/kitchenSink.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/tests/fixtures/missingInputs.ts, app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/tests/fixtures/repeatingSet.ts, packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/form-response-types.ts
**Breaking change!**
Deserialize formattedDate objects on the way into the Vault.
Previously, a formattedDate would be submitted to the Vault as a serialized object. For example:
```
{
"1": "{\"DD\":13,\"MM\":8,\"YYYY\":2025}",
"2": "Test",
"4": "{\"YYYY\":2025,\"MM\":8,\"DD\":13}"
}
```
This would require a consumer pulling data from the vault (API, Response Downloads) to parse the string back into an object to access its properties.
This PR deserializes that object on the way into the Vault in the new `normalizeFormResponses` function. So now, a response with dates will look like this:
```
{
"1": {
"DD": 13,
"MM": 8,
"YYYY": 2025
},
"2": "Test",
"4": {
"YYYY": 2025,
"MM": 8,
"DD": 13
}
}
```
Since this changes the format or shape of the data being stored in the Vault, it is considered a …
=> feat!: Deserialize dates when normalizing data

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/client/fileUploader.ts
The "file-type" package explicitly notes that it cannot detect the mime-type of text files. (eg: CSV, TXT, SVG) 
As we allow CSV and TXT, it removes the mime-check for these extensions.
Fixes #6014
=> * Remove mime-check for txt files. (csv/txt)

package.json, yarn.lock
https://github.com/vercel/next.js/releases/tag/v15.5.0
Note using following for these bumps
```
npx @next/codemod@canary upgrade latest
```
Dev tools now has a detachable panel
https://github.com/user-attachments/assets/f28aaf8b-b2d0-45c4-9b09-b804401e6dfc
=> chore: Update next.js to 15.5.0

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ApiKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/dialogs/ResponseDeliveryHelpDialogApiWithApi.tsx, next-env.d.ts
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5787
- Update not disable the classification select and allow saving when an api key exists.
- Remove save button 
- Update save callback name
- Auto-save when classification is changed
https://github.com/user-attachments/assets/0e8d1a45-3c45-47e5-98e7-a4ad8122a8b5
=> fix: allow save security attribute when api key exists

package.json, yarn.lock
Update to the latest version of the `@cdssnc/sanitize-pii` module so that error code timestamps are no longer partially redacted and incorrectly identified as phone numbers.
- https://github.com/cds-snc/sanitize-pii/pull/38
- https://github.com/cds-snc/platform-core-services/issues/809
1. After deploy, create a support request that includes the [Forms error code format](https://docs.google.com/document/d/1Za03rcuC9YUDtNXuNyHAwUi7wtp-vgVFxBx0Oy2JZz8).
2. Expect that the timestamp portion of the error code is not redacted.
None.
=> fix: redaction of timestamps in support tickets

scripts/pr-review-sync-vars.sh, scripts/set-rainbow-lambda-env-vars.sh
fixes the index of the container definition used for rainbox and preview environments.
=> fix: Use correct container definition for rainbow and preview

scripts/set-rainbow-lambda-env-vars.sh
Need to reference old index for container definition until latest task definition is live.
=> fix: Update set-rainbow-lambda-env-vars.sh

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, components/clientComponents/globals/Buttons/CircleButton.tsx
Update to ensure id exists when panel is in an open or a closed state.
Fixes: #6041
https://github.com/user-attachments/assets/0e598809-512e-418f-8255-fa5d2a8727c7
=> fix: skip to right panel

components/clientComponents/forms/DynamicRow/DynamicRow.tsx
Fixes issue where when using a repeating set inputs we're warning about "controlled or uncontrolled input element"
Problem: New rows were initialized with empty objects {}, causing form fields to start with undefined values and transition to "", triggering warnings. 
Updated code ensure empty strings to avoid undefined values
Console error:
https://github.com/user-attachments/assets/e2c73e50-847f-4025-9d2f-004e6defd12c
The issue also shows up as an error in the Jest test output 
<hr>
> A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: …
=> fix: dynamic row - controlled or uncontrolled input element 

lib/middleware/schemas/templates.schema.json
Found and fixed some cases where `En` was `EN` and `Fr` was `FR`
=> fix: schema typos

package.json, prisma.config.ts
Update to use config file for prisma vs package.json 
```bash
warn The configuration property `package.json#prisma` is deprecated and will be removed in Prisma 7. Please migrate to a Prisma config file (e.g., `prisma.config.ts`).
For more information, see: https://pris.ly/prisma-config
```
=> chore: add prisma config file
