.github/workflows/staging-build-push-container.yml, .github/workflows/staging-deploy.yml, config/infrastructure/aws/README.md, config/infrastructure/aws/appspec-template.json
This GitHub workflow will build the node app and automatically deploy it to the AWS staging environment.
=> Auto build node app and deploy to Staging

README.md
=> Fix Demo URL

.env.public
This PR modifies the public environment variables to add the Notify template ID's and Email to variables.
---
=> Change send to email

.eslintrc.js, .prettierrc.js, .vscode/launch.json, components/globals/Base.js, package.json, public/static/locales/fr/welcome.json
This PR fixes the JSON formatting for the `fr` locale that is required for the welcome page.  
It also fixes the favicon icon which is not a `png` but an `ico`.  This was causing Next.js to try and fetch the default page with `favicon.png` as a param.
=> Small fixes for welcome page

forms/award.json, forms/baggage.json, forms/lostfishgear.json, pages/index.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
=> 3 new forms

pages/index.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
> - Added the esdc link to the home page
> - Fixed up an error in the fr locale json structure
=> added esdc link to welcome page

forms/callback.json
adding the Service Canada callback form to the forms folder
=> add callback form json file

pages/index.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
- cleaned elements in both welcome.json
- added link to callback form
- added h2 title in index.js for Form List
=> added links to callback form, added h2 form header

forms/securityclearanceform.json
Security clearance form
> 1-3 sentence description of the changed you're proposing, including a link to a GitHub Issue # or Trello card if applicable.
---
> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le problème (« issue ») GitHub ou la fiche Trello, le cas échéant.
> Sequential steps (1., 2., 3., ...) that describe how to test this change. This will help a developer test things out without too much detective work. Also, include any environmental setup steps that aren't in the normal README steps and/or any time-based elements that this requires.
---
> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la modification. Elles aideront les développeurs à faire des tests sans avoir à jouer au détective. Veuillez aussi inclure toutes les …
=> Security Clearance Form 

forms/notifycontact.json, pages/index.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
added new links to new forms on index.js
added titles to welcome.json
added notifycontact form
=> Addnewlinks

forms/callback.json
changed radiobutton element for question 1 to radio element
=> fixed radio button to radio

.gitignore, components/forms/Forms.js, forms/esdc.json, forms/notifycontact.json, lib/formBuilder.tsx, styles/_forms.scss
- Added the file-upload field to the ESDC form JSON (UI only)
- Updated some styles, ongoing work with Design
=> Tweak styles

forms/notifycontact.json
Demo for Transport Safety Board is tomorrow (Wednesday) at 11am EST
=> Updating email to mine

forms/award.json
- Entered 2 plaintext elements for section titles
- removed the titles in each affected elements
=> added section titles and removed titles in fields

forms/esdc_accessibility_fund_FOR-DEMO.json
adding first draft of ESDC accessibility grant form
missing dynamic add-field blocks, etc
cc @srtalbot
=> Add ESDC new form JSON file

components/forms/Forms.js, forms/award.json, forms/baggage.json, forms/callback.json, forms/contact.json, forms/esdc.json, forms/esdc_accessibility_fund_FOR-DEMO.json, forms/intake.json, forms/lostfishgear.json, forms/securityclearanceform.json, lib/formBuilder.tsx, styles/_base.scss, styles/_forms.scss, tailwind.config.js
- The referrerUrl for the confirmation page now supports providing both EN & FR links.
- Added basic styles for headings in plainText
- Removed some `required` fields in sample JSON forms
=> Add En/Fr referrers and remove required fields

forms/esdc_accessibility_fund_FOR-DEMO.json
changes via cayce and hillary to polish up the form and include missing sections, fixed copy, etc 
FOR DEMO
=> update copy and add attestation

pages/index.js, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
Added link to welcome page to the G&C's accessibility form.
=> Add link to welcome page

forms/esdc_accessibility_fund_FOR-DEMO.json
- Copy edit: "does your organization owe any amounts of to the Government of Canada"
- Remove any required fields, except: Attestation check boxes (E.g., I have the capacity and the authority to..."
=> small fixes for demo form

forms/esdc_accessibility_fund_FOR-DEMO.json, public/static/locales/en/welcome.json, public/static/locales/fr/welcome.json
=> file input

.dockerignore
This PR makes several additions to Docker Ignore file.  Mainly to ignore the local prebuilt static JS  and ensure a clean build on every image.
=> Update docker ignore to force rebuild

forms/esdc_accessibility_fund_FOR-DEMO.json
=> remove "placeholder" text title for demo

components/forms/DynamicRow/DynamicRow.tsx, components/forms/Forms.js, lib/formBuilder.tsx, lib/markdown.tsx, public/static/locales/en/confirmation.json
This PR:
- fixes COPY on the confirmation page:
- Fixes a missing key on the component <Heading>
- Parses the object sent to the Submit API to filter out any unwanted props in the Form json.
=> Fixes Warnings and Filters out Props sent to Submit API

.github/workflows/jest.yml
Creates action to run Jest Tests and report annotations and coverage.
=> Create jest action for testing

.vscode/launch.json, README.md, components/forms/Forms.js, lib/dataLayer.tsx, lib/formBuilder.tsx, lib/logger.tsx, lib/markdown.tsx, package.json, pages/_app.js, pages/api/log.js, pages/api/submit.js, public/static/locales/en/common.json, public/static/locales/fr/common.json, tailwind.config.js, yarn.lock
This PR introduces a logging system that leverages `pino` that allows logs to be output to stdout in a JSON format for easier ingestion to log readers in the future.
The logging module under `./lib/logger` outputs two functions.  
1. A `logMessage` function that allows for developer controlled logging of specific events
2. A 'logger' function that wraps any other function with a `try` and `catch` block which preserves the original typescript signature of the wrapped function.
An environment variable can be introduced "DEBUG" to change the level of logging output to "debug" instead of "info".  All logs output in "development" and "debug" mode are 'prettified' for easier reading by the developer.
- Server Side Rendered (SSR) traffic including path and parameters in the request
- Pages on …
=> Logging on Server and Client

components/forms/DynamicRow/DynamicRow.tsx, styles/_forms.scss, tailwind.config.js
> I've set up some temp styles until I've cleaned up the rest of the styles from being imported from `forms-storybook` -> `forms-client`
https://recordit.co/gulPzp27bw
=> add a row style update

forms/contact.json, forms/notifycontact.json, forms/platform_intake.json, pages/index.js
- Fixed checkbox issue on intake form
- change publish status to ensure demo forms show up on sandbox page and platform intake on index page
=> Set forms status to display on different pages

lib/logger.tsx, pages/api/log.js
This PR fixes early Monday morning brain fog...
Do not mutate the message on client side but instead on the log API once received.
=> Logger fix

forms/award.json, forms/forests_early.json, forms/forests_future.json, pages/api/log.js, pages/index.js, pages/sandbox.js, styles/_base.scss, styles/_forms.scss
Excellence form was created a while ago and wasn't finished. It could benefit from some of the new components we've created and a content update.
- ### Adding section headers to the form
- > Since we now have section headers we might as well be using them to chunk out this form
- ### Updating some questions
- > Some questions were left out of this form while waiting for conditional logic to be implemented, but since we decided to go with section headers temporarily we can now finish the rest of the form.
- ### Adding Team Nomination section
- > Some sections were left out of this form while waiting for conditional logic to be implemented, but since we decided to go with section headers temporarily we can now finish the rest of the form.
- ### Adding Dynamic Row Component to team section
- …
=> Excellence Award 2020 form updated for demo

components/forms/FormGroup/FormGroup.tsx, lib/formBuilder.tsx
This PR replaces the label element on a field-set with the proper legend element.  The legend element is also styled like a field input label.
=> A11y fix form group

forms/TSB-contact.json
- update title to match TSB page
=> TSB form updates

forms/platform_intake.json, public/static/locales/en/confirmation.json, public/static/locales/fr/common.json, public/static/locales/fr/confirmation.json, styles/_base.scss, styles/_forms.scss
> - Changed to Leanne's
> - Added "A team member will email you shortly" / "Un membre de notre équipe vous contactera par courriel sous peu"
> - Forgot to add the small screen media query to make `<p>`'s `w-full`
> - Mario provided french copy for the small english updates I made
=> Intake update 2

public/static/locales/en/common.json
changed privacy and terms and condition link in footer to point to the english page
=> fixed priv and terms link en

forms/TSB-contact.json
Updating email routing to mine while we're still demoing
=> Updating form email routing

styles/_forms.scss
- Small tweaks to both
- A little hard to style based on the rich text component but added some small changes
=> Error styling + small rich text update

components/globals/Base.js, public/static/locales/en/common.json, public/static/locales/fr/common.json
A large majority of the identified a11y violations are due to a missing <title> element on all of our pages. See [this example](https://a11y-tools-query.herokuapp.com/reports/62f2ed6a09c423351c137d018583a5e3f052f8fee6b1530019a55f654f423062).
I've added a generic "GC Forms" or "GC Formulaires" title depending on the current language of the app.
We may want to customise this title per page / form down the line.
=> Add a generic page title to the base component <head>

pages/api/submit.js
This PR refactors the submission logic to simplify the handling of logic between the different environment.
- If production only send to lambda and return it's response
- if staging send to lambda but log the response and continue with notify preview
- if local development or heroku do not try to send to lambda and only return notify preview
=> refactor submission logic

forms/cfha.json
=> adding cfha form

forms/cfha.json
=> removed validation

pages/api/submit.js
This PR refactors the submit.js API endpoint to ensure that the response headers are only ever set once.  This was an issue given the async nature of the dependant functions and the unique circumstances of the staging environment sending to both Lambda and Notify.
=> Fix Erroring logic on submit.js API

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/platform_intake_spec.js, package.json, pages/id/[form].js, pages/id/builder-preview.js, pages/sandbox.js, pages/welcome-bienvenue.js, yarn.lock
I didn't see any documentation on nextjs' [10.1.0 page](https://nextjs.org/blog/next-10-1) about any breaking changes, and the app seems to work fine locally for me.
I also added `/id/` to form URLs in this PR as requested by @bryan-robitaille . So a form that was previously at `/20` is now at `/id/20`.
=> NextJS version upgrade and form URL modification

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/platform_intake_spec.js, package.json, pages/api/submit.js, pages/id/[form].js, pages/id/builder-preview.js, pages/sandbox.js, pages/welcome-bienvenue.js, styles/_base.scss, styles/_forms.scss, yarn.lock
> - Pull Request went stale with all the refactoring
> - Confirmation page styles
> - Sticky Footer
=> confirmation-styles + sticky footer

README.md
See:
https://trello.com/c/O883umdF/610-separate-storybook-packagejson-into-its-separate-folder
=> Remove npm references in readme

public/static/locales/en/common.json, public/static/locales/fr/common.json
- changed french translations to reflect english changes
- added phone number format in english validation 
-
=> french translations

cypress/integration/tsb_contact.spec.js, forms/TSB-contact.json
- adding back button on end page in EN and FR
- Updating cypress test
- Validated JSON
Note: Mario, I've seen us use "retour" before, can you confirm that is correct?
=> tbs-review4

components/containers/Dashboard/DataView.tsx, pages/admin/upload.js, pages/admin/view-templates.js, styles/_base.scss
- Wrapped the new upload and view pages in Auth (must be logged in to view).
- Some basic style cleanup of the view page to make it more readable with expand / collapse for the larger JSON blobs. This page is still very much WIP
Next Steps (for future PRs):
- Get a specific form
- Modify and Delete existing JSON blobs
=> Templates admin pages improvements

forms/DPI_intake.json
Creating the DPI intake form. 
Here's the original: https://docs.google.com/forms/d/e/1FAIpQLSfFvmwH_kAY4Xi30YglTDHRrNPRf-6TopL6Zv2XWvja-04h0g/viewform?vc=0&c=0&w=1&flr=0&fbzx=-7979797604105645072 
End-page content is taken from the platform intake form
Pulled FR content from other forms, but please review.
=> Creating DPI intake form

public/img/blue-checkmark.svg, public/img/blue-circle.svg, styles/_base.scss, styles/_forms.scss, styles/_header.scss, tailwind.config.js
I wasn't happy with some inconsistencies in the focus states for the forms components and submit button, but after some discussion with Eric and some feedback from Julianna I've made some updates with their help.
The changes are as follows:
- Links previously had a separate focus colour but have been updated along with the form inputs to have one darker shade of blue that I was previously using for active states in my previous PR briefly.
- Worried the colour switch alone won't be enough for visually impaired users
- The buttons have been updated to have a small solid white box shadow (in the case this button is ever applied to a darker background), followed by a 2 px blue outline to stand out more.
=> Focus feedback from Julianna and Eric

.github/workflows/codeql-analysis.yml
- This PR introduces GitHub's "[industry-leading static analysis engine](https://github.com/github/codeql-action)" to find security vulnerabilities
- File repurposed from [covid-alert-server](https://github.com/cds-snc/covid-alert-server/blob/master/.github/workflows/codeql-analysis.yml)
=> Introduce CodeQL action for security scanning

components/containers/DynamicForm/Settings.test.js, components/containers/DynamicForm/Settings.tsx, components/forms/Button/Button.tsx, components/forms/JsonUpload/JsonUpload.test.js, components/forms/JsonUpload/JsonUpload.tsx
It took me awhile to figure out how to properly mock the router but we got there.
This PR adds some basic tests for the new JSONUpload component, and for the new Settings Page. There's probably much more I could do, but most of the other components don't seem like they have much more than this, so I wasn't sure. Let me know if there's something I should write a test for.
Bryan already updated the datalayer tests so I don't think we need to add any there.
=> Add some tests for new components

components/containers/DynamicForm/Settings.tsx, components/forms/Button/Button.tsx, public/static/locales/en/admin-templates.json, public/static/locales/fr/admin-templates.json, styles/_base.scss, styles/_forms.scss, tailwind.config.js
Add a few style updates / tweaks:
- Delete button is red now on the settings page. I added a "destructive" version to the button. I pulled the colours from a figma file Nick shared with me in the last few weeks. This will likely need iteration in the future based on communication with design.
- Added some basic google translate translations for my template UI text. Please give feedback on things that should be changed!
=> Sandbox styles

.github/workflows/cypress.yml, .github/workflows/eslint.yml, .github/workflows/jest.yml
This PR ensures that the automated tests are run during both the PR as well as the merge.  If the tests were successful on the PR then they *should* also pass on the Merge however it's best to be safe rather then sorry.  This follows the same deployment process as Covid Alert Portal.
=> Add that tests also run on push to branches

.github/workflows/cypress.yml, .github/workflows/eslint.yml, .github/workflows/jest.yml, .github/workflows/prod-build-push-container.yml, .github/workflows/staging-build-push-container.yml, styles/_base.scss
Brings Sandbox up to date with Main branch.  
Fixes conflicts due to renaming of formMetadata to formConfig.
=> Merge main into Sandbox

CHANGELOG.md, pages/id/[form]/[[...step]].js
Remove tmp routing for future patch 1.0.1
Updated change log for unreleased change.
=> Remove temp routing for prod release

.github/ISSUE_TEMPLATE/go-live----form-title--.md
=> Update issue templates

README.md
Adds documentation on local DB setup and use.
Needs translation at some point.
=> Add database documentation (in english)

.github/ISSUE_TEMPLATE/onboarding-team-members.md
Added items referring to technical onboarding
=> Add items to developer onboarding issue template

pages/api/submit.tsx
This PR moves the submission file upload logic to after the Send to Reliability Queue flag is checked.
This ensures no files are uploaded if the form submission is not being sent to the submission Lambda.
=> move logic to check for reliability queue flag

.idea/prettier.xml, .storybook/main.js, package.json, yarn.lock
closes #411 
- upgraded storybooks to use webpack5 
- removed fallback for tls,dns,net and stream NodeJS libs
1. pull down changes
2. run `yarn storybook`
3. the storybooks application should be started on port 6006
N/A
N/A
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la …
=> fix: upgrade storybooks to use webpack5 to ignore polyfilling ioredis NodeJS dependencies

.husky/pre-commit, package.json, yarn.lock
closes #388 
Setup husky to lint and run tests as a pre-commit hook. Whenever something is committed... linting will be done first and then the unit tests run. 
1. pull down changes
2. run `yarn install`. This should run a postinstall script that sets up the pre-commit hook 
3. change a file and commit ( do not push to this branch )... you should see the pre-commit hook being run
N/A
N/A
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull …
=> chore: setup husky for repo

components/forms/Alert/Alert.tsx
closes #321 
One liner... change h3 to h2 on alert component n order to fix issue of skipped heading when alert is present
Same way you usually test UI changes.
N/A
N/A
This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :
langues officielles?
une baisse de la quantité de code couvert par les tests automatisés?
fonctionnalité existante?
que ça devrait être divisé en de plus petites demandes de tirage (« pull
requests ») afin de réduire le risque lié aux modifications?
modification de la politique de confidentialité?
préoccupations liées à la sécurité?
façon importante la performance?
risque d’utiliser des dépendances ajoutées? …
=> fix: change h3 to h2 heading

lib/integration/helpers.ts, lib/tests/helpers.test.js
An error when submitting a form:
`GET http://localhost:3000/_next/static/chunks/pages/id/79/confirmation.js net::ERR_ABORTED 404 (Not Found)
Uncaught (in promise) Error: Failed to load script: /_next/static/chunks/pages/id/79/confirmation.js
at HTMLScriptElement.script.onerror (route-loader.js:104)`
Tracked it down to an extra path being pushed to the router.
=> Remove extra path being pushed to the router.

CHANGELOG.md, pages/_document.js
Add's a required content security policy exception for Google Tag Manager that is required for Google Analytics to run.
No
=> add missing connect-src attribute.

documentation/Forms/FormViewer.stories.mdx
Updating a typo in the dynamic row syntax
| …
=> Dynamic row documentation update

.husky/pre-commit, lint-staged.config.js, package.json, yarn.lock
There is no issue created for this PR.
This changes the way husky handles the pre-commit script, only running `lint` on staged files. This allows for other files to be a "work-in-progress" on the developer's machine, that won't prevent a commit of a few files, if there is a lint error in a file that isn't being committed. It will also reduce the amount of time it takes to run lint pre-commit.
- run `yarn install` to add the new `lint-staged` package to your environment
- create a new branch to test this on your local machine
- Make a change that will cause a lint error to two files
- stage one of the files
- attempt to commit that file, the `lint-staged` command run by the husky pre-commit script will cause an error, preventing the file from being committed
- fix the error in the staged …
=> chore: Add `lint-staged` for pre-commit lint checks only on staged files.

CHANGELOG.md, package.json, pages/api/token/temporary.ts, tests/api/token/temporary.test.js, yarn.lock
closes #558 
PR sends an email through GC Notify when a temporary token is generated.
Using Postman:
- Add user to form (URL for request = http://localhost:3000/api/id/28/owners)
- Create main token (URL for request = http://localhost:3000/api/id/28/bearer)
- Create temporary token (URL for request = http://localhost:3000/api/token/temporary). Use forms-formulaires@cds-snc.ca in the payload as it is whitelisted on GC Notify.
You should have received an email containing the temporary token.
=> feat: send email when temporary token is generated

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/platform_intake_spec.js, cypress/integration/tsb_contact.spec.js, lib/middleware/httpRequestAllowed.ts, lib/middleware/jsonValidator.ts, lib/tests/jsonValidator.test.js, pages/api/id/[form]/owners.ts, pages/api/organisations.tsx, pages/api/templates.ts, pages/api/token/temporary.ts, tests/api/id/[form]/owners.test.js, tests/api/token/temporary.test.js, tests/templates.test.js
There is no issue for this PR. Some of the APIs were expecting the `body` to be sent as text, instead of JSON. This meant that the tests needed to call `JSON.stringify()` on the body, and that Postman requests needed to send the body as `Content-Type:text/plain`. 
To fix this, all APIs are now expecting the body to be sent as JSON.
All of the tests have been updated, and should pass; the only thing that changed was removing the `JSON.stringify()` part on the body.
Check any Postman requests for `Content-Type:application/json`, and they should work too. Sending `text/plain` should cause an error.
=> fix: request body JSON

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/platform_intake_spec.js, cypress/integration/tsb_contact.spec.js, lib/middleware/httpRequestAllowed.ts, lib/middleware/jsonValidator.ts, lib/tests/jsonValidator.test.js, pages/api/id/[form]/owners.ts, pages/api/organisations.tsx, pages/api/templates.ts, pages/api/token/temporary.ts, tests/api/id/[form]/owners.test.js, tests/api/token/temporary.test.js, tests/templates.test.js
Reverts cds-snc/platform-forms-client#591
There was an error that broke uploading JSON configs. Reverting this PR until that error is figured out.
=> Revert "fix: request body JSON"

lib/s3-upload.ts, pages/api/submit.ts
Please see greater detail about the initiative here https://github.com/cds-snc/forms-terraform/pull/166
This is a small PR to configure AWS SDKs mainly the S3Client and the Submission Lambda client to use local endpoints when specified as opposed to reaching out to AWS. This allows us to test a form submission end to end locally
Please see test instructions on the linked PR. This PR is mainly to allow platform-forms-client to work with the solution
N/A
=> feat: enable full local development by modifying AWS SDKs to use localstack

components/admin/JsonUpload/JsonUpload.tsx, components/containers/Admin/Organizations/CreateOrganization.tsx, components/containers/Admin/Organizations/OrganizationSettings.tsx, lib/integration/helpers.ts
No issue for this PR.
Changing the Axios default to allow a timeout of 60s for `production` environment, othewise no timeout. Without a timeout in the production environment, the system could stop responding to the client if there are any unexpected errors.
Run API calls against the files that have been changed.
It would be nice to set the value once within the app as a constant.
=> Change Axios timeout.

cypress/integration/accessibility.spec.js, cypress/integration/cds_intake.spec.js, cypress/integration/dynamic_rows.spec.js, cypress/integration/forms_functionality.spec.js, cypress/integration/platform_intake_spec.js, cypress/integration/tsb_contact.spec.js, tests/data/cdsIntakeTestForm.json, tests/data/dynamicRowsTestForm.json, tests/data/platformIntakeTestForm.json, tests/data/tsbContactTestForm.json
Modified the Cypress tests to use mocked JSON files that can be committed to the repo. This means that the tests don't rely on the data in the database.
Run the Cypress tests and they should all pass without issue.
=> test: Update Cypress tests to use mocked form files.

public/static/locales/en/common.json, public/static/locales/fr/common.json
Closes #629 
Updated the default JSON for `EN` and `FR`. These values can also be set / overridden in the form config JSON.
- Load the any page on the site, in either EN or FR. 
- Click the link and verify it goes to the correct page.
- Check the alt text.
=> fix: Update home page link.

styles/_forms.scss
Closes #630.
Also updated the `gc-file-input-upload-button` to have matching colours.
| 
| 
- Load a form that has a secondary button
- Hover over the button and observe the colour changes
=> fix: secondary button contrast

CHANGELOG.md, components/forms/RichText/RichText.tsx
closed #498 
context: [previous  PR](https://github.com/cds-snc/platform-forms-client/pull/601)
=> Clicking a link clears the form

.github/workflows/prod-build-push-container.yml, .github/workflows/staging-build-push-container.yml, Dockerfile
Fixes the missing Env variable required for the reCaptcha feature.
The browser side variable is static and is required at build time.  It will not be picked up in the server side process.
=> Add arg for recaptcha to docker and build stages

lib/integration/helpers.ts
- Fixed submission not working because of formID information not being passed properly to the lambda
=> fix: submission API not able to process form response

.env.example, CHANGELOG.md, lib/s3-upload.ts, package.json, pages/api/id/[form]/retrieval.ts, pages/api/notify-callback.ts, tests/api/notify-callbacks.test.js, yarn.lock
closes #242 
linked to https://github.com/cds-snc/forms-terraform/pull/186
based on https://docs.google.com/document/d/1XXtqmSeQXQRdklpz4FmpUdagKgr6new67633OsyHmzg (which will be updated shortly to reflect the final solution that was implemented)
- added new API path for GC Notify to call us back when a notification has failed to be delivered
Note:
- This PR adds a new environment variable `GC_NOTIFY_CALLBACK_BEARER_TOKEN`
- This PR replaces `LOCAL_S3_ENDPOINT` and `LOCAL_DYNAMODB_ENDPOINT` by `LOCAL_AWS_ENDPOINT` in the .env file
- It requires GC Notify callback to be enabled and properly set up using the portal. It has been done for staging using a specific token that has been saved in LastPass (Application Variables - Staging)
Warning:
- It looks like only one callback path can be set …
=> feat: add new API patch to plug GC Notify callback feature

CHANGELOG.md, components/forms/DynamicRow/DynamicRow.test.js, components/forms/DynamicRow/DynamicRow.tsx, lib/formBuilder.tsx, lib/middleware/schemas/templates.schema.json, lib/types.ts, public/static/locales/en/common.json, public/static/locales/fr/common.json, styles/_forms.scss
closes #528 
- Added a new `maxNumberOfRows` property in JSON template in order to configure DynamicRow component
- Redesigned DynamicRow component buttons
|<img width="763" alt="Screen Shot 2022-03-31 at 1 02 33 PM" src="https://user-images.githubusercontent.com/1763961/161110994-9686cb5b-e77e-4632-8838-bd1fd526d89e.png">|<img width="786" alt="Screen Shot 2022-03-31 at 2 16 43 PM" src="https://user-images.githubusercontent.com/1763961/161124222-9af919d4-5f8b-48c8-889c-e47f8244aaeb.png">|
https://forms-staging.cdssandbox.xyz/id/276 form in staging has been updated so that it includes the new …
=> feat: added new maxNumberOfRows property in JSON template for DynamicRow component configuration

.github/workflows/build-and-deploy-storybooks.yml, package.json
This PR is a remediation as a result of a incident.
This PR creates an action which will build and deploy storybooks for every PR and merge to main. The github bot will paste the storybooks link on every PR. This will resolve the incident as well as allow us to use storybooks in reviews
1. See if the link works
N/A
=> feat: build and deploy storybooks action

components/admin/JsonUpload/JsonUpload.tsx, lib/middleware/jsonValidator.ts, tests/api/id/[form]/retrieval.test.js
Closes #709 
In addition to displaying the error, I added the copy "JSON Validation Error: ", so it was clear where the error originated.
| 
| 
|
- Go to the admin section, and select a form to edit. 
- Upload a form that doesn't adhere to the JSON schema used for validation. For example, remove the required "_publishingStatus_".
- Upload the form.
- Observe that the error displayed is now specific to the JSON Validation.
=> Display specific error when validating the JSON config.

flag_initialization/index.js, migrations/index.js
- Fixed missing logger module in the database migration file as well as the flag initialization one
=> fix: missing logger module

components/admin/BearerRefresh/BearerRefresh.tsx, components/admin/FormAccess/FormAccess.tsx, components/admin/JsonUpload/JsonUpload.tsx, components/forms/Checkbox/Checkbox.tsx, components/forms/Description/Description.tsx, components/forms/Dropdown/Dropdown.tsx, components/forms/DynamicRow/DynamicRow.tsx, components/forms/FileInput/FileInput.tsx, components/forms/TextInput/TextInput.tsx, components/forms/TextPage/TextPage.tsx, lib/formBuilder.tsx, pages/admin/index.tsx, pages/admin/vault.tsx
Refactoring some code to remove unnecessary `null` in ternary operators, favouring instead the logical && operator as described here: https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator
This PR has no change in the behaviour of the code or display.
=> refactor: Remove unnecessary `null` in ternary operators.

CHANGELOG.md, components/forms/FileInput/FileInput.tsx, styles/_forms.scss
- redesigned file input button
|<img width="587" alt="Screen Shot 2022-04-26 at 3 27 10 PM" src="https://user-images.githubusercontent.com/1763961/165377361-2ace645f-91d8-4be6-a953-5cf7c988b045.png">|<img width="680" alt="Screen Shot 2022-04-26 at 3 27 04 PM" src="https://user-images.githubusercontent.com/1763961/165377393-ba1003c2-4ea4-43d6-98a2-440e0e6603a1.png">|
- Test branch using form https://forms-staging.cdssandbox.xyz/en/id/276
=> feat: redesign file input button

CHANGELOG.md, pages/welcome-bienvenue.js
closes #712 
- removed list of published forms from welcome page
|<img width="1000" alt="Screen Shot 2022-04-29 at 9 05 24 AM" src="https://user-images.githubusercontent.com/1763961/165950061-48ea00bc-5f53-44bd-8151-3794963e2be3.png">|<img width="921" alt="Screen Shot 2022-04-29 at 9 05 48 AM" src="https://user-images.githubusercontent.com/1763961/165950079-2a9db8da-badc-49d1-8cdd-c888fd7368c4.png">|
- Using the update code from this branch you can head over to https://forms-staging.cdssandbox.xyz/welcome-bienvenue and see that the list of published forms is gone
Please complete the following …
=> feat: remove forms list from welcome page

.github/workflows/staging-build-push-container.yml, .github/workflows/staging-deploy.yml
- Trying to fix a recurring issue we have with our staging deployment script. @patheard suggested a new way of waiting for an action to complete before triggering another one.
=> build: fix staging-deploy Github action

components/globals/SecurityBadge.tsx, lib/integration/crud.ts, lib/integration/helpers.ts, public/static/locales/en/common.json
Removed  description from badge value.
=> Badge display

.env.example, README.md
Adding more examples on whats needed to run locally using localstack
=> docs: updated env example when testing using localstack

.github/workflows/generate-sbom.yml, .github/workflows/staging-build-push-container.yml
Add GitHub workflows to generate SBOMs and upload them
to Dependency-Track. This will allow us to have a view of all
the dependencies used by the org and their potential
vulnerabilities.
1. Check that a NodeJS SBOM is generated by the creation and merge of this PR.
2. Check that a Docker SBOM is generated when this PR is merged.
n/a
=> feat: generate Software Bill of Materials

pages/id/[form]/[[...step]].tsx
=> fix: form page using incorrect data structure

components/forms/TextArea/TextArea.tsx, components/forms/TextInput/TextInput.tsx
closes #841 
| ![image](https://user-images.githubusercontent.com/77435/175353756-b6b957ec-9680-4e9b-b6b1-26dffedd3e34.png) | 
|
- Load [Form 331](https://forms-staging.cdssandbox.xyz/en/id/331) from staging.
- Observe that the message "You have 0 characters left." does not appear.
- Refresh the page several times, checking that the message does not appear.
=> fix: Change how `remainingCharacters` is initialized.

pages/api/submit.ts
There is no issue # for this PR.
I noticed a mismatched HTML tag contained within a string. I am honestly not certain if the tag should be a H1 or H2, but am guessing it should be H1.
I haven't even tested the functionality of this change, since it requires a failure by Notify, and the fix seems so apparently obvious.
=> fix: mismatched HTML tags

README.md
Update the docs with the SQL commands required to grant
yourself local admin now that we've updated the database
schema.
=> docs: grant local admin with Prisma

__tests__/Settings.test.js, components/admin/FormAccess/FormAccess.test.js, components/forms/Button/Button.test.js, components/forms/Checkbox/Checkbox.test.js, components/forms/Dropdown/Dropdown.test.js, components/forms/DynamicRow/DynamicRow.test.js, components/forms/Form/Form.test.js, components/forms/TextArea/TextArea.test.js, components/forms/TextInput/TextInput.test.js, lib/tests/validation.test.js
There is no issue for this. In looking at another issue, I saw in the [documentation for testing-library](https://testing-library.com/docs/user-event/setup/) that: 
> Using the methods on the instances returned by userEvent.setup() is recommended.
So I refactored our usage of `userEvent.setup()` to return an instance.
Note: This PR doesn't update the `JsonUpload.test.js` file, as that is updated in another PR.
- Run the jest tests. They should all pass successfully. This should already be verified when the PR is created.
=> refactor: create userEvent instance

.github/workflows/prod-build-push-container.yml, .github/workflows/staging-build-push-container.yml, .github/workflows/test-container-build-production.yml, .github/workflows/test-container-build-staging.yml, Dockerfile
* Modify Dockerfile to include GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET as build arguments
* Create two workflows on pull request to develop and main to test container build
Workflow should test changes ! 
N/A
=> fix: modify Dockerfile to include necessary build arguments

CHANGELOG.md, __fixtures__/duplicateElementIds.json, __fixtures__/invalidLayoutIds.json, __fixtures__/invalidSubElementIds.json, __fixtures__/validFormTemplate.json, lib/middleware/jsonIDValidator.ts, lib/tests/jsonIDValidator.test.js, pages/api/templates.ts
Closes #882 
- valid JSON should be able to be uploaded without errors
- a JSON config containing a duplicate ID should return an error
- a JSON config containing a layout ID that is not in the elements should return an error
- a JSON config containing duplicate subElement IDs should return an error
- a JSON config containing subElement IDs that do not match the parent dynamic row ID should return an error
=> feat: add validation for jsonConfig IDs

__tests__/api/flags.test.ts, __tests__/api/id/form/bearer.test.ts, __tests__/api/id/form/owners.test.ts, __tests__/api/templates.test.ts, __tests__/api/users.test.ts, lib/auth.ts, lib/tests/auth.test.ts, lib/tests/sessionExists.test.js, lib/users.ts, pages/admin/flags.tsx, pages/admin/index.tsx, pages/admin/login.tsx, pages/admin/unauthorized.tsx, pages/admin/upload.tsx, pages/admin/users.tsx, pages/admin/vault.tsx, pages/admin/view-templates.tsx, pages/api/auth/[...nextauth].ts, pages/id/[form]/settings.tsx, prisma/migrations/20220817173353_change_userrole_enum/migration.sql, prisma/schema.prisma
It was noticed moments after PR #906 was merged that the enum values should be UPPERCASE instead of lowercase.
Create an admin user and log into the system.  A user with `ADMINISTRATOR` as the value in the DB should be able to login.
=> fix: change enum values to UPPERCASE

README.md
Update the README with the new query required to grant
yourself the localhost `Administrator` role.
=> docs: update instructions to grant local admin

CHANGELOG.md, lib/templates.ts
- Fixed issue with ReCaptcha feature (not working because of missing API key)
- Load any form locally and try to submit it while making sure you have the ReCaptcha flag set to on in the admin>options panel
=> fix: recaptcha feature missing API key

CHANGELOG.md, __tests__/Settings.test.js, pages/id/[form]/settings.tsx
Closes #940 
| 
| 
- Load a form in the Form Settings page
- The title of the form should appear just above the Form ID.
- Change languages to see the FR / EN title appear.
=> feat: add form title to Form Settings page

lib/tests/validation.test.js, pages/api/id/[form]/owners.ts
This started out as a simple task, to change a ternary (`const requestBody = req.body ? req.body : undefined;`
) operator to a nullish operator (`const requestBody = req.body ?? undefined`).
Then I noticed that a little bit of destructuring variables could happen, to further clean up and simplify the code. I also added some tests to ensure that `isValidGovEmail` would handle `null` and `undefined` (because I removed a check for the email within `owners.ts`.
Load a form and add an email to the Form Access.
=> refactor: clean-up owners.ts code

CHANGELOG.md, components/auth/AcceptableUse.test.js, components/auth/AcceptableUse.tsx
[Acceptable use page ](https://github.com/cds-snc/platform-forms-client/pull/911) PR must be merged before this PR. 
Once acceptable use PR merged this PR will be updated to only render changes related to time formatting. 
closed #949 
Before                                       
After                                        
=> Fix last login time date format

lib/users.ts, pages/api/auth/[...nextauth].ts
Closes #946 
- Login to `/auth/login`.
- Press the "cancel" button on the "Acceptable Use" page.
- Wait a few minutes (5 or more, for example)
- Login again on `/auth/login`
- The timestamp at the top of the acceptable use page should be time from your first login, a few moments ago
There is another PR to format the timestamp correctly.
=> feat: retrieve user lastLogin from DB

CHANGELOG.md, components/admin/FormAccess/FormAccess.test.js, components/admin/FormAccess/FormAccess.tsx
Closes #733 
- login to the `/admin` section
- edit a form
- add a new user to **Form Access**
- observe that the input field for the email address is now empty
=> fix: clear user email after success response

components/login/TemporaryToken.tsx
Closes #968
This doesn't change any of the functionality, only the form input type.
| ![Screen Shot 2022-08-29 at 1 10 17 PM](https://user-images.githubusercontent.com/77435/187257780-4d53bded-3b08-41a1-8ba0-0bf04ba9e368.png) | 
- Follow the login process for a Program Administrator.
=> fix: change input to textarea

components/form-builder/panel/Button.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx
Adds temporary styling for panel actions
=> Form Builder - Add temp styling for panel actions

components/form-builder/elements/RichText.tsx, components/form-builder/elements/Select.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/types/index.ts
Adds `Required` checkbox input to the form builder element panel
- Add a form element
- Toggle the required checkbox for the form element
- Note the JSON output (updating the value)
=> Add required checkbox

components/form-builder/layout/Layout.tsx, components/form-builder/panel/Button.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx
Style and a11y improvements
| <img width="832" alt="image" src="https://user-images.githubusercontent.com/1187115/188012248-0cd47c28-d86d-4222-9813-d72a7904eb59.png"> | <img width="823" alt="image" src="https://user-images.githubusercontent.com/1187115/188012338-433d4b40-783f-4567-86bd-718c4f54b656.png"> |
=> Visual and a11y improvements

components/form-builder/__tests__/useTemplateStore.test.ts, components/form-builder/hooks/useGetTemplate.tsx, components/form-builder/layout/CopyToClipboard.tsx, components/form-builder/store/useTemplateStore.ts, components/form-builder/types/index.ts, components/form-builder/util.ts
- Reset the data store between test runs
- Add initialize method to store to enable above
- Add getSchema method to store for easier retrieval
=> Reset data store between tests

components/form-builder/__tests__/useTemplateStore.test.ts, components/form-builder/elements/Option.tsx, components/form-builder/elements/Options.tsx, components/form-builder/elements/Select.tsx, components/form-builder/panel/Button.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/Input.tsx, components/form-builder/panel/MultipleChoice.tsx, components/form-builder/panel/PanelActions.tsx, components/form-builder/panel/index.ts, components/form-builder/store/useTemplateStore.ts
This PR is mostly stylistic rather than changing logic. It is mainly concerned with adding elements and changing styling to bring us more in line with [the Figma mocks we've been using](https://www.figma.com/file/dbezuEglWNQ8qyO64eJJiA/v1.-Form-builder?node-id=353%3A9861).
The list of changes, more or less:
- Add the GDS/CDS checkboxes & radios
- Add a "Required" field to the Modal
- Always add one option by default to new question fields
- Keep text input styles in an `Input` file
- Update the "Question" field to just have an underline and use bold text 
- Focus the Question automatically, not the Option
- When you press "Enter" in an Option, you get a new Option 
- Add CDS design system-type styling for buttons
- Add CDS design system-type focus styling for inputs and the select that …
=> Update form builder so it looks more like the Figma mockups

components/form-builder/__tests__/useTemplateStore.test.ts, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx, components/form-builder/store/useTemplateStore.ts, components/form-builder/types/index.ts
When inserting a new element, previously we were just appending the new element to the end of the array. With this change, the element is inserted after the index of the item where "Add element" was clicked.
| ![Screen Recording 2022-09-15 at 2 50 45 PM](https://user-images.githubusercontent.com/1187115/190485981-3a9978dd-ffef-4f85-9ed4-51fbaafd4705.gif) | ![Screen Recording 2022-09-15 at 2 59 25 PM](https://user-images.githubusercontent.com/1187115/190487440-b32e0d4b-309e-46e1-a595-97f810342e75.gif) |
- Start a new form
- Add multiple elements
- When adding elements, they should be inserted at …
=> feat: Insert new element at index

components/form-builder/panel/Button.tsx, components/form-builder/panel/PanelActions.tsx
Disables the Move up button on the first element, and disables the Move down button on the last element.
| <img width="827" alt="image" src="https://user-images.githubusercontent.com/1187115/190501566-662ca9fa-5443-41e2-963b-8db995e83f56.png"> | <img width="827" alt="image" src="https://user-images.githubusercontent.com/1187115/190501946-a9df3369-f75a-48cd-9a30-7fffddfd0c7b.png"> |
Add multiple items, notice the move up/down buttons
=> feat: disable first move up and last move down buttons

components/form-builder/__tests__/useTemplateStore.test.ts, components/form-builder/elements/Option.tsx, components/form-builder/elements/RichText.tsx, components/form-builder/elements/RichTextLocked.tsx, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/layout/Layout.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/preview/Form.tsx, components/form-builder/store/useTemplateStore.ts, components/form-builder/types/index.ts, components/form-builder/util.ts, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
- Adds custom hook for element options
- Adds `localizeField("path")` i.e. localizeField("description") will result in `descriptionEn` or `descriptionFr`
- Updates spawn across the form builder app -- so a general click through is required
=> feat: Form builder translations and helper functions

CHANGELOG.md, lib/tests/templates.test.ts, lib/tests/users.test.ts, lib/users.ts
- Fixed issue where we could not enable/disable user permissions through the admin panel
- Updated and fixed some unit tests that were not properly checking calls to function under test
- Go to the admin panel
- Try to enable/disable permissions for any user
=> fix: unable to enable/disable user permissions

components/form-builder/hooks/useElementOptions.tsx, components/form-builder/panel/ElementPanel.tsx
There are a handful of accepted validation "types" in the JSON schema.
Here they are:
- [["email", "alphanumeric", "text", "name", "number", "phone", "date"]](https://github.com/cds-snc/platform-forms-client/blob/develop/lib/middleware/schemas/templates.schema.json#L302)
The "text" one I hadn't cottoned onto before, because it seems like it means there are no special presentation rules, as far as the form builder is concerned.
Our logic thus far assumes that `textField` elements with any validation rule specified should be treated differently (eg, maybe they are a date or an email), whereas `text` never really showed up as an option.
Recently, while importing an already-existing JSON form, I noticed that the text elements were being shown as checkboxes, and this was the root cause. …
=> fix: Import textFields with validation type of "text"

CHANGELOG.md, components/globals/Footer.js, public/static/content/en/terms.md, public/static/content/fr/terms.md, public/static/locales/en/common.json, public/static/locales/fr/common.json
closes #863 
- Updated terms and conditions page as well as the text link in the footer
|<img width="824" alt="Screen Shot 2022-10-07 at 11 37 18 AM" src="https://user-images.githubusercontent.com/1763961/194593212-8a0c3226-cbc9-4ead-ae1f-1b10dd44cee3.png">|<img width="792" alt="Screen Shot 2022-10-07 at 11 36 30 AM" src="https://user-images.githubusercontent.com/1763961/194593226-f060c6ef-e4bc-4787-8ae9-f819ae0acfff.png">|
|<img width="820" alt="Screen Shot 2022-10-07 at 11 37 10 AM" src="https://user-images.githubusercontent.com/1763961/194593217-19ba441c-bf1f-4435-80db-81e2aedb5850.png">|<img …
=> feat: updated terms and conditions as well as text link in the footer

components/globals/Footer.js, public/static/locales/en/common.json, public/static/locales/fr/common.json
- Removed hosted by CDS mention from footer
|<img width="527" alt="Screen Shot 2022-10-07 at 2 32 35 PM" src="https://user-images.githubusercontent.com/1763961/194626154-bdb610fd-3e81-4078-a7a7-3a0d521cbe00.png">|<img width="263" alt="Screen Shot 2022-10-07 at 2 32 42 PM" src="https://user-images.githubusercontent.com/1763961/194626152-d1d27ae1-93d7-4736-bc06-7473c47f5f73.png">|
=> feat: remove hosted by CDS mention from the footer

lib/templates.ts, pages/api/templates.ts, prisma/migrations/20221011172436_template_ownership/migration.sql, prisma/schema.prisma
This PR associates a User to a Template when a Template is created.
A new many-to-many relationship is introduced between Users and Templates.
Closes #1129
=> Users are associated to Templates

components/globals/AdminNav.tsx, lib/privileges.ts, pages/admin/privileges.tsx, pages/api/auth/[...nextauth].ts, prisma/migrations/20221006181804_permissions/migration.sql
- Fix default permissions in the SQL migration script
- Added error log when interpolation fails
- Quick fix permission check (while waiting for final checks to be implemented)
=> fix: default privileges definition clashes with the interpolation function

cypress/integration/login_page.spec.js, pages/auth/login.tsx, public/static/locales/en/login.json, public/static/locales/fr/login.json
=> Adds login page validation

cypress/integration/register_page.spec.js, pages/signup/register.tsx, public/static/locales/en/signup.json, public/static/locales/fr/signup.json
Adds Cypress test for signup page and fixes minor signup validation errors.
=> Adds cypress test for signup and fixes minor errors

lib/hooks/useAuth.ts
Another minor PR to remove the `statusText` check from the useAuth code
=> fix: remove statusText check from confirm callback in useAuth

lib/privileges.ts, lib/templates.ts, lib/tests/templates.test.ts, pages/admin/view-templates.tsx, pages/api/templates.ts
- Enhanced `getAllTemplates` API function to return either all or some templates depending on user privileges
=> feat: enhance getAllTemplates API function to return either all or some templates depending on user privileges

pages/admin/users.tsx, pages/api/users.ts, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-users.json
This PR adds an interface to modify user permissions
| ![Screen Shot 2022-10-24 at 11 54 54 AM](https://user-images.githubusercontent.com/25329319/197572002-52a02ae3-aa4f-47f4-8b44-e1b107f6562a.png) | ![Screen Shot 2022-10-24 at 11 49 03 AM](https://user-images.githubusercontent.com/25329319/197572036-ca4d21b0-e0e9-4fbc-909c-7eedcda6e624.png) |
| Screen Does not Exist | ![Screen Shot 2022-10-24 at 11 49 11 AM](https://user-images.githubusercontent.com/25329319/197572132-80093ec9-6be4-44e4-b584-1e2f6722ba5f.png)|
=> User management interface

components/form-builder/layout/Publish.tsx
=> Removed two links from the publish page

components/form-builder/__tests__/useAllowPublish.test.ts, components/form-builder/hooks/useAllowPublish.tsx, components/form-builder/types/index.ts
The checkTranslated function was basically just a placeholder, only checking the translated status of a single field. This fleshes out the checkTranslated function to check the entire form.
- Build a form without adding translations
- Check the Publish translate status
- Translate the form
- Check the Publish translate status again
=> Check translation status of form elements

components/form-builder/panel/PrivacyDescription.tsx
=> Updated privacy description

prisma/seeds/seed.ts
- Fixed issue with `publishingStatus` migration counter
=> fix: publishingStatus migration counter

components/form-builder/layout/EditNavigation.tsx, components/form-builder/layout/Layout.tsx, components/form-builder/layout/LeftNavigation.tsx, components/form-builder/layout/PreviewNavigation.tsx, components/form-builder/layout/Settings.tsx
When not logged in:
- Updates the Left Nav + access to publish page
- Removes delete and dropdown from settings page
- Update preview and edit navs
- Re-add save to left nav
**No Publish**
**Settings**
For testing with no auth you can checkout the [root form builder branch](https://github.com/cds-snc/platform-forms-client/tree/feature/root_form-builder) and cherry pick in b499d2472ea1abef2c3149110a47c5762d55f92b
For auth view you can checkout this branch / check left nav + publish page + settings page.
=> Add auth checks for form builder

components/form-builder/layout/Publish.tsx, components/form-builder/layout/Published.tsx
- Add call to reset form after reaching published page
- Adds get host so we can properly point to the published form
- Publish a form
- Check visit the create page and note the form state should now be `reset` / `empty`
=> Add reset form to form builder

CHANGELOG.md, lib/templates.ts, lib/tests/templates.test.ts, package.json, pages/admin/view-templates.tsx, pages/api/templates.ts, pages/id/[form]/users.tsx, prisma/seeds/fixtures/privileges.ts, public/static/locales/en/admin-templates.json, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-templates.json, public/static/locales/fr/admin-users.json, yarn.lock
closes https://github.com/cds-snc/platform-forms-client/issues/1203
- Added admin feature to assign users to template
- Navigate to http://localhost:3000/admin/view-templates
- Assign users to template using the Assign button in the forms table (you may want to create fake users to see how the UI behaves)
- Using `yarn prisma:studio` you can verify that the assignations are saved in the database
=> feat: admin can now assign users to template

components/form-builder/layout/Header.tsx, components/form-builder/layout/Published.tsx, components/myforms/Card/Card.tsx
**Adds `my forms` to form builder header**
**Connects edit link:**
- Visit form builder 
- Create a form ... use test data delivery to save a draft (temp workaround)
- Visit my forms 
- View the draft 
- Click more + edit a form 
=> Add "my forms" to form builder header + link to edit

components/form-builder/hooks/usePublish.tsx
Adds second call to API to publish a form
This will be removed once the API gets updated to handle publishing + uploading in the same call.
Create and publish a form --- view the form under "My forms"
=> Patch for publishing form

components/globals/AdminNav.tsx, components/myforms/Card/Card.tsx, pages/myforms/[[...path]].tsx
Fixes some links to Form Builder now that https://github.com/cds-snc/platform-forms-client/pull/1239 is merged
=> Fix form builder links

components/form-builder/layout/Publish.tsx, components/form-builder/panel/ConfirmationDescription.tsx
=> fix: Confirmation description update

components/form-builder/__tests__/Layout.test.js, components/form-builder/layout/Header.tsx, components/form-builder/layout/Layout.tsx, components/form-builder/layout/TestDataDelivery.tsx
Fixing / enabling a simple render test for the Form Builder.
This was disabled given some issues we ran into the the previous rich text area.
=> Fix layout test

lib/tests/validation.test.js, lib/validation.tsx
Fixes a few failing cases with the email validation.
=> Adds fix for email validation

public/static/locales/fr/form-builder.json
Fixes some bad json after a merge
=> Fix JSON from bad commit

components/form-builder/elements/RichTextLocked.tsx, components/form-builder/lexical-editor/Editor.tsx, components/form-builder/lexical-editor/RichTextEditor.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/store/useTemplateStore.tsx
Updates Rich Text area to announce aria label
Fixes #1297
|<img width="1096" alt="203073626-23edd9e4-1e7b-4ea8-b90a-917be4cc44ec" src="https://user-images.githubusercontent.com/62242/203083174-86820242-eac7-4a7f-8914-9ff8feb1ce53.png">  | <img width="1281" alt="Screen Shot 2022-11-21 at 9 32 06 AM" src="https://user-images.githubusercontent.com/62242/203082946-b93a1aa4-8907-45d0-9f84-4a70bdd4979a.png"> |
Using VoiceOver navigate to  form introduction description, privacy policy and confirmation text  --- note they should be announced to match each label. 
Are there any related issues or tangent …
=> Rich text areas - a11y - labels

components/form-builder/elements/RichTextLocked.tsx, components/form-builder/panel/ElementPanel.tsx, components/form-builder/panel/PanelActions.tsx, components/form-builder/shared/Button.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds role="toolbar" to the Element Actions panel and adds a roving index for keyboard navigation.
Also improves responsiveness of the actions panel.
=> Set PanelActions role to toolbar and add roving index

cypress/integration/form-builder.spec.js
This PR adds an initial cypress test for the form builder (while logged out)
- Runs via CI
=> Add initial cypress test for form-builder

lib/types/index.ts, lib/types/utility-types.ts, pages/api/acceptableuse.ts, pages/api/flags/[key]/disable.tsx, pages/api/flags/[key]/enable.tsx, pages/api/flags/index.tsx, pages/api/id/[form]/apiusers.ts, pages/api/id/[form]/bearer.ts, pages/api/privileges.ts, pages/api/request/publish.ts, pages/api/users.ts
No issue here just a minor PR to remove an unnecessary session check on routes which use sessionExists and protect all methods
N/A
N/A
=> fix: unnecessary session check on all routes which have all HTTP methods protected by the session

tsconfig.json
A haiku:
ts-config 
headaches, migraines, and cognitive load 
stack overflow  
See if your IDE stops screaming at you
N/A
=> fix: cypress and jest types conflicts

components/form-builder/app/edit/ConfirmationDescription.tsx, components/form-builder/app/edit/PrivacyDescription.tsx
Another PR moving towards the removal of Styled Components
- Compare current main vs this PR
Develop
PR
=> CSS cleanup for Confirmation and Policy

flag_initialization/default_flag_settings.json, pages/form-builder/support/[[...supportType]].tsx, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
No PR adding a feature flag `supportForms` to enable and disable support forms.
N/A
N/A
=> fix: add feature flag for support Forms

pages/admin/login.tsx
No issue. A warning was appearing locally when visting `/admin/login`.
This was because two children were being passed into the title component on that page 
The solution was to use one template literal 
N/A
N/A
=> fix: title component warning on /admin/login page

public/static/locales/fr/admin-templates.json, public/static/locales/fr/common.json, public/static/locales/fr/form-builder.json, public/static/locales/fr/reset-password.json, public/static/locales/fr/signup.json
closes https://github.com/cds-snc/platform-forms-client/issues/1381
- Fixed a few typos in the French translation files. The goal here is to fix the typos reported in the Github issue (in the Known issues section).
=> fix: some typos in French translation files

components/form-builder/__tests__/useAllowPublish.test.tsx, components/form-builder/__tests__/useTemplateStore.test.tsx, components/form-builder/app/edit/PanelActionsLocked.tsx, components/form-builder/app/edit/elements/Option.tsx, components/form-builder/app/edit/elements/Options.tsx, components/form-builder/app/edit/elements/tests/Dropdown.test.js, components/form-builder/app/edit/elements/tests/Option.test.js, components/form-builder/app/edit/elements/tests/Options.test.js, components/form-builder/app/edit/elements/tests/RichTextLocked.test.js, components/form-builder/app/edit/elements/tests/ShortAnswer.test.js, components/form-builder/test-utils/defaultStore.json
Adds jest test for form builder elements
Haven't been able to track down the true cause of the act errors in the tests  --- but wanted to get them removed as they are very very noisy.
--- for now I found this 
>  if there's no visual indication of the async task completing.
https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning#an-alternative-waiting-for-the-mocked-promise
I think something like this could be the case possibly around hydration
--- with that in place the noisy warnings go away.
While testing I did see this which could be related but haven't figured out how yet
=> Form Builder - Elements tests

public/static/locales/fr/my-forms.json
Handful of French translation strings from My Forms section
=> Add remaining translation strings for My Forms section

components/myforms/LeftNav/LeftNavigation.test.js, components/myforms/LeftNav/LeftNavigation.tsx
Updates left nav to wrap when link has longer text.
| <img width="582" alt="before" src="https://user-images.githubusercontent.com/62242/209362740-47e72c02-6169-4b0a-9176-6ee6eed93be5.png"> | <img width="898" alt="after" src="https://user-images.githubusercontent.com/62242/209362780-0483fc86-1fbc-4f15-9627-103d763e1a23.png"> |
- Visit my forms
- Switch to french
- View left nav
=> Fix My Forms left nav

components/form-builder/app/edit/Modal.tsx, components/form-builder/app/edit/PanelActions.tsx, components/form-builder/app/edit/tests/Modal.test.js, styles/_form-builder.scss
- Removes duplicate style classes
- Updates close button to bring it inline with the Dialog component (with `close` text).
- Adds a `defaultOpen` prop so we can control the initial open or close state again bringing the modal more inline with the Dialog component.
|  |
- Create a form
- Click `more...` button
- At this point the modal should be open
=> Cleanup modal styles

components/form-builder/app/Preview.tsx, components/form-builder/app/Publish.tsx, components/form-builder/app/Published.tsx, components/form-builder/app/Template.tsx, components/form-builder/app/edit/ElementDropDown.tsx, components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/Modal.tsx, components/form-builder/app/edit/PanelActions.tsx, components/form-builder/app/edit/elements/Option.tsx, components/form-builder/app/edit/elements/lexical-editor/plugins/FocusEditor.tsx, components/form-builder/app/edit/elements/lexical-editor/useEditorFocus.tsx, components/form-builder/app/edit/elements/question/QuestionInput.tsx, components/form-builder/app/navigation/Header.tsx, components/form-builder/app/shared/Dialog.tsx, components/form-builder/app/shared/DownloadFileButton.tsx
This PR is the first part of updates to ensure the `rules of hooks` are followed.  
https://github.com/cds-snc/platform-forms-client/pull/1491 sets up lint rules for hooks but ends up being too large to test properly.  This PR handles some of the easier updates without adding the lint rule yet (that will be added later in followup PRs)
**Before (55 problems)**
**After  (35 problems)**
Are there any related issues or tangent features …
=> Form builder hook updates pt-1

components/form-builder/hooks/useAllowPublish.tsx
This PR is the second part of updates to ensure the rules of hooks are followed.
https://github.com/cds-snc/platform-forms-client/pull/1491 sets up lint rules for hooks but ends up being too large to test properly. This PR handles some of the easier updates without adding the lint rule yet (that will be added later in followup PRs)
This update the useAllowPublish hook --- test the publish page
=> Form builder hook updates pt-2

public/static/locales/en/form-builder.json
Fixes minor content change for contact us form
Navigate to http://localhost:3000/form-builder/support/contactus and you should see the link "Canada.ca Contact us". Previously the link was "Canada.ca Contact"
=> Fixes minor content change for contact us form

components/form-builder/app/edit/elements/tests/Question.test.js, components/form-builder/test-utils/index.ts, components/form-builder/test-utils/storage.ts
Adds a session storage mock for Form builder tests + updates question input test
=> Add session storage mock for form builder tests

components/myforms/Tabs/TabsList.tsx, pages/myforms/[[...path]].tsx
- Updates tab list which uses a ref as a dependency see related PR:https://github.com/cds-snc/platform-forms-client/pull/1505
- Updates My Forms page note we purposely exclude the router dependancy see:
https://github.com/vercel/next.js/discussions/29403#discussioncomment-1908563
- Test My Forms loads and redirects to drafts properly
@thiessenp-cds I think we're not using the `TabsList` component anymore
1) Can you confirm
2) If we're not should we remove it? 
=> Hook updates - TabsList + My Forms

lib/hooks/useRefresh.ts, pages/id/[form]/retrieval.tsx
- Updates useRefresh
Fixes:
```
22:6  warning  React Hook useEffect was passed a dependency list that is not an array literal. This means we can't statically verify whether you've passed the correct dependencies 
```
- Updates retrieval.tsx
Fixes:
```
7:17  error  React Hook "useTranslation" is called in function "retrieval" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use"  react-hooks/rules-of-hooks
```
them such as any environmental setup steps and/or any time-based …
=> Fix hook lint issues ( useRefresh, retrieval)

package.json, yarn.lock
Update TypeScript + related packages
=> Update TypeScript version - 4.9.4

prisma/seeds/seed.ts
- Fixed deployment issue due to latest changes around DB Schema
=> fix: added required object types directly in seed.ts

components/form-builder/app/edit/Edit.tsx, components/form-builder/app/navigation/FileName.tsx, components/form-builder/app/shared/Input.tsx
Update to use the form title as the form name if the form name hasn't already been set
- Create a new form
- Add a form title ... onBlur this should set the form name
- Create a new form
- Add a form name
- Add a form title 
The form name should be kept in this case
Related: https://github.com/cds-snc/platform-forms-client/pull/1581
=> Use form title as form name

components/form-builder/app/navigation/Header.tsx, styles/_form-builder.scss
Visit form builder home page or my forms --- should show icon + GC Forms
=> Add GC Forms name to "non form builder edit pages"

components/form-builder/app/shared/tag-input/TagInput.tsx, components/form-builder/app/shared/tag-input/Tags.tsx, components/form-builder/app/shared/tag-input/tests/TagInput.test.js
Improved tests around TagInput component including:
- Test tag input using {Space} {Enter} {Comma} and onBlur
- Test validation with fake validator
Also improved structure of Tag by moving the button into the span tag container.
=> Improved tests around TagInput component

components/form-builder/app/ShareModal.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Add link to Share Modal email preview
| <img width="720" alt="image" src="https://user-images.githubusercontent.com/1187115/217296334-e89b2545-f7eb-4540-80a0-e069199a929e.png"> | <img width="714" alt="image" src="https://user-images.githubusercontent.com/1187115/217296026-0c0ec8f4-31b0-4eb1-8343-acebe5ab86ee.png"> |
=> Bugfix: Add link to email preview

components/form-builder/app/ShareModal.tsx, components/form-builder/app/edit/elements/element-dialog/ElementDescription.tsx, components/form-builder/app/edit/elements/element-dialog/ElementDialog.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/CheckBox.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/DropDown.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/Radio.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/Text.tsx, components/form-builder/app/shared/Button.tsx, components/form-builder/app/shared/Dialog.tsx, components/form-builder/app/shared/ListBox.tsx
Bring the Add Element dialog into alignment with current designs. This involved modifying the underlying Dialog component to support the slightly different style, without affecting other instances that depend on the default styling of Dialog.
Converted a bunch of the Dialog component classes to Tailwind.
Modified ListBox to use list items for better semantics.
| <img width="792" alt="image" src="https://user-images.githubusercontent.com/1187115/217656371-5c8695ae-83d3-48d2-a06d-22f68c96992d.png"> | <img width="783" alt="image" src="https://user-images.githubusercontent.com/1187115/217656461-dbe3 …
=> Add element Dialog updates

components/form-builder/app/edit/PanelActions.tsx, components/form-builder/app/edit/tests/PanelActions.test.js
Adjust the Panel Action buttons into an array that we can loop over to eliminate some code duplication.  This also preps more work for the repeated question sets. 
- Action panel buttons should function exactly as before but with new code.
=> Dynamic panel action buttons - pt 1

components/form-builder/app/translate/DownloadCSV.tsx
Updates the Translation CSV Download to support repeating sections.
=> Update CSV Download on Translate to support repeating sections

pages/form-builder/publish.tsx
Going through the code to troubleshoot a help desk ticket I found some 
duplicated code that could be removed.  Looks like the remnants of a merge conflict.
=> remove duplicate code

components/form-builder/app/navigation/Header.tsx, flag_initialization/default_flag_settings.json, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
Removes feature flag for editable filename 
- Ensure with flag remove the "logo" / filename are work as expected.
=> Turn editable filename on by default

components/form-builder/app/edit/PanelBody.tsx, components/form-builder/app/edit/PanelBodyRoot.tsx, components/form-builder/app/edit/PanelBodySub.tsx, components/form-builder/app/edit/elements/question/Question.tsx, components/form-builder/app/edit/elements/question/QuestionDescription.tsx, components/form-builder/app/edit/elements/question/QuestionInput.tsx, components/form-builder/app/edit/elements/question/QuestionNumber.tsx, components/form-builder/app/edit/elements/tests/Question.test.js, components/form-builder/app/edit/elements/tests/QuestionDescription.test.js, components/form-builder/app/translate/Translate.tsx, components/form-builder/util.ts, cypress/e2e/form-builder/form-builder.cy.js
Contains minimal visual changes. Mainly restructuring some of the elements in PanelBody so they flow better and rely less on absolute positioning.
This will help a developer test things out without too much detective …
=> Improve PanelBody structure/flow

components/form-builder/app/edit/Edit.tsx, components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/PanelActionsLocked.tsx, components/form-builder/app/edit/SelectedElement.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/Address.tsx, components/form-builder/app/edit/elements/element-dialog/index.tsx, components/form-builder/app/edit/elements/sub-elements/SubElement.tsx, components/form-builder/blockLoader.ts, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/store/useTemplateStore.tsx, components/form-builder/types/index.ts, form-builder-templates/address.json, lib/types/form-types.ts, pages/api/form-builder/load-block.ts, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds initial setup for adding "address" fields via a single block 
https://www.youtube.com/watch?v=etM0gQvQjAo
- Use the add block dialog to insert the address fields 
- Ensure the auto-complete values match as expected.
- Content for the example block TBD
- Translated content TBD
- Placement in the List Box will likely move
=> Address fields with AutoComplete

components/form-builder/app/edit/elements/element-dialog/descriptions/Address.tsx, form-builder-templates/address.json, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds address example
Note: Also added "What is your address?" as page text to the .json template
- Add an address block via the Add Block dialog
=> Add address example

Dockerfile
Updates docker file to copy the form builder templates
=> Form builder templates 

components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/PanelActionsLocked.tsx, components/form-builder/app/edit/elements/sub-elements/SubElement.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/1707
- Add a long text field
- Should show as long text vs short text
=> Fix long text issue

components/form-builder/app/edit/SelectedElement.tsx, cypress/e2e/form-builder/add-element-dialog.cy.js, cypress/e2e/form-builder/add-elements.cy.js
Cycles through adding each of the "basic" types (ie, doesn't include repeating sets or templates, those are tested elsewhere).
=> Add some tests around adding elements

components/form-builder/app/edit/ElementRequired.tsx, cypress/e2e/form-builder/attestation.cy.js, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
- Adds Cypress test for Form Builder attestation
- Update required checkbox in the Form Builder for attestation to be listed as "All required"
- Use the Form Builder to add Legal Attestation
=> Form builder attestation test

components/form-builder/app/navigation/Header.tsx, components/forms/Form/Form.test.js, cypress/e2e/form-builder/share.cy.js, flag_initialization/default_flag_settings.json, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
- Turns on share feature
- Adds initial cypress test for logged out view
- Fixes input margin issue when logged in
- Test share using logged out
- Cypress test
Margin before
=> Form builder - Turn on share by default and add initial cypress test

components/form-builder/app/edit/elements/DropDown.tsx, components/form-builder/app/edit/elements/element-dialog/ElementDialog.tsx, components/form-builder/app/edit/elements/tests/Dropdown.test.js, components/form-builder/app/shared/ListBox.tsx, components/form-builder/app/shared/tests/ListBox.test.js, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/types/index.ts
Updates how we pass in and style icons for the dropdown and the list box
We can now style direct vs adding a wrapping div
**Before:**
```
{item.icon && (
<div className={highlightedIndex === index ? "icon icon-highlighted" : "icon"}>
{item.icon}
</div>
)}
```
**After:**
```
{item.icon && (
<Icon className={highlightedIndex === index ? "icon icon-highlighted" : "icon"} />
)}
```
- Test adding a block
=> Update dropdown + list box icons

components/form-builder/app/navigation/EditNavigation.tsx, components/form-builder/app/navigation/SubNavLink.tsx, components/form-builder/icons/QuestionsIcon.tsx, components/form-builder/icons/TranslateIcon.tsx, components/form-builder/icons/index.ts
Updates "Edit" navigation styling
Per latest figma updating the edit navigation
| <img width="488" alt="Screen Shot 2023-03-10 at 2 01 23 PM" src="https://user-images.githubusercontent.com/62242/224403808-0bc735fc-787f-4141-b94c-80d1c7f1751b.png"> | <img width="530" alt="Screen Shot 2023-03-10 at 2 00 55 PM" src="https://user-images.githubusercontent.com/62242/224403721-d28aa92a-b74e-45db-a3e3-e4e74530819b.png"> |
- Test edit nav (focus, hover, active)
- Updating stying only didn't update the text in this PR
=> Update edit navigation 

components/form-builder/app/navigation/LeftNavLink.tsx
Updates left nav CSS to remove box shadow
| <img width="533" alt="Screen Shot 2023-03-10 at 3 23 36 PM" src="https://user-images.githubusercontent.com/62242/224421878-536334fc-7ba4-4fe3-9fc7-0e85225b3037.png">| <img width="533" alt="Screen Shot 2023-03-10 at 3 23 54 PM" src="https://user-images.githubusercontent.com/62242/224421898-21f0ebf8-8e9d-4acc-8a99-f33bd48a9638.png"> |
- Check "active" state for left nav
links in this …
=> Remove box shadow on left nav

components/form-builder/app/edit/ElementRequired.tsx, styles/_form-builder.scss
Updates Element Required to use TailWind
- Ensure required checkbox is styled as per before but now with a TailWind child selector
=> Element required css

components/form-builder/app/edit/ModalForm.tsx, components/form-builder/app/navigation/EditNavigation.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds max rows properties for question sets
- Add a question set
- Set the maximum number of rows
- Ensure the output only allows for the number entered in the max rows property
=> Question sets max rows

components/form-builder/app/edit/elements/element-dialog/descriptions/FileInput.tsx, components/form-builder/app/edit/elements/element-dialog/index.tsx, components/form-builder/app/shared/ListBox.tsx, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/icons/UploadIcon.tsx, components/form-builder/icons/index.ts, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Adds a file input to the form builder (hard-coded to off)
This sets up the addition of a file input component for the future 
- Add a file input element
=> File input - prep

cypress/support/commands/commands.js, lib/auditLogs.ts, lib/integration/dynamodbConnector.ts
PR fixes an error that crept in during the Audit Log feature work.
=> Fix DynamoDB connector for localstack setup

public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Change wording for accuracy:
`agree`--> `attest`
`accepte` --> `atteste`
=> Update attestation copy

components/form-builder/app/edit/SelectedElement.tsx, components/form-builder/app/translate/Translate.tsx, components/form-builder/hooks/index.ts, components/form-builder/hooks/useElementOptions.tsx, components/form-builder/hooks/useIsAdminUser.tsx
Toggle file input to "on" for admin users so we can use it for the branding request form
- Test admin vs non admin user for the add element dialog
=> Add check for admin / file input

public/static/content/en/sla.md, public/static/content/fr/sla.md
Issue: 
- some missing numbers and hierarchy
Source of truth: 
https://docs.google.com/document/d/1Uqu8lxiO9BrTnZOubJzSxe33q2RJKSdnTcnSXfr2mvA/edit#
=> Improve SLA numbered list formatting

components/myforms/Card/Card.tsx, components/myforms/MenuDropdown/MenuDropdown.tsx
With the updates from https://github.com/cds-snc/platform-forms-client/pull/1748 the delete and download links from my forms no longer work.
- Fixes download link from my forms (now a direct download)
- Visit my forms
- Download via menu
=> Fix - download link form my forms

components/form-builder/app/Publish.tsx, components/form-builder/app/ResponseDelivery.tsx, components/form-builder/app/SettingsLoggedOut.tsx, components/form-builder/app/branding/Branding.tsx, components/form-builder/hooks/useAllowPublish.tsx, components/form-builder/types/index.ts, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
- Adds card for logged out
- Adds fix to remove email check when publishing
- Removed isPublished contact support text
- Adds logged out check / card for branding page
- Visit settings as a logged out user
=> Settings - logged out

pages/form-builder/responses/[[...params]].tsx
Fixes "missing" form id error for local developement
- Sets formId to null when it does't exist.  Form id doesn't exist until a form is saved.
- As a logged in user visit responses page without a form id i.e. a form that hasn't been saved yet
=> Responses + form id

components/form-builder/app/Preview.tsx, components/form-builder/app/Publish.tsx, components/form-builder/app/PublishNoAuth.tsx, components/form-builder/app/Template.tsx, components/form-builder/app/edit/elements/RichTextLocked.tsx, components/form-builder/app/edit/elements/sub-elements/PanelHightlight.tsx, components/form-builder/app/navigation/FileName.tsx, components/form-builder/app/navigation/Header.tsx, components/form-builder/app/navigation/LeftNavLink.tsx, components/form-builder/app/navigation/LeftNavigation.tsx, components/form-builder/app/navigation/ShareDropdown.tsx, components/form-builder/app/shared/SaveButton.tsx, components/form-builder/app/translate/Translate.tsx
Migrate from old responsive class prefixes to new ones in form-builder app
Should be minimal visual changes aside from the orientation of the left nav at smaller screen sizes.
| ![image](https://user-images.githubusercontent.com/1187115/227045614-345ab72f-4d00-45f2-8b15-0ddd1251fe92.png) | ![image](https://user-images.githubusercontent.com/1187115/227045666-a16722de-898d-4d68-ad16-b7d2f2ea09e0.png) |
them …
=> Refresh responsive classes

components/myforms/LeftNav/LeftNavLink.tsx, components/myforms/LeftNav/LeftNavigation.tsx
Updates the LeftNavigation component in MyForms to match the responsive and other updates in the one in FormBuilder. Minimal visual changes other than improved responsiveness.
=> Update MyForms LeftNavigation to match FormBuilder

components/form-builder/app/edit/elements/element-dialog/descriptions/Attestation.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/1751
- Add a legal attestation block 
- Ensure conditions are listed as 1,2,3
=> Fix condition example text

public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Updates text for 
> Didn’t find your department or agency ...
- Check for text updates on the branding page
=> Branding page - text update

public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Updates translation strings for settings page
Visit setting page as a logged in / logged out user
```
fr/form-builder/settings
```
=> FR text updates for settings page

components/form-builder/app/edit/elements/element-dialog/descriptions/Contact.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/1329#issuecomment-1472088492
=> Adjust heading style of preferred language

pages/index.tsx
=> Add lang attributes around strings on bilingual page

__fixtures__/dynamicRowsTestForm.json, __fixtures__/testData.json, __fixtures__/validFormTemplate.json, __fixtures__/validFormTemplateWithHTMLInDynamicRow.json, components/form-builder/app/edit/SelectedElement.tsx, cypress/e2e/form-builder/add-elements.cy.js, cypress/e2e/form-builder/form-builder-field-with-description.cy.js, form-builder-templates/contact.json, public/static/locales/en/admin-settings.json, public/static/locales/en/form-builder.json, public/static/locales/fr/common.json, public/static/locales/fr/form-builder.json, public/static/locales/fr/reset-password.json
Tweaks for improved content (especially in French), for:
- Given examples
- Repeating question terminology
- Date format
- Numeric field
- Plural/singular agreement
- etc.
=> Content tweaks

components/form-builder/app/edit/ModalForm.tsx
Fixes #1729  an issue where the more modal was writing data to the wrong language fields
- Add a short answer 
- Enter a description 
- Using Builder translation toggle to switch to fr
- Enter FR desc
- Swap to en 
- Ensure desc match toggled language
See: https://www.youtube.com/watch?v=NexUi3mKOzc
=> Use translationLanguagePriority for "more modal"

pages/api/share.ts
closes https://github.com/cds-snc/platform-forms-client/issues/1671
- Added French translation to Form shared email content.
The rest of the changes that were requested in the Github issue did not require code changes but configuration within GC Notify.
=> feat: added French translation to Form shared email content

public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
=> Add missing translation string

components/form-builder/app/navigation/SubNavLink.tsx
=> Flip active/inactive pill states

documentation/Forms/AccessibilityReport.stories.mdx
=> Remove a11y tracker link

components/form-builder/app/ShareModal.tsx
Fixes sent status from https://github.com/cds-snc/platform-forms-client/pull/1829
=> Fix bad commit for share modal

components/form-builder/hooks/useElementOptions.tsx, cypress/e2e/form-builder/repeating-set.cy.js, flag_initialization/default_flag_settings.json, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
Places repeating sets behind a feature flag so it can be disabled for now as we refine.
Are there any related issues or tangent features you …
=> Disable repeating sets behind a feature flag

public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Updates the Privacy statement block text in English and French. …
=> Update privacy statement block text

components/form-builder/app/ShareModal.tsx
=> Make share modal preview bilingual

components/form-builder/app/edit/ElementPanel.tsx, components/form-builder/app/edit/PanelBodyRoot.tsx
Adds click handler for element panel 
- Update to handle opening the floating menu on click.
=> Panel click

components/form-builder/app/ShareModalUnauthenticated.tsx
=> Translation for unauthenticated share menu too

components/form-builder/app/edit/ElementPanel.tsx
A previous PR #1859 sets focus to the text input within an Element panel when clicking the panel, but this relies on the RefsContext, which does not contain refs for RichText element types.
This addresses that by reaching out to the DOM to search within the clicked element for an editor and setting focus to it.
Also fixes moveUp/moveDown for RichText elements as well, with a similar problem/solution. …
=> Handle setting focus to RichText elements

components/form-builder/app/edit/PanelActions.tsx, components/form-builder/hooks/usePanelActions.tsx
Adds a isRoving check to only handle focus when using the panel actions menu
=> Add is roving check for panel actions menu

components/form-builder/app/edit/ModalForm.tsx
Add max chars for text areas
Fixes: #1863 
- Insert a long text element
- Use more menu to add a max chars
=> Max chars for text area

components/myforms/Card/Card.tsx, components/myforms/CardGrid/CardGrid.tsx
- Updates link to form responses to use smaller text
- Updates grid min , max sizing
- Removed `span` within the `a` tag (no needed)
- General My forms test
=> My forms - Update card styling

components/form-builder/app/shared/MultipleChoice.tsx
removes extraneous double quote from className interpolation …
=> Remove extra double quote

components/form-builder/app/translate/Description.tsx
=> Fix reference to elementType label

components/form-builder/app/edit/elements/element-dialog/descriptions/Date.tsx, components/form-builder/app/edit/elements/element-dialog/descriptions/DropDown.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Fixes #1923
Updates add element dialog examples for dropdown and date to use the translation files
- Use the add element dialog to select dropdown and date -- en / fr
=> Update example text

components/form-builder/store/useTemplateStore.tsx, pages/api/submit.ts, prisma/migrations/20230413154707_default_security_attribute/migration.sql, prisma/schema.prisma, prisma/seeds/seed.ts
Updates forms to use Protected A by default within the app settings
- Create a new form
- Ensure the new form defaults to Protected A
=> Security Attribute - default to Protected A

components/form-builder/app/branding/BrandingRequestForm.tsx
There was a hardcoded language reference for the Brand submission form, causing it to only render in English. This updates that language reference to use the selected language from i18n.
This will help a developer test …
=> Render brand form in selected language

public/static/content/en/sla.md, public/static/content/en/terms-and-conditions.md, public/static/content/en/terms-of-use.md, public/static/content/fr/sla.md, public/static/content/fr/terms-and-conditions.md, public/static/content/fr/terms-of-use.md, public/static/locales/en/common.json, public/static/locales/en/terms.json
- Translation of terms and conditions 
- Sentence case in footers
- Spacing of docs
=> FR Terms and conditions + tinkering policy docs

components/form-builder/app/branding/options.ts
fixes #1968 
Set branding to OAG test en / fr
=> Fix fr logo path for Auditor General branding 

components/globals/LanguageToggle.tsx
Fixes: #2018
Adds isReady check before using router path
- Open dev console
- Login 
- Note error on agreement page is gone
See: https://github.com/cds-snc/platform-forms-client/issues/2018#issue-1692457016
=> Warning: Prop href did not match.

pages/index.tsx
Fixes #2006
Fixes an issue where the browser locale was prepended to the links on the landing page.
With the browser set to FR
`/en/form-builder` ended up being  `fr/en/form-builder`
```
locale - The active locale is automatically prepended. locale allows for providing a different locale. When false href has to include the locale as the default behavior is disabled.
```
| <img width="500" alt="Screenshot 2023-05-04 at 9 01 20 AM" src="https://user-images.githubusercontent.com/62242/236212364-269e5a8f-1715-4830-b3f8-3ee888c909d0.png"> |<img width="500" alt="Screenshot 2023-05-04 at 9 03 10 AM" …
=> Disable locale prop for links on landing page

components/form-builder/app/edit/Edit.tsx, components/form-builder/app/edit/RefsContext.tsx, components/form-builder/app/edit/elements/question/QuestionInput.tsx, components/form-builder/app/shared/ExpandingInput.tsx, cypress/e2e/form-builder/add-elements.cy.js, cypress/e2e/form-builder/autocomplete.cy.js, styles/_form-builder.scss
Partial fix for https://github.com/cds-snc/platform-forms-client/issues/2003
Follow-up from https://github.com/cds-snc/platform-forms-client/pull/2025
Swaps question Input to use the expanding input.
| <img width="877" alt="old" src="https://user-images.githubusercontent.com/62242/236288025-212d0f0a-ceeb-4a3a-9d09-698308fdb11b.png"> | <img width="896" alt="new" src="https://user-images.githubusercontent.com/62242/236288074-12f85a7c-7f16-48d0-a71b-799b92f584c7.png"> |
- Create a new form 
- Enter multiple lines of content in a question input
- Note that the input expands to fix the input. …
=> Expanding question inputs

lib/middleware/cors.ts, lib/middleware/csrfProtected.ts, lib/middleware/jsonIDValidator.ts, lib/middleware/jsonValidator.ts, lib/tests/jsonValidator.test.js, pages/api/acceptableuse.ts, pages/api/templates/[formID].ts, pages/api/templates/index.ts, pages/api/verify.ts
- Reworked API error responses when message was 'Malformed API Request'
=> refactor: reworked API error responses when message was 'Malformed API Request'

package.json, yarn.lock
Update Zustand (major 10.0.1), Immer + Next to latest versions 
=> Bump - Zustand, Immer + Next

styles/_form-builder.scss
Fixes #1912
Small update to use inline-block vs bock for Radio Fields and Checkbox fields within the Form Builder
|<img width="494" alt="Screenshot 2023-05-08 at 12 20 04 PM" src="https://user-images.githubusercontent.com/62242/236876670-451efa28-27df-48df-a818-ee55d4773b97.png"> | <img width="499" alt="Screenshot 2023-05-08 at 12 19 44 PM" src="https://user-images.githubusercontent.com/62242/236876753-9c03b657-d203-4650-803f-1c78463f5815.png"> |
There are a few places in the Form builder that use Radio Fields and Checkboxes
- Required field inside the editor
- Settings page
- More Modal …
=> Fix #1912 - use inline block

components/globals/LanguageToggle.tsx
> Having an issue with the language toggle at the top right of the form, when switching it gives error of page cannot be found. 
Update to Language toggle to use `pathname` by default and asPath once the client path isReady.
This PR uses `pathname` as the default path --- once and if isReady gets called the href will update to use asPath if it doesn't already match the `pathname`.
<hr>
Per https://github.com/cds-snc/platform-forms-client/issues/2018 there was a mis-match on the href between the client and server.
Adding adding the isReady #2021 check fixed one problem but cause an issue for server rendered pages see: https://github.com/cds-snc/platform-forms-client/issues/2048.
In https://github.com/cds-snc/platform-forms-client/pull/2058 we removed the usage of asPath and isReady but …
=> Language toggle href - support ticket #15026

public/static/locales/en/unlock-publishing.json, public/static/locales/fr/unlock-publishing.json
=> Content tweak clarifying why we collect manager's email

pages/auth/resetpassword.tsx, public/static/locales/en/common.json, public/static/locales/fr/common.json
- Breaks components into Step1 (enter your email) + Step 2 (reset your password)
https://github.com/cds-snc/platform-forms-client/pull/2126/files#diff-df8b3fb3b339ac4385f407ce009b0b40f74d57219d7a82742c7eeae0244bf3f4R330
<hr>
<hr>
- Adds link back to Sign In
- Updates buttons to use primary theme
- Updates H1 tags to remove the underline + slight adjustment to spacing to match the new layout
|<img width="758" alt="old" src="https://github.com/cds-snc/platform-forms-client/assets/62242/8a1c9747-7884-4c1f-ba08-d9c38c3f5c2e"> | <img width="781" alt="new" …
=> Small tweaks for reset password screens

components/form-builder/app/edit/SelectedElement.tsx, components/form-builder/app/edit/elements/RichText.tsx
Fixes: #2168
See bug in #2168
After the fix:
- Create a new form
- Enter title name
- Add the description
- Add a short answer block - type in the question
- Click on Add (default page text block) and click on select block
- Move the page text block above the short answer block
- Enter text into the page text block and the same text should not appear under short block
=> Update Rich text to use id vs index

lib/hooks/auth/useAuthErrors.ts, lib/hooks/auth/useLogin.ts, pages/auth/login.tsx
Update to handle "bad" 2FA code from a post request
Re-using the 
> The security code provided does not match our records.
Message for this one and also 
> The confirmation code has expired. Please request a new one.
when expired
- Enter username + password
- On the 2FA code input --- enter an invalid code
- Should show an error message
=> WIP - 2fa/error handling 2130

lib/auth/2fa.ts, lib/auth/cognito.ts, lib/auth/tokenGenerator.ts, lib/tests/auth/2fa.test.ts
Closes: #2104 
This PR borrows from 'crypto-random-string' and modifies the code, with attribution to the original code version.
It's insertion directly into our codebase is a mitigation strategy against the risk of the original code being modified or removed.
Entropy is calculated as log2(N^L) where N is the number of possible characters and L is the length of the string
For our easy to read character set, N = 32, so entropy = log2(32^L) = L * log2(32) = L * 5
A token length of 5 gives us 25 bits of entropy, which is enough for a token that is only used once
| ![Screenshot 2023-05-30 at 9 48 …
=> 2fa Crypto code generation

pages/signup/register.tsx
Fixes warning where the password confirmation field was changing from uncontrolled component into a controlled component.
- Test registration page 
- Note the `uncontrolled ` warning is now gone.
=> Confirm password development warning

components/auth/Verify.tsx, lib/hooks/auth/useVerify.ts, lib/users.ts, pages/api/auth/[...nextauth].ts, types/next_auth/index.d.ts
Adds a new property to the Session that identifies if this is a users first time logging into GCForms.
The Verify Token page now listens to `useSession` and routes to the acceptable use page on successful authentication.  A user is then redirected appropriately to the New User page or directly to MyForms depending if this is their first time logging in.
- run `prisma:reset` to reset local database
- Login to GCforms
- Enter 2fa code
- Should be redirected to Acceptable use policy
- Accept policy
- Should be redirected to New User Account screen
- Skip publishing step
- Should be redirected to MyForms
- Sign out
- Login to GCforms
- Enter 2fa code
- Should be redirected to Acceptable use policy
- Accept policy
- Should be redirected to MyForms
This new property on the Session could also be …
=> fix: user always receives new account message after logging in

lib/hasError.ts
While testing the `requestNew2FAVerificationCode`  ... force throwing an error Next was catching an error where `.includes` didn't exist for the message type.  Fixed by wrapping a try / catch.
```
export const requestNew2FAVerificationCode = async (
authenticationFlowToken: AuthenticationFlowToken,
email: string
): Promise<void> => {
const verificationCode = await generateVerificationCode();
throw new Error("requestNew2FAVerificationCode > failure");
```
- force throw an error that gets checked by hasError
=> Fix has error

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
Update the devcontainer so that it can start properly.
=> fix: local devcontainer setup

lib/auth/2fa.ts
Fixes #2251
| <img width="500" src="https://github.com/cds-snc/platform-forms-client/assets/62242/6649d3ab-88aa-4887-a9a0-7636ab476cc7" /> |<img width="594" alt="Screenshot 2023-06-12 at 10 07 27 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/7df5efdf-c3d0-4d05-b7a9-2063cf63b768"> |
=> Send new code - Replace bullet point with newlines

components/auth/Verify.tsx, pages/signup/register.tsx
Fixes: #2248
Updates register and verify screens to move focus to alert
- Test "sign-up" screen by entering invalid info
- Test verify code by entering invalid code
=> fix: give focus to alert for create account and verify screens

public/static/locales/fr/auth-verify.json, public/static/locales/fr/common.json, public/static/locales/fr/signup.json
Fixes : #2242 
String updates
- Test verify and sign-up screens
=> fix:  2fa string updates

CHANGELOG.md, components/auth/ReVerify.tsx, lib/auth/cognito.ts, lib/auth/index.ts, lib/tests/auth/cognito.test.ts, pages/api/auth/2fa/request-new-verification-code.ts
- Reviewed Cognito/2FA (lib) thrown errors
- Removed unnecessary line of text in CHANGELOG.md now that the process is automated
- There is not much specific to test here outside of making sure that the sign-in flow still works as expected
=> refactor: review Cognito/2FA thrown errors

lib/auth/2fa.ts, public/static/locales/en/auth-verify.json, public/static/locales/fr/auth-verify.json
Update to use `security code` vs `verification code`
- sign-in flow
=> fix: update content to use security code vs verification code

.github/workflows/prod-build-push-container.yml
Github variable for tag was not being passed properly to checkout action.
=> ci: fix prod-build-push-container.yml

lib/types/privileges-types.ts, prisma/migrations/20230614135719_add_user_active/migration.sql, prisma/schema.prisma
Update user table to add 'active' status for deactivate account feature.
- Run migration scripts + check your the resulting user table schema
=> chore: update user table + add  migrations for upcoming feature

components/admin/Users/Dropdown.tsx, pages/admin/users.tsx, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-users.json
Adds dropdown menu for users screen.
=> [deactivate] - add dropdown menu

lib/templates.ts, lib/users.ts, pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/index.tsx, public/static/locales/en/admin-forms.json, public/static/locales/fr/admin-forms.json
Update manage form + create a query to pull forms for a user
- test using multiple users accounts to ensure the manage forms page is only pulling forms for a single user.
=> [deactivate] Manage forms

components/admin/LeftNav/LeftNavigation.tsx, components/auth/LoginMenu.tsx, components/form-builder/app/navigation/Header.tsx, components/globals/AdminNav.tsx, components/globals/layouts/AdminNavLayout.tsx, components/globals/layouts/UserNavLayout.tsx, lib/users.ts, pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/[id]/manage-permissions.tsx, pages/admin/accounts/index.tsx, public/static/locales/en/common.json, public/static/locales/fr/common.json
- Break out permissions page
- Update layout to add admin link
- Test permissions page 
=> [deactivate] Update layout + move permissions

public/static/content/en/terms-of-use.md, public/static/content/fr/terms-of-use.md
Based on Sarah's recommendation: https://docs.google.com/document/d/1ThGNKO_oyKBSgm7R5Smi8goBIphCV-VTa3249J5sdDc/edit#heading=h.cyhr51dns2gv
=> Terms of use: typo and formatting

README.md
Updates the documentation on local testing
=> docs: update testing info

components/admin/LeftNav/BackLink.tsx, components/admin/Users/PermissionToggle.tsx, components/form-builder/icons/BackArrowIcon.tsx, components/globals/layouts/AdminNavLayout.tsx, pages/admin/accounts/[id]/manage-permissions.tsx, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-users.json
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2341
Updates manage permissions page
- Updates Page name / user name (email) stying
- Adds success / fail message when saving
- Replaces buttons with a toggle switch
- Adds back to accounts link (replaces left nav)
- From the permissions screen test toggling on / off permissions  
- Ensure permissions end up in the correct state for on / off. 
Are there any related issues …
=> Account permissions

pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/[id]/manage-permissions.tsx, pages/admin/accounts/index.tsx, public/static/locales/en/admin-forms.json, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-forms.json, public/static/locales/fr/admin-users.json
Adds delete form under manage forms -- re-uses the delete confirm code (under my forms)
- Test deleting a form under manage forms.
=> [deactivate] Delete user form

components/myforms/CardGrid/CardGrid.tsx, pages/myforms/[[...path]].tsx
Fixes a TypeScript issue that came up in `Add overdue warning to my forms` #2345
n/a
=> Fix card type

components/myforms/Card/Card.tsx, components/myforms/CardGrid/CardGrid.tsx, pages/myforms/[[...path]].tsx, public/static/locales/en/my-forms.json, public/static/locales/fr/my-forms.json
=> [deactivate] Add overdue warning to my forms

lib/ownership.ts
Fixes https://github.com/cds-snc/platform-forms-client/issues/2346
Adds emails for transfer ownership -- to be connected via https://github.com/cds-snc/platform-forms-client/pull/2365
- This isn't connected yet but sets up the initial code.
=> Transfer ownership email

components/admin/LeftNav/BackLink.tsx, components/form-builder/app/FormOwnership.tsx, components/form-builder/app/Settings.tsx, components/form-builder/app/Template.tsx, components/form-builder/app/navigation/LeftNavigation.tsx, next.config.js, pages/admin/accounts/[id]/manage-forms.tsx, pages/form-builder/edit/translate.tsx, pages/form-builder/settings/[formId]/form.tsx, public/static/locales/en/admin-users.json, public/static/locales/fr/admin-users.json
- Visit manage ownership via forms admin
- remove the back link url 
=> Add back link for form ownership

components/admin/Users/Dropdown.tsx, components/form-builder/app/FormOwnership.tsx, pages/admin/accounts/[id]/manage-forms.tsx
Some card style tweaks fixes #2376 #2375 
| <img width="724" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/6d9773c6-50ff-45c7-b712-7ac993943fa0"> | <img width="713" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/4a5e9cd2-2e91-46fd-a503-77529ff8ddeb"> |
| <img width="481" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/5b4e5076-8c05-4a19-b8ee-6f085fedc585"> | <img width="522" alt="image" src="https://github.com/cds-snc/platform-forms-client/assets/1187115/e1c01a0c-7720-425d-8c0e-6f4a1cca207e"> | …
=> Card fixes

pages/admin/accounts/[id]/manage-forms.tsx
Adds lang attribute to French titles on English interface and vice-versa.
Also flips english/french priority depending on selected language.
Fixes #2384 
=> manage-forms Form titles lang attributes

.eslint-tailwindcss.js, components/globals/AdminNav.tsx, pages/admin/index.tsx
Fixes #2385 
GC Forms logo should link to `/form-builder` and be titled `GC Forms`
Also fixes #2386 
Adds a h1 title to Admin home
=> Logo link and title

pages/admin/accounts/index.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2391
Limits which buttons are available for deactivated accounts.
- Deactivate an account - note which buttons are available
=> Manage active buttons for deactivated users

components/forms/Form/Form.tsx
=> feat: don't trigger gta event on preview submissions

components/form-builder/app/navigation/Header.tsx, pages/form-builder/settings/[formId]/form.tsx
The new Manage Ownership section on Form Settings should only be accessible to users with enough permissions (Admin).
Are there any related …
=> Control access to manage ownership

cypress/e2e/accounts_restricted.cy.ts
Add cypress test for `Restricted access`
- Cypress test
=> Restricted access page test

components/form-builder/app/FormOwnership.tsx, cypress/e2e/form-builder/admin-menu.cy.ts, cypress/e2e/form-builder/ownership.cy.ts
Tests:
- Only admin can assign owners
- Must have at least one owner
- Only display Administration menu link to Admins 
Are there any related …
=> Add some tests around Ownership and Admin menu

.eslint-tailwindcss.js, components/form-builder/app/Nagware.tsx, components/form-builder/app/responses/tests/DownloadTable.cy.tsx
=> Download table cypress test

.github/workflows/codeql-analysis.yml, .github/workflows/cypress.yml, .github/workflows/eslint.yml, .github/workflows/jest.yml, .github/workflows/pr-review-client-deploy.yml, .github/workflows/pr-review-client-remove.yml
This will configure github actions for testing and PR Review environments to run against branches off of long-running feature branches.
To work, the feature branch *must* be prefixed by `feature/*` ie, the name of this branch: `feature/enable_tests_and_review_envs_feature_branches`
Any PRs targeting a branch with the `feature/*` will trigger Jest, e2e, eslint, and PR Review environment workflows.
Test PR (targets this branch): https://github.com/cds-snc/platform-forms-client/pull/2438
=> Enable tests and review environments on feature branches

components/globals/YourAccountDropdown.tsx, cypress/e2e/form-builder/admin-menu.cy.ts
Fixes a cypress test
this issue that could be addressed in the …
=> Fix admin menu test

pages/api/account/security-questions/index.ts
- Removed useless get security questions for logged in user API path. Questions can be accessed through the session object.
=> refactor: removed useless get security questions for logged in user API path

.eslint-tailwindcss.js, lib/hooks/auth/useResetPassword.ts, pages/auth/resetpassword.tsx, public/static/locales/en/reset-password.json, public/static/locales/fr/reset-password.json
=> Connect setup security questions to API  - Answer questions PT 1

components/admin/Profile/EditSecurityQuestionModal.tsx, lib/auth/securityQuestions.ts, lib/hooks/auth/useResetPassword.ts, pages/auth/resetpassword.tsx, pages/profile.tsx
=> Connect profile and questions modal

components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/tests/DownloadTable.cy.tsx
All overdue (within overdueAfter threshold) items should be downloadable when account is restricted.
Previously, was using the higher-threshold warnAfter.
This will help a developer test things out without too much …
=> fix: DownloadTable should allow downloading of overdue items

lib/auth/securityQuestions.ts
- Sanitizing security answers. We are now removing punctuation, french accents and capitals (aka converting to lower case)
https://ricardometring.com/javascript-replace-special-characters
=> feat: sanitize security answers

next-env.d.ts, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
Fixes: 
#2421
#2275 
- Publish a form + test links from published page
=> chore: fix contact us links for published page

components/globals/Select/Select.tsx, pages/auth/setup-security-questions.tsx, public/static/locales/en/setup-security-questions.json, public/static/locales/fr/setup-security-questions.json
Connects the setup security questions API.
Try signing on with a new user. The security questions screen should show. Then try adding security questions.
- Add logic to stop a user from selecting an already select security question
- Clean up the form by creating custom form elements and removing the formik/custom mix that doesn't work well
- Cypress test
=> Connect setup security questions to api

components/form-builder/app/responses/DownloadTable.tsx
- Removed unused variable in DownloadTable.tsx
=> chore: removed unused variable in DownloadTable.tsx

pages/auth/setup-security-questions.tsx
Helps a user out by removing already selected questions.
Login with a new user and go to the security questions flow. Selecting a question should remove that question from the other two lists.
=> Adds question filtering

cypress/e2e/setup_security_questions_page.cy.ts, public/static/locales/en/setup-security-questions.json
Adds cypress tests for setup security questions page
=> Adds security questions page cypress tests

components/admin/Profile/EditSecurityQuestionModal.tsx
Updates the Answer check on the profile page to check "onChange" vs "onBlur"
- Test updating an answer on the profile page
=> Update answer check

pages/api/auth/[...nextauth].ts, prisma/seeds/fixtures/users.ts, prisma/seeds/seed.ts
Seeds test users with SecurityAnswers. Also creates a new User that does not have SecurityAnswers.
Are there any related issues or tangent …
=> Add seeds for SecurityAnswers

cypress/e2e/setup_security_questions_page.cy.ts
Updates security questions cypress test to use specific user type
Cypress test
=> Update Security questions test

cypress/e2e/security_questions_redirect_page.cy.ts, pages/auth/setup-security-questions.tsx
Adds a redirect to profile if a user visits setup security questions after already filling them in.
- Login 
- Fill in security questions
- Agree to policy ...
- Manually try to visit auth/setup-security-questions ... 
... this should redirect you to the profile page …
=> Redirect to profile from setup-security-questions

components/auth/Expired2faSession.tsx, components/auth/Verify.test.js, components/auth/Verify.tsx, public/static/locales/en/cognito-errors.json, public/static/locales/fr/cognito-errors.json
Fixes https://github.com/cds-snc/platform-forms-client/issues/2490
=> fix: error handling for 2FAExpiredSession

components/globals/Alert/Alert.tsx, components/globals/layouts/UserNavLayout.tsx, pages/auth/setup-security-questions.tsx, public/static/locales/en/setup-security-questions.json, public/static/locales/fr/setup-security-questions.json
=> Alert Banner

__tests__/api/acceptable-use.test.ts, cypress/support/commands/commands.ts, lib/auth/auth.ts, lib/auth/index.ts, lib/auth/securityQuestions.ts, lib/cache/acceptableUseCache.ts, lib/tests/auth.test.ts, next-env.d.ts, pages/api/acceptableuse.ts, pages/api/auth/[...nextauth].ts, pages/auth/setup-security-questions.tsx, pages/form-builder/index.tsx, pages/form-builder/responses/[[...params]].tsx, pages/form-builder/settings/branding-request.tsx, pages/form-builder/settings/branding.tsx, pages/profile.tsx, types/next_auth/index.d.ts
Modifies previous logic that added security questions array to the session.  
Replaced with:
- new property on the session that holds a boolean for `userHasSecurityQuestions`
- Once property is set to 'true' no more checks will occur during that session.
Chore:
- moved the `acceptableUseCache` module to `cache` folder
- modified new Cypress command to provide different answers for different questions to ensure proper future testing.
- Existing tests should pass
=> userHasSecurityQuestions property implementation

cypress/e2e/setup_security_questions_page.cy.ts, pages/auth/setup-security-questions.tsx, public/static/locales/en/setup-security-questions.json, public/static/locales/fr/setup-security-questions.json
Adds a duplicate answer check to the Setup Security Question page.
Navigate to the Setup Security Question page and try filling in a few answers that are the same. An error should be shown when trying to submit.
=> Adds duplicate answer check

components/myforms/Card/Card.tsx
Updates display for long form titles under my forms
- Login
- Visit my forms 
- Check card output based on feedback from https://github.com/cds-snc/platform-forms-client/issues/2521
=> chore: Form title line wrap

lib/auth/passwordReset.ts, lib/tests/auth/passwordReset.test.ts, lib/tests/templates.test.ts
- Added unit tests around new password reset library
=> chore: added unit tests around password reset library

public/static/locales/en/reset-password.json, public/static/locales/fr/auth-verify.json, public/static/locales/fr/reset-password.json
=> Translations: Security questions / Password reset

pages/admin/accounts/[id]/manage-permissions.tsx
- Added missing privilege in admin panel
=> fix: display missing privilege in admin panel

next-env.d.ts, package.json, pages/api/auth/[...nextauth].ts, yarn.lock
A bug in Next-Auth was ignoring the maxAge set in the JWT configuration object.
The sessions were defaulting to 30 days which is much longer than the 2 hours we have documented in our security controls.
I'll open a bug separately on Next-Auth however this solves the issue in the meantime.
| ![Screenshot 2023-08-14 at 10 49 10 AM](https://github.com/cds-snc/platform-forms-client/assets/25329319/c22db940-fdbc-4d73-b02a-15a75b5431a9) | ![Screenshot 2023-08-14 at 10 47 43 AM](https://github.com/cds-snc/platform-forms-client/assets/25329319/fe47a3d3-96fb-4407-b7f4-bb2620c77b20) |
Log into develop …
=> fix: token session

components/globals/SkipLink.tsx
Related: #2505 
- `<nav>` region around `Skip to main content` link is redundant/unnecessary https://webaim.org/techniques/semanticstructure/#regions
This will help a developer test things out without too much …
=> fix: Skip to main content redundant nav landmark region

public/static/locales/en/setup-security-questions.json
Fixes https://github.com/cds-snc/platform-forms-client/issues/2549
- Visit setup security questions page ... view banner 
=> chore: fix security questions banner text

components/admin/LeftNav/LeftNavigation.tsx, components/form-builder/app/navigation/LeftNavLink.tsx, components/form-builder/app/navigation/LeftNavigation.tsx, components/globals/LeftNavLink.tsx, components/myforms/LeftNav/LeftNavigation.tsx, next-env.d.ts
After reviewing #2553 found some other areas to cleanup.
- fixes classname order issues
- removes need to add fragments around child items
- removes w-38 classname (which doesn't exist)
Per #2553
The behavior and look of the lists should be unchanged. The only change should be that the lists are now in UL elements and the aria-current="page" should only be added to the current active item that is the displaying "page"
Nav Lists updated:
/form-builder/edit
/en/myforms/drafts
/admin/accounts
=> chore: cleanup for left navigation

components/globals/YourAccountDropdown.tsx
Updated account dropdown so it shows the admin link when the logged in account has access to update users
- Modify your permissions to only have access to manage users vs flags etc...
=> fix: Update account dropdown

pages/api/auth/[...nextauth].ts
- Added metadata to NextAuth error logs to help us understand why we are getting an intermittent `CLIENT_FETCH_ERROR ` error.
=> chore: added more context to NextAuth error logs

pages/api/auth/[...nextauth].ts
Should now fix the serialization issue when trying to get to the root of the next-auth error.
=> Fix: auth error reporting take 2

package.json, yarn.lock
=> bugfix: Downgrade Nextjs to fix language switching bug

pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/[id]/manage-permissions.tsx
Follow up for item missed in #2587 
Removes left nav from manage-permissions (like manage-forms)
Are there any related issues or tangent …
=> chore: Remove leftnav from manage-permissions

pages/admin/accounts/[id]/manage-forms.tsx, pages/admin/accounts/[id]/manage-permissions.tsx, public/static/locales/en/form-builder.json, public/static/locales/en/signup.json, public/static/locales/fr/form-builder.json, public/static/locales/fr/signup.json
=> Update content to be clear about where shared inboxes are supported

components/globals/layouts/FormDisplayLayout.tsx
Remove shared HeadMeta from frontend layout. The shared component includes a session check. There is no need for this overhead on the frontend forms, so just hardcode meta tags in frontend layout.
This will help a …
=> chore: Remove common HeadMeta from frontend layout

components/globals/ErrorPanel.tsx, lib/integration/freshdesk.ts, pages/api/request/publish.ts, pages/api/request/support.ts, pages/form-builder/support/[[...supportType]].tsx, pages/unlock-publishing.tsx
- Adds freshdesk handling for ticket create / support forms
- Adds error panel for error response if a request fails
- Remove or alter the API key
- Test support forms
=> chore: add freshdesk error handling

components/globals/Fip.tsx, components/globals/Header.tsx, components/globals/layouts/DefaultLayout.tsx, components/globals/layouts/UserNavLayout.tsx, pages/index.tsx, styles/_base.scss, styles/_header.scss
- Updates language selection page
- Update FIP to allow modifying margins and padding
|before|after|
|---|---|
|  <img width="800" alt="current" src="https://github.com/cds-snc/platform-forms-client/assets/62242/655242b9-d66c-491c-98e3-572d9d140f6a"> | <img width="900" alt="updated" src="https://github.com/cds-snc/platform-forms-client/assets/62242/77ca859c-2557-4160-8c06-f8b808a26e6c"> |
- Test new language selection page
- Ensure existing pages i.e. public facing form matches existing look and feel
=> refactor: update language selection page

bin/delete-ecs-task-defs.sh
Update the ECS task delete script so that it retrieves the currently active `form-viewer` task definition and prevents the deletion of that task definition.
Also reduces the sleep wait to speed up script execution.
- https://github.com/cds-snc/platform-core-services/issues/441
=> chore: add ECS task def delete safety check

components/globals/YourAccountDropdown.tsx, public/static/locales/en/common.json, public/static/locales/fr/common.json, public/static/locales/fr/profile.json
Updates a few missing localization strings in the profile area.
=> Updates a few localizations for profile

components/form-builder/app/Start.tsx, pages/form-builder/index.tsx, tailwind.config.js
Fixes: #2644
Updates start page https://7wvhwansataisbfupialqbfhvm0krhck.lambda-url.ca-central-1.on.aws/en/form-builder
| <img width="1240" alt="Screenshot 2023-09-15 at 9 46 42 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/401bf63b-6be1-4019-b93e-0290295a6031"> | <img width="1264" alt="Screenshot 2023-09-15 at 9 45 20 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/3266ec33-aab0-4f92-ab51-4195ff6a8aeb"> |
- No logic update ... styling only.
=> refactor: update start page

.github/workflows/prod-deploy.yml
Update the Production deploy workflow to use an OIDC role for authentication with AWS.
- cds-snc/platform-core-services#441
=> fix: switch to OIDC role for prod deploy workflow

.github/workflows/prod-deploy.yml, .github/workflows/staging-deploy.yml
Update the Sentinel deployment payload to include the correct product name.
Once this has merged and a Staging or Production deployment has occurred, validate that the product name is correct in Sentinel.
=> fix: Sentinel deploy metric product name

components/auth/AcceptableUse.tsx, components/form-builder/app/Published.tsx, components/globals/ErrorPanel.tsx, components/globals/Header.tsx, components/globals/layouts/UserNavLayout.tsx, components/myforms/FilterNav/FilterNavigation.tsx, cypress/e2e/acceptable_use.cy.ts, cypress/e2e/setup_security_questions_page.cy.ts, cypress/e2e/your_account_user_profile.cy.ts, lib/auth/auth.ts, pages/admin/index.tsx, pages/auth/login.tsx, pages/auth/policy.tsx, pages/auth/setup-security-questions.tsx, pages/form-builder/support/[[...supportType]].tsx, pages/forms/[[...path]].tsx, pages/signup/account-created.tsx, pages/signup/register.tsx, pages/unlock-publishing.tsx
- Updates url from "/myforms" to "/forms"
- Removes useEffect redirect to /all --- all is the default now.
- Test what used to be paths leading to "/myforms" --- all paths should now direct to "/forms"
=> refactor: change "/myforms" url to "/forms"

lib/integration/freshdesk.ts, lib/tests/freshdesk.test.ts
Removes placeholder `XYZ` from ticket subject lines
Test request publish form
=> chore: update ticket subject lines

components/form-builder/app/navigation/SubNavLink.tsx, components/myforms/CardGrid/CardGrid.tsx, components/myforms/FilterNav/FilterNavigation.tsx, pages/forms/[[...path]].tsx, public/static/locales/en/my-forms.json, public/static/locales/fr/my-forms.json
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2702
- Updates forms nav to add current page
- Updates forms nav to add ids
- Updates Cards to ensure titles etc... have unique ids across all tabs.  Added "draft", "published", or "all" to the ids
Test "all", "drafts", "published" filter nav for a11y
=> fix: Forms nav fix aria label and ids

components/myforms/Card/Card.tsx
Updates the published banner text colour from white to black on the emerald background to fix contrast issue.
Check /forms using a scanner i.e. Axe
=> chore: a11y update card banner text colour

components/auth/AcceptableUse.tsx, components/auth/Verify.tsx, components/form-builder/app/Preview.tsx, components/globals/Alert/Alert.tsx, components/globals/ErrorPanel.tsx, pages/auth/login.tsx, styles/_typography.scss
Some typography tweaks:
- Ensures the form preview on the Test page renders the title and FIP with frontend styles.
- Adjust inline sizing of hint text on Auth pages 
- Adjust margin on titles in Alerts
- Adjust red underline of H1 headings on fontend forms
them such as any environmental setup steps and/or any …
=> fix: Adjust title and FIP in Preview on Test page to more closely match frontend styles

components/form-builder/app/edit/elements/lexical-editor/Editor.tsx
=> fix: Render frontend fonts/styles in RichTextEditor

components/form-builder/app/Preview.tsx
Updates the preview FIP header to bring it back inline with the current front facing output 
- Test preview output of a form under the form builder tool
=> chore: update preview header

components/globals/layouts/DefaultLayout.tsx, components/globals/layouts/FormDisplayLayout.tsx, pages/sla.tsx, pages/terms-and-conditions.tsx, pages/terms-of-use.tsx
- Updates the max width for 
```
/terms-of-use
/sla
/terms-and-conditions.tsx
```
- Updates padding . margins for the "page container" so things line up with the FIP across breakpoints
- Visit pages listed above ... note they no longer span the full width.
<hr>
- Test content pages at smaller breakpoints to ensure alignment 
- Test public facing form output across the same breakpoints
=> refactor: update max with for static pages

components/form-builder/app/navigation/LeftNavigation.tsx
Update alignment for responses in the left navigation
| <img width="356" alt="Screenshot 2023-09-27 at 3 56 44 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/af667ff6-1dbd-4071-802e-8958698984ef"> | <img width="377" alt="Screenshot 2023-09-27 at 4 00 47 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/ac9605b3-c972-4d35-aae1-43274d6ea934">|
- Check alignment for responses icon in the left nav
=> chore: update responses icon alignment

components/form-builder/app/edit/elements/question/QuestionInput.tsx
Updates the form-builder question input text size to be smaller (2xl vs 3xl).
=> Updates question input text size

components/globals/Buttons/LinkButton.tsx, components/globals/layouts/UserNavLayout.tsx, pages/auth/logout.tsx, pages/auth/resetpassword.tsx, pages/signup/register.tsx, styles/_forms.scss, styles/_typography.scss
Fixes: #2730
- Fixes button on sign-out page to not have bold text.
- Updates hint text on register and reset password forms.
- Updates "Know your responsibilities" page.
=> chore: text sizing updates

components/form-builder/app/shared/Tooltip.tsx, package.json, yarn.lock
Adds a tooltip component.  
To be used in https://github.com/cds-snc/platform-forms-client/pull/2739
i.e. figma design
- This PR doesn't use the component yet it just sets it up.
For now if you want to try it you can 
```javascript
<Tooltip text="my tooltip text">
<button>my</button>
</Tooltip>
```
=> chore: Add tooltip component

components/form-builder/app/Preview.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2682
- Check preview screen and ensure background colour is now white
=> chore: ensure white background for preview screen

components/forms/Label/Label.tsx, next-env.d.ts
Updates all required message to use lang option
Fixed Output:
https://htykqyrdhzxpsunpg6yeoewmdy0gvjoc.lambda-url.ca-central-1.on.aws/fr/id/clnlwihhv0000mm7wncgdh7qw
- Create a new form and add the attestation block
- Ensure the required label shows in the correct language
=> fix: all required message

next-env.d.ts, prisma/migrations/20231023125640_template_closing_data/migration.sql, prisma/schema.prisma
In support of https://github.com/cds-snc/platform-forms-client/pull/2792
Adds closing date migration.
=> chore: Add closing date to db

lib/tsUtils.ts
Adds SVG mime time to image upload
=> Add SVG mime type

pages/admin/accounts/[id]/manage-forms.tsx
Update to fix issue deleting a form via admin / manage forms.  This page was missing the `TemplateStoreProvider`
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2814
- Navigate to manage forms via admin account page
- Delete a form
=> fix: Fix manage forms delete

package.json, yarn.lock
Adding node-gyp to dependancies to fix an issue with NPM / Yarn 1.x 
see: https://github.com/yarnpkg/yarn/issues/3728#issuecomment-1737249792
>  This package requires node-gyp, which is not currently installed. Yarn will attempt to automatically install it. If this fails, you can run "yarn global add node-gyp" to manually install it.
=> chore: Add node-gyp

lib/responseDownloadFormats/json/index.ts, pages/api/id/[form]/submissions/download.ts
Adds a JSON transformer for the downloadable JSON option
- Removes the form block from the FormResponseSubmissions type and just returns the submissions themselves.
- Formats the date
Also includes a small refactor of download.ts to switch/case format.
=> Add JSON Transformer

components/form-builder/app/responses/DownloadTable.tsx
Refactors DownloadTable error states for clarity/simplicity
=> Refactor error states on DownloadTable

components/form-builder/app/responses/CheckAll.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/DownloadTableReducer.ts
Refactors CheckAll to a separate component. No functionality changes, just moving to a separate component to tidy up the DownloadTable component.
=> Refactor CheckAll to separate component

pages/api/submit.ts
Following the same pattern in the application for the other Lambda function calls by referencing a hardcoded value.
Simplifies the Infra as Code by not having to pass in an additional value that is already known.
- Submit a form
- Everything should submit a-ok
In the tv show Loki how could you reach 'the end of time' when time itself is an infinite scaling problem.  
=> chore: remove unrequired env var

components/form-builder/app/responses/ActionsPanel.tsx, components/form-builder/app/responses/DeleteButton.tsx, components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx
Only display the Delete button when viewing New responses.
Includes small refactor of ActionsPanel
=> Only show Delete on New Responses screen

components/form-builder/app/responses/DownloadTable.tsx, components/form-builder/app/responses/MoreMenu.tsx
Holding off on completing implementation of the Delete new responses feature, so hiding the button.
=> Hide delete new responses button

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx
=> Additional check for formID

pages/form-builder/responses/[[...params]].tsx, public/static/locales/en/form-builder-responses.json, public/static/locales/fr/form-builder-responses.json
Adds Report a problem link below the DownloadTable
=> Report a problem link

pages/form-builder/responses/[[...params]].tsx
Ensures that the parsed formID from the URL is not later used by client components as it is not sanitized.
=> fix:  Code QL security warning

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx
Fixes issue with JSON input label.
=> fix json label

components/form-builder/app/responses/Dialogs/DownloadDialog.tsx, lib/responseDownloadFormats/csv/index.ts
Adds a note to the CSV about where to find the confirmation codes
=> Add confirmation code note to csv

components/globals/card/Card.tsx
Issue -- card jumps between cards and content.
https://github.com/cds-snc/platform-forms-client/assets/62242/a3448083-9447-4f01-8132-83b95dd5b4b6
=> Fix content jumping for card

components/form-builder/app/responses/Dialogs/ConfirmDialog.tsx, lib/clientHelpers.ts, lib/tests/clientHelpers.test.js, lib/tests/vault.test.ts, lib/vault.ts
- make DynamoDB requests run synchronously
=> fix: run promises synchronously when making requests to DynamoDB

components/admin/LeftNav/BackLink.tsx, components/form-builder/icons/BackArrowIcon.tsx, components/globals/layouts/FormBuilderLayout.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3078
Moves backlink out of the Left Navigation and into the main content area.
=> chore: Move back link

pages/api/id/[form]/submission/report.ts, pages/api/request/publish.ts, pages/api/request/support.ts
Add more detailed log message for support ticket 400 errors
=> chore: update support error message logs

.github/workflows/codeql-analysis.yml
CodeQL is the code analysis engine developed by GitHub to automate security checks. You can analyze your code using CodeQL and display the results as code scanning alerts.
Inspiration: https://github.com/auth0/nextjs-auth0/blob/main/.github/workflows/codeql.yml
Also getting rid of this warning
=> Refresh codeql analysis job workflow

components/form-builder/app/edit/elements/element-dialog/tests/ElementDialog.test.js, lib/formBuilder.tsx, lib/hooks/useValueChanged.tsx, lib/tests/formBuilder.test.js, lib/validation.tsx
Fixes validation issue where a fields not in the `current` group were being validated but not on the screen.
=> fix: group validation

components/form-builder/app/branding/options.ts
Related to acceptance criteria in #2892
=> chore: update name of health canada branding option

app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx
Closes: https://github.com/cds-snc/platform-forms-client/issues/3166
=> Fix closed page layout

app/(gcforms)/[locale]/(form administration)/form-builder/published/clientSide.tsx, components/clientComponents/form-builder/app/Publish.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3179
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3161
=> Published flow

app/api/settings/[internalId]/route.ts, app/api/settings/route.ts
closes: #3222 
Wrong param was being referenced in GET request.
=> fix: settings api endpoint

components/form-builder/app/branding/Branding.tsx, public/static/locales/en/form-builder.json, public/static/locales/fr/form-builder.json
=> chore: update branding settings to link to new form

components/clientComponents/myforms/Card/Card.tsx
Fix links from being escaped
Fixes: #3170
=> Fix link escape

components/clientComponents/form-builder/app/shared/SaveButton.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3238
=> fix initial save button

prisma/seeds/fixtures/security-questions.ts, public/static/locales/fr/form-builder.json
Tiny updates to a few FR copy strings.
=> chore: small content tweaks found while testing

components/form-builder/app/edit/ModalForm.tsx
=> Fix: String ID showing up rather than text itself

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/page.tsx, components/clientComponents/form-builder/app/Publish.tsx, components/clientComponents/form-builder/app/Published.tsx, components/clientComponents/form-builder/app/index.ts, components/serverComponents/form-builder/LoggedOutTab.tsx, components/serverComponents/globals/Buttons/LinkButton.tsx, components/serverComponents/globals/InfoCard/InfoCard.tsx, components/serverComponents/globals/card/Card.tsx, package.json, yarn.lock
=> feature: Publish flow

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/layout.tsx, app/(gcforms)/[locale]/(app administration)/admin/(with nav)/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/DeliveryOptionEmail.tsx, app/(language selection)/page.tsx, app/layout.tsx, components/clientComponents/admin/LeftNav/NavLink.tsx, components/clientComponents/admin/Users/ConfirmDeactivateModal.tsx, components/clientComponents/auth/LoginMenu.tsx, components/clientComponents/form-builder/app/navigation/LinksSubMenu.tsx, components/clientComponents/form-builder/app/navigation/SubNavLink.tsx, components/clientComponents/form-builder/app/navigation/TabNavLink.tsx, components/clientComponents/form-builder/app/shared/SaveButton.tsx, components/clientComponents/globals/Buttons/LinkButton.tsx, components/clientComponents/globals/Buttons/themes.ts, components/clientComponents/globals/Header.tsx, components/clientComponents/globals/NavLink.tsx, components/clientComponents/globals/StyledLink/StyledLink.tsx, components/clientComponents/globals/YourAccountDropdown.tsx, components/clientComponents/globals/layouts/UserNavLayout.tsx, components/clientComponents/myforms/MenuDropdown/MenuDropdown.tsx, components/clientComponents/myforms/Tabs/Tab.tsx, components/serverComponents/globals/Buttons/LinkButton.tsx, styles/_base.scss, styles/_forms.scss
Update to remove box shadow from a tags
=> Remove box shadow

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Modal.tsx
Fixes issue where navigating to edit would always focus on the last input element.
=> Fix edit focus issue

styles/_base.scss
=> Style cleanup

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditNavigation.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, components/serverComponents/icons/RightPanelOpen.tsx, components/serverComponents/icons/index.ts, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, package.json, yarn.lock
=> Add right panel

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Adds route and tab for "logic"
=> Add logic page

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/ErrorSaving.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SaveButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, next.config.mjs
Fixes save issue when leaving edit page
=> Fix save auto save issue

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SaveButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/page.tsx, lib/hooks/form-builder/index.ts, lib/hooks/form-builder/useTemplateContext.tsx, lib/store/useTemplateStore.tsx
Add timer to avoid multiple saves happening when first loading the edit page.
=> Check "mounted" time before saving

lib/auth/passwordReset.ts
The function checking if a user has security questions was using the raw input from the form instead of using the sanitized user email address.
This allowed a user to be found in the first step but returned that they did not have security questions in the second.
Fixing this reduces pressure on support as users will be able to reset their password even if they mistakenly input an email address with capital letters.
1. Use password reset page
2. Enter email address with capital letters (First.Last@somewhere.com)
3. After receiving password reset email the link should bring you to the question response page.
=> fix: Password reset is case sensitive for user emails

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Node.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/data/index.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/hooks/useDynamicTree.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/index.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/types.tsx, lib/formContext.ts, lib/hooks/form-builder/useHandleAdd.tsx, lib/store/index.ts, lib/store/useTemplateStore.tsx
=> Tree view - PT2

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx
=> Tree view - pt 3

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Node.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/data/index.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/hooks/useDynamicTree.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/index.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/types.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/groupsToTreeData.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/treeDataToGroups.ts
=> Tree view 3

flag_initialization/default_flag_settings.json, public/static/locales/en/admin-flags.json, public/static/locales/fr/admin-flags.json
=> Add conditionalLogic flag

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/published/Published.tsx
=> Fix Published link

components/clientComponents/globals/SubNavLink.tsx
Fixes focus state for sub nav links
=> Fix sub nav links

__utils__/mocks/server-actions/getTranslatedElementProperties.ts, __utils__/mocks/server-actions/index.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/NewSection.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/RichTextLocked.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, jest.config.ts, lib/hooks/form-builder/index.ts, lib/hooks/form-builder/useHandleAdd.tsx
Fixes #3371
Addresses issue when loading translations for a specific language in the new client side translation hook by pulling those translations from a server action.
=> Translated hint text

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/conditionals/ConditionalIndicatorOption.tsx
Fixes conditional option output
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3369
=> Fix option output

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Edit.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts
Adds a redirect to Edit when form is already published.
=> Add Redirect from edit for published form

app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/conditionals/AddOther.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3411
=> Get server translated props for "Add other"

__utils__/mocks/server-actions/index.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/Options.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/index.ts
=> Remove AddOther from barrel file and add mock

components/clientComponents/globals/Header/Header.tsx
Updates Header to have less forms :) 
(right Forms link is removed and left Forms text becomes a link)
=> Updates header forms link

lib/auth/cognito.ts
fixes: #3437 
| ![image](https://github.com/cds-snc/platform-forms-client/assets/25329319/2410767b-e1bd-443b-9b00-fb45059d4083) | ![image](https://github.com/cds-snc/platform-forms-client/assets/25329319/185204f1-dadb-46ad-93c6-7cba1e10a076) |
=> fix: bad credentials error

app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts
closes: #3434 
Ensures proper error is returned when MFA is invalid
|![image](https://github.com/cds-snc/platform-forms-client/assets/25329319/d2298a77-9ebe-4c6a-b482-9a652c603ff2) | ![Screenshot 2024-04-03 at 08-20-35 Check your email for a security code](https://github.com/cds-snc/platform-forms-client/assets/25329319/ad9bc8e4-e44b-4e5c-8575-065351fb0cd1)|
=> fix: MFA invalid error

app/(gcforms)/[locale]/(form administration)/form-builder/Start.tsx
=> Start - add click handler to upload

app/(gcforms)/[locale]/(user authentication)/auth/account-created/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/login/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/logout/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/mfa/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/register/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/page.tsx, app/(gcforms)/[locale]/(user authentication)/auth/setup-security-questions/page.tsx, app/(gcforms)/[locale]/(user authentication)/layout.tsx
fixes: #3441
Use new 'has' css variant to set styling of parent components in layout based on page children.
=> fix: Content widths on auth pages

app/(gcforms)/[locale]/(user authentication)/auth/mfa/components/client/MFAForm.tsx
There is no issue created for this PR however I noticed while working on another branch that the MFA screen flickered and errors were being reported in the console.
|![old_mfa](https://github.com/cds-snc/platform-forms-client/assets/25329319/d20c1269-eb0d-4e3e-98cd-371832aad8de)|![new_mfa](https://github.com/cds-snc/platform-forms-client/assets/25329319/b61164c2-d453-48f4-b51e-74b74c20fec8)|
- Navigate to the `/auth/mfa` page without an active session
=> fix: SSR Error and page flash on MFA

.env.example, README.md
Goes with https://github.com/cds-snc/forms-terraform/pull/620
- Updated `.env.example` file to clean-up variables that were not being used anymore. Also tweaked some variables so that the web application can take advantage of the Redis/PostgreSQL deployed in Localstack.
- Updated `README.md` to reflect all recent changes made to the web application. Also fully removed the French translation since it was way more outdated than the English one.
=> chore: update .env.example and README file to reflect changes around Redis and PostgreSQL in Localstack

public/static/content/fr/sla.md
fixes : https://github.com/cds-snc/platform-forms-client/issues/3464
Fix pdf links
=> Fix fr sla links

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Dialogs/ReportDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Responses.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/ResponsesFooter.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/TitleAndDescription.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/layout.tsx
=> Bugfix- prevent conflicting display states after moving responses

lib/hooks/useGCFormContext.tsx
Adds ability to check and match against an array of next actions.
=> Handle multiple next action

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/logic/Flow.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/page.tsx, package.json, yarn.lock
=> Add React flow

__fixtures__/testDataWithGroups.json, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/__tests__/findParentGroup.test.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/initializeGroups.ts, app/(gcforms)/[locale]/(form administration)/form-builder/page.tsx, lib/store/useTemplateStore.tsx
Pass allowGroups flag into useTemplateStore instead of querying within.
Also fixed findParentGroup test
Also fixed an initializeGroups bug
=> Improved allowGroups flag handling

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/logic/Flow.tsx, styles/_form-builder.scss
=> Connect flow to groups

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/__tests__/findParentGroup.test.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/__tests__/setNextAction.test.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/setNextAction.ts
Adds utility function to auto-set the next action based on the next item in the object if it exists.
=> Add util function to auto-set next action

next.config.mjs, nextCacheHandler.mjs
Introduces changes suggested by Wissam in PR #3475
=> fix: Reduce mem cache size and simplify config logic

i18n/index.ts, middleware.ts
Depending on the layout entry point the x-path isn't always set.
This PR makes an updates to try to use cookieLang as a backup.
=> Use cookieLang as backup for locale

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/provider/FlowRefProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/GroupOutput.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/store/useGroupStore.tsx, lib/store/useTemplateStore.tsx
Adds a ref provider so we can update the flow state from the outside.
=> Add flow provider ref

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx
Adds code to allow moving from section to section without the need to select a question.
=> Move section to section - next actions

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/GroupOutput.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx
Updates click handling between sections and questions.
=> Update next actions selectors

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useAutoLayout.ts
Update to expose run layout allowing the flow layout to auto layout when the edges are updated.
=> Re-run auto layout

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/lexical-editor/tests/RichTextEditor.cy.tsx, utils/reliabilityQueueTableTTLDataTypeMigration/.env_example, utils/reliabilityQueueTableTTLDataTypeMigration/change_ttl_data_type_from_string_to_number.ts, utils/reliabilityQueueTableTTLDataTypeMigration/package.json, utils/reliabilityQueueTableTTLDataTypeMigration/tsconfig.json, yarn.lock
Fixes merge conflicts to merge develop into nextjs_app_router
=> chore: Update branch with latest develop

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/GroupSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/initializeGroups.ts, styles/_form-builder.scss
=> Logic updates

.github/workflows/release_generator.yml
Update release-please generator to latest version.
=> chore: update release generator

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx
Renders custom TreeView items
Prevents dropping a group after Review
=> Render custom TreeView Items

lib/integration/notifyConnector.ts
- JSON stringify error request Axios object
=> chore: JSON stringify error request Axios object (only when not in production but it should still be removed entirely when not needed anymore)

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/question/Question.tsx, lib/store/useTemplateStore.tsx
Hides Question numbers when conditional logic / groups is enabled
=> Remove q numbers when groups enabled

__utils__/mocks/file-type/index.ts
=> File buffer lint

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SectionTitle.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/types.tsx
Prevent renaming of locked section titles
=> Prevent rename locked sections

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/useFlowData.tsx, styles/_form-builder.scss
Updates arrow heads and line styles
=> Update flow line styles

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleCanDropAt.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleOnDrop.ts
Refactors some TreeView handlers to separate files for readability/testability.
=> Refactor TreeView handlers

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/FlowWithProvider.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/ChoiceSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/ClearMultiRules.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/GroupSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/initializeGroups.ts
- Fixes issue with zoom ... doesn't run fitView if the user has zoomed in.
- Fixes label display adds truncate + wrapping so text doesn't sit under arrow.
- Adds empty option for selects "Select an option" to ensure it doesn't look like a rule is set when it isn't.
- Adds clear nextAction for group when multiple actions are set and you want to override at the section level.
- Prevents pointing review to anything other than "end" / "submit"
=> Logic fixes

lib/utils/form-builder/formHasGroups.ts, lib/utils/form-builder/getLayoutFromGroups.ts, lib/utils/form-builder/index.ts, lib/vitests/formHasGroups.test.ts, lib/vitests/getLayoutFromGroups.test.ts
Adds utilities to sync group layout with group element order
Note: this is hardcoded to not be used yet.
=> Add util to sync layout array with group elements

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx
=> Next actions fix issue passing the wrong id

.eslint-tailwindcss.js, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Edit.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, styles/_form-builder.scss
ref: 
https://github.com/cds-snc/platform-forms-client/issues/3192
https://github.com/cds-snc/platform-forms-client/issues/3243
Before:
=> Fix:  Checkbox / Radio styling in form builder 

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/layout.tsx
Updates right panel to fix to use choice ids an the parent of for the selectors
=> Handle next actions via multiple questions

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx
Fixes the RightPanel overlapping and running over the Footer
=> Fix right panel height

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx
Accidentally removed in previous PR
=> Re-add fixed class to open panel link

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/ChoiceSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/ClearMultiRules.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/GroupSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleOnDrop.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/groupsToTreeData.ts, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, lib/formContext.ts, lib/hooks/useElementTitle.tsx, lib/vitests/nextaction.test.ts
Update to handle catch-all action across multiple choice selects
=> fix multiple catch alls

app/api/id/[form]/submission/confirm/route.ts
We've experienced DynamoDB beginning to throttle the response confirmation requests. It returned a ThrottlingException to the caller.
```
{"level":"error","time":1713791577367,"err":{"type":"DynamoDBServiceException","message":"Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html","stack":"ThrottlingException: Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: …
```
=> chore: DynamoDB retry with exponential backoff

app/(gcforms)/[locale]/(form administration)/forms/components/server/Card.tsx
https://github.com/cds-snc/platform-forms-client/assets/62242/8cd390a1-3834-4b63-8600-3354ff85695c
=> Fix "forms" icon fill when active

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, lib/types/form-builder-types.ts
Update settings page error handling
=> Settings page - error handling

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx
Update choices to filter / remove "used" choices
https://github.com/cds-snc/platform-forms-client/assets/62242/a66a664b-66d1-4da5-a43a-3c4a688094a2
=> CL: Groups Filter choices

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/ChoiceSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx
Adds change key update for next actions to ensure an array of actions triggers a render / update.
=> Use change key - from multi-next actions

app/(gcforms)/[locale]/(form administration)/form-builder/Start.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/ConfirmDelete.tsx, app/(gcforms)/[locale]/(form administration)/forms/components/ResumeEditingForm.tsx, app/(gcforms)/[locale]/(form administration)/forms/components/client/ConfirmDelete.tsx, app/(gcforms)/[locale]/(user authentication)/components/client/LoginMenu.tsx, components/clientComponents/globals/Header/YourAccountDropdown.tsx, lib/hooks/__tests__/useAllowPublish.test.tsx, lib/store/defaults.ts, lib/store/storage.ts, lib/store/types.ts, lib/store/useTemplateStore.tsx, lib/store/utils.ts, lib/utils/form-builder/index.ts
- Updates move up / move down to add a group option
-  Update to useTemplate store to break out the types and util files --- just moving things around to make the file smaller and easier to work with.
=> Update element move up / move down to work with Groups

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, lib/store/types.ts, lib/store/useTemplateStore.tsx
Update duplicate element code to work with groups
Fix for https://github.com/cds-snc/platform-forms-client/issues/3716
=> Handle duplicate for groups

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Add translations strings for TreeView
=> Add translation strings for TreeView

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/Tooltip.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/ItemActions.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/KeyboardNavTip.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
https://github.com/cds-snc/platform-forms-client/assets/62242/9179aeb9-232c-44a2-bc74-6ff584b6ef84
=> Add keyword tip for TreeView

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, lib/hooks/__tests__/useAllowPublish.test.tsx, lib/hooks/form-builder/useAllowPublish.tsx
Fixes skipped test from https://github.com/cds-snc/platform-forms-client/pull/3763
Also adds a couple of notes and renames some variables to bring a little more clarity.
=> Fix allow publish test

.github/workflows/release_generator.yml
Move release target branch back to develop.
=> Update target branch

.github/workflows/release_generator.yml
Changes the trigger on the Release Please generator back to develop
=> fix: Trigger release generation on develop branch

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsPanel.tsx
Fixes issue where template possibly doesn't exist when trying to save via the quick panel
Bug
https://github.com/cds-snc/platform-forms-client/assets/62242/ad251364-0f36-441a-84b6-86c04cad782c
=> Fix saving from quick panel

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/processFormData.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/actions.ts, app/(gcforms)/[locale]/(user authentication)/auth/mfa/resend/components/client/ReVerify.tsx, lib/auth/cognito.ts
Reverts cds-snc/platform-forms-client#3801
Happy path for token resend is broken
=> Revert "chore: Update error handling for 2fa"

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts
Mistakenly introduced in PR #3825
=> Remove isUUID check for formID

app/(gcforms)/[locale]/(user authentication)/auth/register/action.ts, app/api/id/[form]/submission/confirm/route.ts, lib/auth/cognito.ts, lib/integration/notifyConnector.ts, lib/vault.ts
- Adds first batch of HealthCheck logs to feed monitoring dashboard in CloudWatch
=> chore: add first batch of healthcheck logs

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalFormRules.tsx, lib/utils/form-builder/index.ts
- Includes a minor update to the sortByLayout function to operate on a copy of the elements array rather than the elements array itself.
- Adds a sortByGroups util function
- Fixes #3702
=> Fix: Sort questions in Add Rule question list

lib/auth/nextAuth.ts
Remove the logs that are created each time a user enters an invalid MFA code.
=> chore: reduce logging noise

README.md
Minor doc update to avoid new devs getting hydration errors like me in cypress testing!~ :)
=> * Update doc about hydration errors.

middleware.ts
The current middleware was behaving unexpectedly with the current matcher array.  The documentation was not clear that the array represents a logical OR between matchers and not a logical AND.  The matchers were originally seperated for readability but have now been combined to ensure proper functionality.
Discovered because `favicon.ico` was having a language parameter added to it's path by the middleware which in turn caused the browser to receive a 404 when requesting the redirected path.
- Open browser and navigate to the site.
- Ensure favicon is displayed in the browser tab.
=> fix: Add file extention check into single middleware matcher.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/Section.tsx
=> chore: Fix section padding

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/handlers/handleOnDrop.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/setNextAction.ts, lib/hooks/useAutoFlowAll.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3788
Adds a hook for AutoFlow all --- this is a temporary fix until we have a better solution.
=> chore: Add temporary fix for AutoFlow issues

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/EditableInput.tsx
Fixes: #3860
Updates TreeView to rename section input when blurred.
https://github.com/cds-snc/platform-forms-client/assets/62242/e7262ab8-103b-4291-9bdb-cfb97dad14a1
=> chore: Rename section on blur from TreeView

app/api/notify-callback/route.ts
Add healthcheck logging for Notify callback behaviour.   This will allow us
to monitor callback behaviour on the service health dashboard.
1. Happy path: submit a form with a valid email address and expect to see the log that no reprocessing is required.
2. Unhappy path: submit a form with an invalid email address and expect to see the permanent failure log message. 
None
=> feat: add healthcheck logs for Notify callback

lib/managedData/data/organizations.json
Updates department list from gc-organizations.
Test by making sure a new org is in the department dropdown, for example:
EN: Office of the Secretary to the Governor General
FR: Bureau du secrétaire du gouverneur général
=> chore: Updates department list from gc-organizations

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/actions.ts, app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/clientSide.tsx, app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/components/TextInput.tsx, app/(gcforms)/[locale]/(app administration)/admin/(no nav)/view-templates/page.tsx, i18n/translations/en/admin-templates.json, i18n/translations/fr/admin-templates.json
Adds:
- Form ID
- Updated At in local timezone
- Ability to sort by latest published forms
Removes
- Ability to override publishing
- Direct link to Edit form
Cough Cough... I'm not a designer and this is only an interim immediate solution.
Designs will need to be created with Supports input to ensure we have a tool that supports their flows.
| ![Screenshot 2024-07-04 at 3 37 11 PM](https://github.com/cds-snc/platform-forms-client/assets/25329319/d36b616a-90ca-4370-b714-972b35f98a81) | ![Screenshot 2024-07-04 at 3 34 09 PM](https://github.com/cds-snc/platform-forms-client/assets/25329319/5592416 …
=> chore: fixes template view in adminstration panel

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/PrePublishDialog.tsx
Fixes #3978
To test, open a form ready to publish, click publish. In the modal, continue to the 2nd step, and then open the dropdown.
=> * Fix Display Issue with Prepublish Dropdown on Staging

i18n/translations/en/form-builder.json, i18n/translations/fr/common.json, i18n/translations/fr/form-builder.json
=> fix: Offboarding content translations and tweaks for form exit

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ConfirmationTitle.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SectionTitle.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/GroupNode.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/Legend.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/SectionNameInput.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/GroupSelect.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SectionName.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/EditableInput.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/TreeView.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Change made in response to findings from diary study.
https://miro.com/app/board/uXjVK4Bp0Ho=/
=> fix: Change "sections" to "pages" throughout

__fixtures__/sections-out-of-order.json, i18n/translations/en/common.json, i18n/translations/fr/common.json
Fixes #3962 
- Beginning --> Start page
- Privacy --> Privacy statement
- Review --> Review page
- End --> Confirmation page
Fixes #3848 
- Logic --> Branching
- Rules clarification
=> chore: Consistent terminology for conditional logic

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/conditionals/ConditionalIndicatorOption.tsx
Updates code to use a button vs a span for the add rule "link"
=> chore: use add button for add rule

.github/CODEOWNERS
Adds additional individuals to code owners file
=> chore: update code owners file

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/flow/Legend.tsx, components/serverComponents/icons/LogicOptionArrowIcon.tsx, components/serverComponents/icons/LogicSectionArrowIcon.tsx
Updates legend icons for branching view.
=> chore: update legend icons

i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
=> chore: Clarify content for branching visualization legend

components/clientComponents/globals/Header/Header.tsx, components/clientComponents/globals/SkipLink.tsx, components/serverComponents/globals/SkipLink.tsx
Minor fixes as requested by design.
=> Fix: Tiny Banner Fixes

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/LogicNavigation.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/logic/components/ResetFlowDialog.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Closes #3988
To test:
1. Open Form
2. Go to Logic View
3. Click the Tiny Logic Reset Button
4. Dialog occurs!~
5. Cancel to not, Confirm to!
=> feat: Add dialog 'are you sure' for logic reset.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Closes #3846
To test:
-> Go to publish view with Publish rights.
=> chore: Add warning for logic flow "Double check your work"

i18n/translations/en/form-builder.json
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4090
Fixes issue from https://github.com/cds-snc/platform-forms-client/pull/4073 where some stings we're accidentally moved up a level.
=> chore: Fix nesting for logic strings

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalFormRules.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ModalRules.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/4087
- Update code to toggle panel open.
- Updates some CSS Tailwind order issues + unknown `border-dark-gray` class
https://github.com/user-attachments/assets/48a7e340-63a7-41a5-bc64-009db8f2cc78
=> chore: Toggle panel open from modal view

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx
Adds overflow scroll and sticky to panel nav for next actions
https://github.com/user-attachments/assets/3610fb4a-ceb0-4fed-b274-3e6f71b4c330
=> chore: add scrolling for next actions panel

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/MultiActionSelector.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SelectNextAction.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/logic/SingleActionSelect.tsx, lib/utils/form-builder/i18nHelpers.ts
Fixes #4064 
Also fixes references to logic strings that have been moved to common.json translation file.
=> (fix): English strings in French branching/logic dropdowns

i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
A few more content tweaks in EN and FR for concision, clarity, consistency, ahead of release! :D
=> chore: A few more copyedits

components/clientComponents/globals/Header/Header.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Closes #4092
This swaps the banner if Logic is on!~
To test: Have feature flag off. Then have it on.
=> feat: * Swap banner if Logic is on.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SelectedElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx
Updates code for button text when settings translation lang priority.
=> chore: update button text for repeating sets

public/static/content/en/terms-of-use.md
https://gcdigital.slack.com/archives/C01GFD150MC/p1723123041318829
=> fix: small typo in terms of use

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/actions.ts, lib/users.ts
This PR fixes a bug where an error was being thrown when a user accesses the responses page directly when using the "0000" temporary form ID.  This use case was probably occurring when a user bookmarked the responses page with the "0000" id in the url.
The logic set to redirect a user at the layout level was wrapped in a try / catch which did not allow the `redirect` to properly bubble up to the NextJS Router.
The `fetchSubmissions` function was also checking for a formID of "0000" to short circuit but undefined was being passed in as it is the value stored in the TemplateStore for a draft form.
A small refactor was done on `getUnprocessedSubmissionsForUser` in `lib/users` to remove an unused argument that was never referenced in the codebase.
| Before …
=> Fix: no owners on template error when loading unsaved draft form

lib/integration/notifyConnector.ts
- Rewords error log when GC Notify request times out
=> refactor: reword error log for when a GC Notify request times out

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/Dialogs/ReportDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/FormOwnership.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/SetClosingDate.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/ConfirmDelete.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/ShareModal.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/ConfirmFormDeleteDialog.tsx, app/api/id/[form]/submission/report/route.ts, app/api/request/publish/route.ts, app/api/request/support/route.ts, components/clientComponents/admin/FormAccess/FormAccess.tsx, components/clientComponents/admin/JsonUpload/JsonUpload.tsx, components/clientComponents/admin/TemplateDelete/Settings.tsx, lib/hooks/auth/fetchWithCsrfToken.ts, lib/integration/freshdesk.ts, lib/utils/form-builder/blockLoader.ts, package.json, yarn.lock
- Updates NextJs to latest version (4.2.4 => 4.2.7).
- Updates Axios to latest (1.6.3 => 1.7.7)
- In an effort to try and reduce/eliminate the memory leak we are preemptively replace `fetch` with `axios`.  This aligns with all the other network calls set within the app code base.
- Removes the `process.env.NODE_ENV` check for existing axios calls on the client side.  The NODE_ENV variable does not exist outside of the scope of the Node server.  This was setting all of our axios calls client side to never timeout.
- Submit a support ticket 
- Open the 'Confirm Delete Modal' for a form with and without form submissions. 
This may or may not solve the memory leak we are currently seeing in Production / Staging
=> Chore: replace fetch with axios

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelActions.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelActionsButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBodyRoot.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBodySub.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SelectedElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/AddToSetButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/question/Question.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/PanelHightlight.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, lib/hooks/form-builder/useIsWithin.tsx, lib/types/form-builder-types.ts
| <img width="800" alt="before" src="https://github.com/user-attachments/assets/77c0b8c4-0650-42b9-af60-124ae65d50a8"> | <img width="800" alt="Screenshot 2024-09-09 at 8 03 31 AM" src="https://github.com/user-attachments/assets/484be449-3e2b-4034-9866-583c050c80c1"> |
| <img width="800" alt="before" src="https://github.com/user-attachments/assets/bd60ace2-4111-4685-9838-a4fe2376ce7d"> | <img …
=> chore: Style repeating sets

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SelectedElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/CustomizeSetButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/Dialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/DynamicRowDialog.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json, lib/hooks/form-builder/useHandleAdd.tsx, lib/middleware/schemas/templates.schema.json, lib/types/form-types.ts
- Adds dialog to customize dynamic row buttons
- Updates template schema to allow dynamic properties for custom button text
https://github.com/user-attachments/assets/d0687a2b-842f-487f-bf91-6054abd6166f
=> chore: Add dynamic row dialog

flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json
Minor part of #3564 used to allow the toggle on staging.
=> feat: Add feature flag for addressComplete.

lib/auditLogs.ts, lib/tests/auditLog.test.ts
Renames the property being sent to the Audit Log processing Lambda from `userID` to `userId` which aligns with the API Server audit logs.
closes #4275 
There is a larger refactor required that is out of scope to align the various variable namings throughout the Product.  Examples include: `formID` / `formId` / `userID` / `userId` 
=> Change userID to userId to align with other service lines

package.json, yarn.lock
Update react complex tree to latest.
=> chore: package update for react complex tree

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/api/actions.ts, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/api/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/SettingsNavigation.tsx, flag_initialization/default_flag_settings.json, lib/integration/zitadelConnector.ts, lib/templates.ts, lib/tests/templates.test.ts
This PR removes the "zitadelAuth" flag and instead does a privilege check in order to enable API Prototype testing in Production.
| Only available if "zitadelAuth" flag was active | User must be an owner of the form, including manage all forms, and have "View" "Flag" privilege (useIsAdminUser) |
With Manage All Forms and "View Flag" privilege you should be able to:
- View Settings API page,
- Create key,
- Refresh Key
- Delete Key
Without Manage All Forms or "View Flag" privilege you should NOT be able to:
- View Settings API page,
- Create key,
- Refresh Key
- Delete Key
There is a small risk …
=> feature: GC Forms adminstrators can access API settings

app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/flags.ts
Adds a dedicated feature flag for repeating sets.
=> chore: Add flag for repeating sets

app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/flags.ts, lib/hooks/form-builder/useElementOptions.tsx
Remove flag for experimental blocks.
=> chore: remove flag for experimental blocks

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElementModal.tsx
Fixes issue where the sub-element modal wasn't immediately updating the sub element panel view.
**Example of the issue:**
https://github.com/user-attachments/assets/429129ea-17e8-4c66-819b-c052d11e01e7
=> fix: sub element modal

package.json, tailwind.config.js, yarn.lock
Adds package and initial config for GCDS.
This will be used for 
https://github.com/cds-snc/platform-forms-client/pull/4343
https://github.com/cds-snc/platform-forms-client/pull/4319
=> chore: Add GCDS Tokens

.eslint-tailwindcss.js, components/clientComponents/forms/TextArea/TextArea.tsx, components/clientComponents/forms/TextInput/TextInput.tsx, lib/formBuilder.tsx, styles/_forms.scss, styles/_input.scss, styles/_textarea.scss
Updates styles for front facing text inputs and text areas
https://github.com/user-attachments/assets/d60dde01-b11e-45b2-9499-3d4595c50a88
=> chore: GCDS text inputs

components/clientComponents/forms/Radio/Radio.tsx, styles/_checkbox.scss, styles/_forms.scss, styles/_radio.scss
Adds styles for GCDS radio
🔗  https://design-system.alpha.canada.ca/en/components/radio-group/
https://github.com/user-attachments/assets/fdf28e71-7640-47ac-bbd5-6c1b4f71e741
=> chore: GCDS Radio

styles/_alert.scss, styles/_forms.scss
Update stying for error summary
🔗 https://design-system.alpha.canada.ca/en/components/error-summary/
=> chore: GCDS error summary

lib/responseDownloadFormats/html-aggregated/components/CopyCodes.tsx
Fixes missing styles for copy codes button
=> chore: fix copy codes button

components/clientComponents/forms/Dropdown/Dropdown.tsx, styles/_dropdown.scss, styles/_forms.scss
Updates styles for dropdown to match GCDS
🔗 https://design-system.alpha.canada.ca/en/components/select/
=> chore: GCDS Dropdown

app/(gcforms)/[locale]/(user authentication)/layout.tsx
Fixes layout issue for login etc... panel centering.
=> chore: fix centering for auth pages

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx, lib/hooks/form-builder/useHandleAdd.tsx
Finish conversion to using IDs vs indexes.
=> fix: Fix repeating set bug

components/clientComponents/forms/FormattedDate/FormattedDate.tsx, styles/_input.scss
Updates formatted date inputs to bring them more inline with GCDS styles
=> chore: style formatted date inputs

prisma/migrations/20241010102130_closed_details/migration.sql, prisma/schema.prisma
Standalone PR in support of https://github.com/cds-snc/platform-forms-client/pull/4389
Adds migration for custom closed message.
=> chore: add migration for custom closed message

package.json, yarn.lock
Package bump
Updating to latest will close https://github.com/cds-snc/platform-forms-client/pull/4285
=> chore: update Next JS to 14.2.15

.husky/pre-commit
=> chore: update husky pre-commit hook

package.json, yarn.lock
Bumps to latest replaces https://github.com/cds-snc/platform-forms-client/pull/4410
=> chore: update package markdown-to-jsx

package.json, yarn.lock
Updates NextAuth to latest Beta version 22.
This allows us to enable Turbo mode again when running in development mode (`yarn dev:turbo`).
=> chore: Update next auth to latest version

components/clientComponents/forms/AddressComplete/ManagedCombobox.tsx
=> fix: fix box width for address complete

package.json, yarn.lock
Update Zustand to latest (5.0.0)
=> chore: Bump Zustand 5.0.0

app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts
Adds feature flag for API screens work.
=> chore: add feature flag for API

lib/serviceAccount.ts, lib/tests/serviceAccount.test.ts, lib/types/form-builder-types.ts
- Adds form identifier to API key JSON structure
=> feat: add form identifier to API key data

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx
=> fix : Update Hint Text Position / Panel Body for AddressComplete

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/ClosingDateDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx
Fixes an issue with future dates in the schedule close dialog.
=> fix: Fixes an issue with the schedule close dialog

i18n/translations/en/common.json, i18n/translations/fr/common.json
Removes conditional logic feature banner.
**Removes**
=> chore: Turn off new feature banner

i18n/translations/fr/form-builder.json
=> chore: Update close message error strings

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/EditWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/page.tsx
Adds a wrapper around the key check for the edit page.
=> chore: add wrapper around key check

lib/integration/freshdesk.ts
Fixes check for review env check
=> chore: update check for review env

lib/integration/freshdesk.ts
Related to #4553 
REVIEW_ENV is either undefined or 1 based on the docker file used to build the application.
=> Review ENV variable is 0 or 1

components/clientComponents/forms/AddressComplete/utils.ts
PO Boxes didn't work, now they do. Closes #4579
=> fix: Add Line1 for POBoxes.

components/clientComponents/forms/AddressComplete/utils.ts
Closes #4595
also
Closes #4603
=> fix : AddressComplete - add check for empty line1, and try line2 if available

lib/managedData/data/organizations.json
Updates the organizations.json file for the Departments managed list.
=> chore: Update departments Managed list

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/ExampleWrapper.tsx, components/clientComponents/forms/AddressComplete/AddressComplete.tsx
=> fix: Resolve error with component causing controlled component.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/page.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/clientSide.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, components/clientComponents/forms/Form/Form.test.js, components/clientComponents/forms/Form/Form.tsx
Attempting to fix the issue with server actions on Next 15
https://github.com/vercel/next.js/discussions/58431#discussioncomment-7620263
=> chore: Pass the submitForm server action as a prop

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/page.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/clientSide.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, components/clientComponents/forms/Form/Form.test.js, components/clientComponents/forms/Form/Form.tsx
=> chore: Revert Pass the submitForm server action as a prop (#4634)

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx
Removing an unnecessary comment
=> chore: Remove comment

components/clientComponents/forms/Form/Form.tsx
=> chore: try refresh

lib/managedData/data/organizations.json
Update the Departments managed data file.
=> chore: Update departments.json

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx
Fix for https://gcdigital.slack.com/archives/C05G75MNP4Z/p1731516703773649
Reverts template check and updates API key check for layout.
=> chore: update api check

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/settings/SettingsPanel.tsx
=> chore: update check for settings panel 

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[statusFilter]/components/SystemStatus.tsx, i18n/translations/en/form-builder-responses.json
Adds report a problem status box
=> chore: Add report a problem for API mode

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/ApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/GenerateKeySuccess.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
- Add API key generation toast message
- Add onscreen message to delete api key to modify response delivery
=> chore: Add API key generation toast + onscreen message

.gitignore, utils/responseRetriever/README.md, utils/responseRetriever/accessTokenGenerator.ts, utils/responseRetriever/formSubmissionDecrypter.ts, utils/responseRetriever/formSubmissionIntegrityVerifier.ts, utils/responseRetriever/gcFormsApiClient.ts, utils/responseRetriever/index.ts, utils/responseRetriever/package.json, utils/responseRetriever/tsconfig.json, utils/responseRetriever/types.d.ts, yarn.lock
- Download and install Node.js version 22
- (with Node.js installer) https://nodejs.org/en/download/prebuilt-installer
- (with Brew) `brew install node@22`
To make sure Node.js is properly installed, try to run the following command `node --version`.
- Put the private key file you have generated through the GCForms web application in this folder next to the `index.ts` file. Make sure the file name ends with `_private_api_key.json`
- Install required dependencies by running the following command `yarn install`
```shell
$ yarn retrieve
```
=> feature: Add interactive script to download and confirm submissions

lib/managedData/README.md, lib/managedData/data/organizations.json, lib/managedData/organizations.ts
Updates the organizations list.
Create a new form and add "Department" section. Open the Preview mode and in the department dropdown search for "Canadian Intergovernmental Conference Secretariat" - it should be in the list.
=> chore: Updates organizations list

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/Item.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/itemType.ts
Updates the TreeView to remove markdown chars.
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4177
=> chore: clean markdown from TreeView

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/treeview/util/removeMarkdown.vitest.ts
Adds unit test for remove markdown
=> chore: Add tests for remove markdown

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx, i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
Updates publish page to handle API mode.
Fixes https://github.com/cds-snc/platform-forms-client/issues/4726
=> chore: fix delivery option text for publish page

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/DeleteApiKeyDialog/DeleteApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx
Fixes linking issue to close form.
Fixes #4736
=> chore: fix link to closing date

lib/store/storage.ts, lib/store/useTemplateStore.tsx
Move template store options file to standalone function.
=> chore: move template storage options

lib/store/helpers/move/index.ts, lib/store/helpers/move/moveDown.ts, lib/store/helpers/move/moveUp.ts, lib/store/types.ts, lib/store/useTemplateStore.tsx
Breaks move up and move down out into helper methods.
=> chore: add move helpers

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx
Fixes issue where most recent saved value was not saved back to the template store.
=> chore: save purpose option to template store

lib/store/helpers/move/index.ts, lib/store/helpers/move/subMoveDown.ts, lib/store/helpers/move/subMoveUp.ts, lib/store/useTemplateStore.tsx
Adds helpers for moving sub elements.
=> chore: add helpers for moving sub elements

lib/managedData/README.md, lib/managedData/data/organizations.json
Updates organization list to latest.
See slack thread https://app.slack.com/client/T2G2S06PM/C03T4FAE9FV?selected_team_id=T2G2S06PM
Check the new department is in the list
=> chore: Updates organization list to latest

lib/store/helpers/add/add.ts, lib/store/helpers/add/addSubItem.ts, lib/store/helpers/add/index.ts, lib/store/helpers/move/moveDown.ts, lib/store/helpers/move/moveUp.ts, lib/store/helpers/move/subMoveDown.ts, lib/store/helpers/move/subMoveUp.ts, lib/store/types.ts, lib/store/useTemplateStore.tsx
- Create initial add helpers
- Updates types
- Test adding items + add sub items
=> chore: create "Add helpers" for template store

package.json, yarn.lock
=> chore: Add Athena SDK Package

lib/store/helpers/id/generateElementId.ts, lib/store/helpers/id/getHighestElementId.ts, lib/store/helpers/id/index.ts, lib/store/useTemplateStore.tsx
Update to use helpers for generating element ids.
=> chore: add helpers for generate element

components/clientComponents/forms/Form/Form.tsx, lib/store/useTemplateStore.tsx
Update useTemplateStore to use single line where possible for setters + rearrange the order in store.
=> chore: move getters and setters

components/clientComponents/forms/Form/Form.tsx
Adds a log message when the session is saved after a server action is moved.
=> chore: Add log message when session saved

components/clientComponents/forms/Form/Form.tsx
=> chore: Return (exit) after catching missing server action

package.json, yarn.lock
=> chore: bump next js version

components/clientComponents/globals/Footer.tsx, components/serverComponents/globals/Footer.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Updates footer to include about link.
=> chore: add about gc forms link

packages/gcforms-types/src/index.ts, tsconfig.json
Adds a tsconfig path alias for the new packages type library.
=> chore: Add tsconfig type package alias

lib/hooks/form-builder/useHandleAdd.tsx
Adds missing dependancy for useHandleAdd
=> chore: fix dependancy array for use handle add

.github/workflows/cypress-component.yml, .github/workflows/eslint.yml, .github/workflows/jest.yml, .github/workflows/vitest.yml, package.json
Updates config and Docker files to remove build step for types package.
We're now using the src file and the root tsconfig 
see: https://github.com/cds-snc/platform-forms-client/pull/4887/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R31
=> chore: update workflow files for shared types package

app/api/id/[form]/submission/report/route.ts, lib/vault.ts
Part 8 of https://github.com/cds-snc/platform-forms-client/issues/4287
- Replaces any reference to the old `Status` with new `Status#CreatedAt` attribute when requesting Vault items.
=> refactor: replace use of Status with new Status#CreatedAt attribute when requesting Vault items

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/CustomizeSetButton.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4865
=> fix: Repeating set changes not being saved

lib/privileges.ts
Adds data to log for failed privilege check
=> chore: log details for Privilege Check error

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx
=> fix: Publish Checklist confirmation message always checked.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ManageFormAccessDialog/UserActions.tsx
=> fix: Email Text not Appearing in Manage User Access (for Submissions)

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts
Bug fix related to #4970 
Updates signature of submitForm to accept both FormRecord or ID
The previous release caused an issue where open forms were submitting according to the old signature after release and throwing errors.
=> chore: Update submitForm signature to accept either id or PublicFormRecord

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts
PR to follow-up # 4994
We now have enough info to re-visit the feature later.
=> chore: remove log message 

i18n/translations/en/form-builder.json, i18n/translations/fr/form-builder.json
=> chore: Add missing "example" string

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/PanelHightlight.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/sub-elements/SubElement.tsx
Update to look for panel clicks for sub-elements
Fix for: https://github.com/cds-snc/platform-forms-client/issues/4824
=> chore: handle panel clicks for sub elements

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/RulesDialog/RulesDialog.tsx
=> fix: Add missing Close button to Rules dialog.

lib/invitations/tests/fixtures/AppUser.ts, lib/invitations/tests/fixtures/User.ts, lib/invitations/tests/invitations.test.ts, lib/tests/privileges.test.ts, lib/users.ts, prisma/migrations/20250122171153_add_notes_column_to_user/migration.sql, prisma/schema.prisma
Adds a `notes` column to `User` in preparation for #4987
=> chore: Add notes column to User

app/(gcforms)/[locale]/(user authentication)/components/client/forms/Dropdown.tsx, app/(gcforms)/[locale]/(user authentication)/components/client/forms/Label.tsx, components/clientComponents/forms/AddressComplete/AddressComplete.tsx, components/clientComponents/forms/Dropdown/Dropdown.tsx, components/clientComponents/forms/FileInput/FileInput.tsx, components/clientComponents/forms/Label/Label.tsx, lib/formBuilder.tsx, lib/types/component-utility-types.ts
=> fix:  Correct "required", "no selection", "Select file" in preview being only english.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx
=> fix: Fix the validation message translations not occuring for Preview of Forms

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/branding/components/Branding.tsx
=> chore: Update branding form link in UI

app/(gcforms)/[locale]/(form administration)/forms/components/Invitations/Invitations.tsx, lib/invitations/acceptInvitation.ts, lib/invitations/inviteUserByEmail.ts, lib/invitations/tests/fixtures/Invitation.ts, lib/invitations/tests/invitations.test.ts, prisma/migrations/20250127184750_add_invitations_to_user_model/migration.sql, prisma/schema.prisma
This PR:
- ensures an audit log is always created when a user invites another individual to collaborate on a Template
- adds a relation on Invitation and User to link the two.  This way we can record who created the invite for a user once it was accepted.  The relation could also be used manage or display who 'created' the invitations on the Template.
Ensure that a user can invite and that the secondary user can accept or delete invitations.
=> Chore: audit log invites

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/PreviewClosed.tsx, components/clientComponents/forms/ClosedPage/ClosedPage.tsx, components/serverComponents/globals/Buttons/LinkButton.tsx
=> fix : Open Preview Forms Close Page to new Tab

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/Publish.tsx
=> fix : Show email on publish page if delivery option is set to email.

lib/responseDownloadFormats/csv/index.ts
Context: https://gcdigital.slack.com/archives/C08ATSV2R26
- Reverts previous CSV output changes (https://github.com/cds-snc/platform-forms-client/pull/5029)
=> fix: revert previous CSV output changes

app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts
Adds feature flag for save and resume later.
=> chore: Add feature flag for "save and resume"

lib/deactivate.ts
Temporarily updates deactivation email template.
=> chore: update deactivation email

components/clientComponents/forms/Review/Review.tsx, components/clientComponents/forms/Review/ReviewList.tsx, components/clientComponents/forms/Review/helpers.ts, lib/hooks/useGCFormContext.tsx, lib/utils/getGroupTitle.ts
Updates review component to break out a Review List as a component that will take a list of review items.  This removes the need for all the client side hooks.
=> chore: Update review component to make it server renderable 

components/clientComponents/forms/FormattedDate/FormattedDate.tsx, lib/formBuilder.tsx
Fixes #5096 
Pass language into formattedDate component.
=> fix: Pass lang prop into formattedDate component

lib/tests/validation/validation.test.js, lib/validation/validation.tsx
Adds nfb.ca to valid domain list
=> chore: Add nfb email to valid

components/clientComponents/forms/ResumeForm/ResumeForm.tsx, components/clientComponents/forms/SaveAndResume/ConfirmDownloadDialog.tsx, i18n/translations/en/common.json, i18n/translations/en/form-builder.json, i18n/translations/fr/common.json, i18n/translations/fr/form-builder.json
Addresses part of #5097 by updating content in English and French
https://www.figma.com/design/YoCpkitdwq2DGnp3lh0M4i/Pause-and-resume?node-id=4393-8612&t=pcSBskAHXYc7MvDO-0
=> chore: Bilingual content for "Save and resume"

lib/tests/validation/validation.test.js, lib/validation/validation.tsx
Add `debates-debats` email to validation check.
=> Chore: add email for debates-debats

.github/labeler.yml, .github/workflows/labeler.yml, prisma/schema.prisma
Adds the `!! Database Migration !!` and `!! Package Update !!` labels.
Database Migration label will be added when a PR modifies `./prisma/migrations/**` or `./prisma/prisma.schema`
Package Update label will be added when a PR modifies `./packages/**`
Nothing really to test.  You can see the commit history below where a test commit to `prisma.schema` triggered the addition of the database migration label.  Removing those changes then removed the label from the PR.
Doesn't inform on how to deal with database migrations that will break older version of the app that are still running.
=> feature: Add labels to PRs for db migrations and package changes.

components/clientComponents/forms/ResumeForm/ResumeForm.tsx
Adds error log for resume form error.
=> chore: add error log for upload error

package.json
Remove unnecessary resolutions from package.json
Removes
```
"resolutions": {
"@types/react": "19.0.8",
"@types/react-dom": "19.0.3"
}
```
=> chore: package.json cleanup

yarn.lock
=> chore: fix lock file

package.json, yarn.lock
=> chore: bump eslint config next

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/tests/AddElementButton.cy.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/tests/ElementDialog.cy.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/close/SetClosingDate.tsx, app/(gcforms)/[locale]/layout.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts, lib/hooks/form-builder/useElementOptions.tsx
Cleanup PR to remove some unneeded feature flags.
=> chore: remove feature flags for repeating sets and set closing date

i18n/translations/fr/common.json
=> fix: Fix typo in French asking for valid dates.

lib/saveAndResume/actions.ts
Update catch handling for save and resume
=> chore: update warn for save and resume

package.json
https://github.com/vercel/next.js/releases/tag/v15.2.1
=> chore: Bump Next JS 15.2.1

yarn.lock
Sync lock will all the updates.
=> chore: update lock

app/(gcforms)/[locale]/(static pages)/sla/page.tsx, app/(gcforms)/[locale]/(static pages)/terms-and-conditions/page.tsx, app/(gcforms)/[locale]/(static pages)/terms-of-use/page.tsx, app/(gcforms)/[locale]/(static pages)/unable-to-process/page.tsx, i18n/index.ts, i18n/utils.ts, lib/actions/auth.ts, lib/auth/nextAuth.ts, lib/pages/auth.ts, lib/privileges.ts, middleware.ts
Adds React Cache functionality around the following functions:
- `auth`
- `getAbility`
- `serverTranslation`
Multiple server components were calling the various functions on each render.  Wrapping the functions in Reacts `cache` ensures that they are only evaluated once when given the same arguments (memoized).
You can see an example below with `serverTranslations`.
| ![Screenshot 2025-03-11 at 9 58 59 AM](https://github.com/user-attachments/assets/d1e92f9b-c693-4e65-8896-3927d148964a) | ![Screenshot 2025-03-11 at 10 00 52 AM](https://github.com/user-attachments/assets/8a4368de-5381-4084-a317-2a …
=> chore: small opitmizations

app/(gcforms)/[locale]/(form administration)/forms/components/server/NewFormButton.tsx
=> chore: Add a small margin to the create new form button.

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ManageFormAccessDialog/ManageUsers.tsx, i18n/translations/en/manage-form-access.json, i18n/translations/fr/manage-form-access.json
=> chore: Updated messaging for invitations dialog

components/clientComponents/forms/ClosedPage/ClosedPage.tsx
=> chore: move closed icon

app/(gcforms)/[locale]/layout.tsx, components/clientComponents/globals/Header/Header.tsx, flag_initialization/default_flag_settings.json, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts
=> chore: adds caretaker feature flag

.github/workflows/rainbow-deployment/action.yml, .github/workflows/staging-deploy.yml, Dockerfile.rainbow, bin/bump-load-balancer-listener-rainbow-rules-priority.sh, bin/set-rainbow-lambda-env-vars.sh
Linked to https://github.com/cds-snc/forms-terraform/pull/961
- Adds new Dockerfile.rainbow to package legacy GC Forms image in order to run them in a Lambda function
- Adds new rainbow deployment Github composite action
- Integrates rainbow deployment Github composite action in Staging deploy action
=> feat: rainbow deployment

packages/connectors/package.json, packages/connectors/src/postgres-connector.ts
- Removes Localstack support from Postgres connector
=> chore: remove Localstack support for Postgres connector

.github/workflows/staging-deploy.yml
- Disables Rainbow deployment (temporarily)
=> fix: disable Rainbow deployment (temporarily)

lib/integration/freshdesk.ts
=> fix: extra space in log

lib/integration/freshdesk.ts
=> chore: remove extra space in log

package.json, yarn.lock
=> chore: update Vitest

lib/saveAndResume/InProgressBadge.tsx, lib/saveAndResume/SubmittedBadge.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5201
<hr>
=> chore: update date output for download progress + confirm HTML

lib/client/clientHelpers.ts
Updates code to scroll focus item into view.
Fixes #5325
=> chore: try scroll into view

components/clientComponents/forms/SaveAndResume/SaveAndResume.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5347
=> chore: add icon for load answer

i18n/translations/en/common.json
> Load answers --> Load your answers
=> chore: minor content edit

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/BackButton.tsx, components/clientComponents/forms/BackButtonGroup/BackButtonGroup.tsx, components/clientComponents/forms/NextButton/NextButton.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5362
https://github.com/user-attachments/assets/426b3a90-8fba-4922-8b1e-2988cca74221
Before:
https://github.com/user-attachments/assets/a2ebdffb-2e1d-4fd5-bb75-5be89130d31e
=> chore: update next & back buttons for < laptop width

packages/connectors/CHANGELOG.md, packages/connectors/package.json, packages/types/CHANGELOG.md, packages/types/package.json
- Adds `CHANGELOG.md` files for our packages
=> chore: add CHANGELOG.md files for our packages

components/clientComponents/forms/SaveAndResume/SaveResponse.tsx
https://github.com/user-attachments/assets/5bad2849-f639-4444-900d-090850fe715e
=> chore: fix hover style for get a copy button

packages/connectors/CHANGELOG.md, packages/connectors/package.json, utils/cognitoBackup/package.json, utils/responseGenerator/package.json, utils/responseRetriever/package.json, yarn.lock
- Updates Axios package to version `1.8.4`
=> chore: update Axios package to version 1.8.4

app/(gcforms)/[locale]/(form administration)/form-builder/components/shared/right-panel/RightPanel.tsx, components/clientComponents/globals/Buttons/Circle.tsx, components/clientComponents/globals/Buttons/CircleButton.tsx, cypress/e2e/form-builder/form-builder.cy.ts
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4739
Modify styling for form setup to avoid text overlap problems
https://github.com/user-attachments/assets/45b27a50-5d40-4be0-8a79-6916af80c691
=> chore: Update styling for form setup button

components/clientComponents/globals/Footer.tsx, components/serverComponents/globals/Footer.tsx, components/serverComponents/globals/Version.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Partial fix for ref:  https://github.com/cds-snc/platform-forms-client/issues/5399
<hr>
=> chore:  Add GC Forms version to Footer

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/buildFormDataObject.ts
Small update for string handling.
=> chore: update string check

app/(gcforms)/[locale]/(form administration)/form-builder/components/ShareModal.tsx, app/api/share/route.ts, lib/validation/isValidEmail.ts, lib/validation/isValidEmail.vitest.ts
- Updates route to pull template direct from DB vs passing from the UI
- Validates email addresses
- Shortens filename as needed.
=> chore: update share modal

lib/store/storage.ts, middleware.ts
- Updates middleware to return early on payload check
- Updates session storage error handling
=> chore: Add return for middleware check

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/saveAndResume/SetSaveAndResume.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/clientSide.tsx, app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, app/(gcforms)/[locale]/layout.tsx, components/clientComponents/forms/ResumeForm/ResumeForm.tsx, components/clientComponents/forms/TextPage/TextPage.tsx, cypress/e2e/attestation.cy.ts, cypress/e2e/cds_intake.cy.ts, cypress/e2e/platform_intake.cy.ts, cypress/e2e/tsb_contact.cy.ts, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts, lib/flags/default_flag_settings.json
Clean-up PR to remove save and resume feature flag now that the feature is on by default.
=> chore: remove feature flag for save and resume

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts, lib/validation/validation.tsx
- Adds email check
- Updated check for valid type
-
=> chore: add response check

lib/validation/isValidEmail.ts
Adds max length to email check
See:
https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address
=> chore: add email length check

lib/origin.ts
=> chore: update get origin for tests

instrumentation.ts
This is a quick fix for the performance issues we are noticing that impact the PR Review environments and the Legacy deployments.
While working on a more elegant solution as side-of-desk this change will at least alleviate the immediate concern.
Ensures that the "instrumentation" on server start up is only done on latest app instances and not PR Review Environments or Legacy Deployments.  
=> Check to see if running in lambda env

styles/_base.scss
Update to use GCDS token for body color.
```css
body {
color: var(--gcds-text-primary);
}
```
=> chore: update body copy color

app/(gcforms)/[locale]/(form administration)/form-builder/actions.ts, lib/auth/2fa.ts, lib/auth/passwordReset.ts, lib/deactivate.ts, lib/integration/notifyConnector.ts, lib/invitations/inviteUserByEmail.ts, lib/invitations/tests/invitations.test.ts, lib/templates.ts
- Reworks error logs around GC Notify to make sure we know what type of email failed to be sent.
=> chore: rework error logs around GC Notify integration to add context and be able to know what kind of email failed to be sent

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ActionsPanel.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3138
=> chore: move download button for responses page

lib/responseDownloadFormats/html-aggregated/components/CopyCodes.tsx, lib/responseDownloadFormats/html/components/ResponseSection.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3637
=> chore: update copy to clipboard position

package.json, yarn.lock
=> chore: update axios

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/DownloadCSVWithGroups.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4920
=> chore: move privacy policy text for translate csv

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/DownloadCSVWithGroups.tsx
Fixes: 
https://github.com/cds-snc/platform-forms-client/issues/4125
=> chore: use "page" for csv

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/LeftNavigation.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/2915
=> chore: update default tab for settings after publish

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/SelectedElement.tsx
Update to force an element type for emails.
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5059
=> chore: force element type for email

app/(gcforms)/[locale]/(user authentication)/auth/logout/components/LocalTime.tsx, app/(gcforms)/[locale]/(user authentication)/auth/logout/page.tsx, components/clientComponents/globals/Header/YourAccountDropdown.tsx
Fixes https://github.com/cds-snc/platform-forms-client/issues/4103
- Saves logout time to a session var so it doesn't change on every load.
=> fix:  Sign out page time changes

app/(gcforms)/[locale]/(app administration)/admin/(no nav)/typography/page.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/preview/Preview.tsx, app/(gcforms)/[locale]/(support)/support/components/client/SupportForm.tsx, app/(gcforms)/[locale]/(support)/support/page.tsx, components/clientComponents/forms/Form/Form.tsx, components/clientComponents/globals/Alert/Alert.tsx, components/clientComponents/globals/layouts/FormDisplayLayout.tsx, components/serverComponents/globals/GcdsH1.tsx, styles/_gc-header.scss, styles/_typography.scss
Update headings to use GCDS tokens
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4065
=> chore: update headings

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/layout.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/4894
https://github.com/user-attachments/assets/efd9b50f-565e-4c77-896f-ce813466c19f
=> fix : Footer not always glued to the bottom of the window

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/PrePublishDialog.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5512
=> fix: ensure proper default value for form type (publish)

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/ApiKeyDialog/ApiKeyDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ApiKeyButton.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/components/ResponseDelivery.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/settings/manage/page.tsx
Ensure save classification happens as needed when creating an API key.
=> fix: ensure classification is saved when creating an API key

app/(gcforms)/[locale]/layout.tsx, i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json, lib/cache/types.ts, lib/flags/default_flag_settings.json, lib/hooks/form-builder/useElementOptions.tsx
Update to allow file input via feature flag.
=> chore: add feature flag for file upload

i18n/translations/en/admin-flags.json, i18n/translations/fr/admin-flags.json
=> chore: i18n feature flag strings

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts, components/clientComponents/forms/Form/Form.tsx
Updates hCAPTCHA error handling to be more consistent by returning an error object -vs- throwing an error that is handled.
Try submitting a form. The form should submit.
=> chore: Updates hCAPTCHA error handling to be more consistent

components/clientComponents/forms/Review/EditButton.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5058
Updates review page edit titles to be left aligned.
=> chore: fix review title alignment

packages/editor/CHANGELOG.md, packages/editor/package.json, yarn.lock
Bumps Lexical to latest 0.31.1 (from 0.30.0)
=> chore: Bump Lexical version

app/(gcforms)/[locale]/(form filler)/id/[...props]/actions.ts, lib/notifications.ts
Fixes an issue where notifications were still being sent when the email delivery options was selected.
=> fix: fixes notifications sending when delivery is email

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/RulesDialog/RulesDialog.tsx
Appears to be a bit of leftover testing text
=> chore: Cleanup testing text string

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/ElementPanel.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/PanelBody.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/ElementDialog.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/ExampleWrapper.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/element-dialog/descriptions/FileInput.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/translate/components/TranslateWithGroups.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/publish/components/Publish.tsx, components/clientComponents/forms/FileInput/FileInput.tsx, components/clientComponents/forms/FileInput/ResetButton.tsx, components/clientComponents/globals/BetaBadge.tsx, i18n/translations/en/common.json, i18n/translations/en/form-builder.json, i18n/translations/fr/common.json, i18n/translations/fr/form-builder.json, lib/hooks/form-builder/useAllowFileUpload.tsx, lib/hooks/form-builder/useAllowPublish.tsx, lib/hooks/form-builder/useElementOptions.tsx, styles/_forms.scss
Updates Add element dialog for file upload
=> chore: Dialog updates for file upload

lib/vitests/filterShownElements.test.ts
Should clear up some linting errors
=> chore: Cleanup types in test

components/clientComponents/forms/FileInput/FileInput.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json
Update file input to use Live Region.
=> chore: add speak for file input

app/(gcforms)/[locale]/(form filler)/id/[...props]/page.tsx, components/clientComponents/forms/Form/Form.tsx, components/clientComponents/forms/SubmitProgress/GCFormsIcon.tsx, components/clientComponents/forms/SubmitProgress/ProgressBar.tsx, components/clientComponents/forms/SubmitProgress/Spinner.tsx, components/clientComponents/forms/SubmitProgress/SubmitProgress.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json, lib/hooks/useCustomEvent.tsx
Updates submission spinner component.
Option A) shows progress using a generic spinner
Option B) shows a progress bar - bar has a listener for `submit-progress` event
```javascript
document.dispatchEvent(
new CustomEvent("submit-progress", {
detail: { progress: 20 },
})
);
```
Option B is not in use yet just available. 
Submit using spinner
https://github.com/user-attachments/assets/cd5db443-3be4-4dbd-89f9-48422d84c6de
```
https://github.com/user-attachments/assets/0bde152c-4554-4208-bf55-489daae3ff1a
=> chore: add submit progress bar

packages/connectors/CHANGELOG.md, packages/connectors/package.json, packages/connectors/src/gc-notify-connector.ts, yarn.lock
Context: we are trying to investigate on that timeout error we sometimes get when calling the GC Notify API.
- Replaces [Axios](https://www.npmjs.com/package/axios) with [Got](https://www.npmjs.com/package/got) for our Connectors package (only)
=> feat: replace Axios with Got in connectors package

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/responses/[[...statusFilter]]/components/ActionsPanel.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3630
https://github.com/user-attachments/assets/99b37128-6aed-4e21-9736-2f1e204b77a3
=> chore: fix sticky spacing

app/(gcforms)/[locale]/(user authentication)/auth/reset-password/[[...token]]/components/server/CheckEmail.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/3624
Link back login page and not the homepage
=> chore: link back to sign-in

components/clientComponents/forms/DynamicRow/DynamicRow.tsx
=> fix: Fix dynamic row empty rows error

app/(gcforms)/[locale]/(app administration)/admin/(with nav)/accounts/components/server/UsersList.tsx, app/(gcforms)/[locale]/(support)/unlock-publishing/actions.ts
Adds account link from request unlock publishing ticket email.
=> chore: Add link to account page from request publish ticket

package.json, packages/connectors/CHANGELOG.md, packages/connectors/package.json, packages/connectors/src/gc-notify-connector.ts, yarn.lock
- Puts back Axios in connectors package (instead of Got)
=> chore: revert Axios/Got switch in connectors package

components/clientComponents/globals/BetaBadge.tsx
Fixes colour contrast issue with Beta Badge
=> chore: update bg contrast for beta badge

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/components/dialogs/MoreDialog/RequiredOptions.tsx, cypress/e2e/form-builder/form-builder.cy.ts
Updates more menu checkbox to match document types checkbox (GCDS checkbox style)
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5784
https://github.com/user-attachments/assets/c433482c-4d03-4bd7-bee2-329697e82389
=> chore: fix styling for required checkbox (more modal)

prisma/seeds/seed.ts
Removes data migrations no longer needed.
=> chore: notification v2 data migration - part 3

components/clientComponents/forms/NextButton/NextButton.tsx
=> chore: remove dead end check

app/(gcforms)/[locale]/(form filler)/id/[...props]/lib/server/parseRequestData.ts
* Fixes #5933 when file_upload_s3_direct branch is merged.
=> fix : Fix dynamics rows producing empty elements.

components/clientComponents/forms/FileInput/FileInput.tsx, i18n/translations/en/common.json, i18n/translations/fr/common.json, lib/fileInput/handleUploadError.ts, lib/validation/validation.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/5992
Update error messages to show max file size
=> chore: show max file size

components/clientComponents/forms/FileInput/FileInput.tsx
Fixes: https://github.com/cds-snc/platform-forms-client/issues/6066
Ref: https://github.com/cds-snc/platform-forms-client/pull/6025
Bug:
Staging vs local with fix
https://github.com/user-attachments/assets/ae096a46-c613-4567-b9b8-e995772a2014
Test file
[my-jpeg-form-2025-08-27.json](https://github.com/user-attachments/files/22006398/my-jpeg-form-2025-08-27.json)
=> fix: ensure mime type for file inputs when set

packages/editor/CHANGELOG.md, packages/editor/package.json
Updates Lexical to latest
https://github.com/facebook/lexical/releases/tag/v0.35.0
=> chore: bump lexical

cypress/support/commands/commands.ts
Update the useForm command to have better log outputs.
=> chore: Log use form errors

app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOption.tsx, app/(gcforms)/[locale]/(form administration)/form-builder/[id]/edit/components/elements/SubOptions.tsx
Applying same fix for sub-options
ref: https://github.com/cds-snc/platform-forms-client/pull/6182
=> chore: fix lint for sub options
